### ISSUE TITLE
Error when showing the splash screen

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1030]
See below. Not reproducible. Comes sometimes during the very first start of PK-Sim (after new installation).

```
Application:
PK-Sim® 7.4.0.98

Parameter is not valid.

Stack trace:

at System.Drawing.Graphics.get_PageUnit()
   at DevExpress.Utils.Text.FontsCache.GetFontCacheByFont(Graphics graphics, Font font)
   at DevExpress.Utils.Text.TextUtils.GetStringSize(Graphics g, String text, Font font, StringFormat stringFormat, Int32 maxWidth, Int32 maxHeight, IWordBreakProvider wordBreakProvider, Boolean& isCropped)
   at DevExpress.Utils.Text.TextUtils.GetStringSize(Graphics g, String text, Font font, StringFormat stringFormat, Int32 maxWidth, Int32 maxHeight, Boolean& isCropped)
   at DevExpress.Utils.Paint.XPaintMixed.CalcTextSize(Graphics g, String s, Font font, StringFormat strFormat, Int32 maxWidth, Int32 maxHeight, Boolean& isCropped)
   at DevExpress.Utils.Paint.XPaintMixed.CalcTextSize(Graphics g, String s, Font font, StringFormat strFormat, Int32 maxWidth)
   at DevExpress.XtraEditors.ViewInfo.LabelControlViewInfo.CalcSimpleTextSize(String Text, Boolean useHotkeyPrefix, LabelAutoSizeMode mode, Int32 predWidth, Int32 predHeight)
   at DevExpress.XtraEditors.ViewInfo.LabelControlViewInfo.CalcTextSize(String Text, Boolean useHotkeyPrefix, LabelAutoSizeMode mode)
   at DevExpress.XtraEditors.ViewInfo.LabelControlViewInfo.CalcTextSize(Boolean useHotkeyPrefix)
   at DevExpress.XtraEditors.ViewInfo.LabelControlViewInfo.CalcTextPoints()
   at DevExpress.XtraEditors.ViewInfo.LabelControlViewInfo.CalcContentRect(Rectangle bounds)
   at DevExpress.XtraEditors.ViewInfo.BaseControlViewInfo.CalcRects()
   at DevExpress.XtraEditors.ViewInfo.BaseControlViewInfo.CalcViewInfo(Graphics g)
   at DevExpress.XtraEditors.LabelControl.LayoutChanged(Boolean isVisualUpdate)
   at DevExpress.XtraEditors.LabelControl.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at PKSim.UI.Views.SplashScreen.set_StatusInfo(String value)
   at PKSim.Presentation.Presenters.Main.SplashViewPresenter.Handle(ProgressingEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by msevestre** [comment]
I have seen it in development but not in the exe!! 
It's only devexpress stuff at that stage. I feel we should upgrade to a new version soon

**Comment by msevestre** [comment]
Does it happen often?
