### ISSUE TITLE
Cannot open file after saving ...

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1058]
Hi, 
cannot open the file after saving and closing the project...
is there anything you can do about it? The file is huge (351mb) and a confidential...

Best, Tobias

Application:
PK-Sim® 7.2.2 - Build 3

Array cannot be null.
Parameter name: bytes

Stack trace:
```
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserialize(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<>c__DisplayClass5_0.<MapFrom>b__1(BuildingBlockMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@tobiasK2001 It looks like one of this case were the project got corrupted for some very unclear reason
Do you know what was done with the file before?

**Comment by tobiasK2001** [comment]
well quite a lot... I try to point out the most relevant things:

- as it was quite big I saved a back Version (8:50 am) under a new name
- than deleted a lot of Simulation and folders I used for obsolete Parameter identifications
- deleted the obsolete Parameter identifications
- added new fitted values to processes in the compound BB
- updated relevant simulations and cloned to new scenarios
- imported compound BB templates, formulation and administration BB from anotther PK-sim project
- build new DDI simulation withing the cleaned up PK-sim file
- I tried to open a PI, but this didn't worked with an error. I could ignore the error and opned the PI from the earlier saved back up.
- than further worked with the cleaned up PKsim file and checked a relevant PI in the cleaned up version. opened VPC and created some plots
- worked with the chart editor in the DDI plots. After copying and pasting the plots to a powerpoint I saved the project (15:39 pm) and closed the saved back up without saving again than I closed PK sim.
The next day I found that our automatic back up system created some conflict files. saved back ups with date and time.one file affected was the WJ file. In the earlier back up PK-sim project file (8:50 am) an older WJ version was opened. After renaming the conflict WJ fil to original name the  (8:50 am)  back up PK-sim project  could acces the most recent WJ file. However the cleaned up (15:39 pm) version still could not be opened.
However I can see in the cleaned up (15:39 pm) version still the history with entries untill 15:10 pm...
Does this makes some sense to you?
