### ISSUE TITLE
Error in Simulation

### ISSUE THREAD

**Issue by HASSANMY** [Open-Systems-Pharmacology/PK-Sim#1068]
Application:
PK-Sim® 7.3.0.42

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Presentation.DTO.Mappers.FormulationMappingDTOToFormulationMappingMapper.MapFrom(FormulationMappingDTO formulationMappingDTO, Simulation simulation)
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolFormulationPresenter.<SaveConfiguration>b__21_0(FormulationMappingDTO formulationMappingDTO)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolFormulationPresenter.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolPresenter.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundCollectorPresenterBase`2.<>c.<SaveConfiguration>b__11_0(TSubCompoundPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundCollectorPresenterBase`2.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolCollectorPresenter.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationWizardPresenter`1.<SaveBuildingBlocksConfiguration>b__15_0(ISubPresenterItem`1 x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Presentation.Presenters.Simulations.SimulationWizardPresenter`1.SaveBuildingBlocksConfiguration()
   at PKSim.Presentation.Presenters.Simulations.CreateSimulationPresenter.ModelConfigurationDone()
   at PKSim.Presentation.Presenters.Simulations.SimulationWizardPresenter`1.WizardCurrent(Int32 previousIndex, Int32 newIndex)
   at OSPSuite.Presentation.Presenters.WizardPresenter`3.WizardNext(Int32 currentIndex)
   at OSPSuite.UI.Views.WizardView.<InitializeWizard>b__27_3()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@HASSANMY Thanks for reporting the issue
Can you please provide us with the steps to reproduce the issue? Without those, we won't have a chance to fix them. Ideally, you would attach at test project so that we can see what's happening and fix the issue in the next version

Thanks for your help

**Comment by Yuri05** [comment]
Closing due to inactivity.
