### ISSUE TITLE
PK-Sim error message. Cannot save or open

### ISSUE THREAD

**Issue by LunaPrieto** [Open-Systems-Pharmacology/PK-Sim#1069]
I would need help with the following PK-Sim error. 
I just install the software on a new computer.
I can open the application but I cannot load previous projects or save new ones.
I will be very happy with any assistance on this. 
Thank you
/Luna

Application:
PK-Sim® 7.4.0.127

The type initializer for 'NHibernate.Cfg.Configuration' threw an exception.
-----------------------------------------------------
The type initializer for 'NHibernate.LoggerProvider' threw an exception.
-----------------------------------------------------
Unable to instantiate: NHibernate.Log4NetLoggerFactory
-----------------------------------------------------
Exception has been thrown by the target of an invocation.
-----------------------------------------------------
The type initializer for 'NHibernate.Log4NetLoggerFactory' threw an exception.
-----------------------------------------------------
Object reference not set to an instance of an object.

Stack trace:
```
at NHibernate.Log4NetLoggerFactory.GetGetLoggerMethodCall[TParameter]()
   at NHibernate.Log4NetLoggerFactory..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.Log4NetLoggerFactory..ctor()
 --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NHibernate.LoggerProvider.GetLoggerFactory(String nhibernateLoggerClass)
 --- End of inner exception stack trace ---
   at NHibernate.LoggerProvider.GetLoggerFactory(String nhibernateLoggerClass)
   at NHibernate.LoggerProvider..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.LoggerProvider.LoggerFor(Type type)
   at NHibernate.Cfg.Configuration..cctor()
 --- End of inner exception stack trace ---
   at NHibernate.Cfg.Configuration.Reset()
   at PKSim.Infrastructure.Services.SessionFactoryProvider.createSqlLiteConfigurationFor(String dataSource)
   at PKSim.Infrastructure.Services.SessionFactoryProvider.OpenSessionFactoryFor(String dataSource)
   at OSPSuite.Infrastructure.Services.SessionManager.OpenFactoryFor(String fileName)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
@LunaPrieto @PavelBal I moved this to the PK-Sim repo so that the discussion won't spam everyone watching forum entries.

@PavelBal : Are you getting the same error message as @LunaPrieto ?

**Comment by PavelBal** [comment]
@msevestre Yes

**Comment by msevestre** [comment]
@PavelBal Which version are you using BTW?

Does the problem occur as well with Version 7.3?

**Comment by PavelBal** [comment]
7.4. I do not have 7.3 atm (is it possible to have 7.3 and 7.4 installed concurrently? WIthout using a virtual machine..)

**Comment by LunaPrieto** [comment]
@msevestre I have version 7.4.
I just tried deleting it and re-installing it but it did not work for me. I still have the same error message. 
I also run the installation validation and that work perfectly. But I still cannot open/save files.

**Comment by msevestre** [comment]
yes you can install VErsion 7.3 using at least the portable version
@PavelBal : Can you download it, unzip it and see if that works?

https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/tag/v7.3.0.42

**Comment by msevestre** [comment]
@Yuri05 and @all

There seem to be an error documented here if some software has installed a dll that we do not use globally
https://github.com/nhibernate/nhibernate-core/issues/1836

@PavelBal Do you have the same issue with MoBi? Or just PK-Sim?
@PavelBal : Could you try to copy the log4net dll in your PK-Sim folder and see if this solves the issue? Version 2.0.8

**Comment by msevestre** [comment]
[net45-full.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2756787/net45-full.zip)
Here is a folder with log4net.dll
Can you try unzipping the content of the folder in your pksim install and see if this solves the issue?

**Comment by PavelBal** [comment]
@msevestre I had the issue with MoBi (did not try out with PK-Sim) and **yes**, copying the .dll in MoBi folder solves the issue.

**Comment by msevestre** [comment]
Wow. This is crazy. 
@LunaPrieto : can you try the workaround as well until we release a fix?

**Comment by msevestre** [comment]
@all: OK we have updated the portable version of PKSim and MoBi to include the workaround. This is what we'll advise people to use if they have the same problem

**Comment by msevestre** [comment]
[PK-Sim Portable with patch](https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/download/v7.4.0.127/pk-sim-portable-setup.zip)

[MoBi Portable with patch](https://github.com/Open-Systems-Pharmacology/MoBi/releases/download/v7.4.0.138/mobi-portable-setup.zip)

**Comment by harishkaushikbugworks** [comment]
finally i used the portable PKSIM and MOBI it worked
