### ISSUE TITLE
Exporting a simulation for an individual to Pk-Sim from Mobi

### ISSUE THREAD

**Issue by Dictatrix** [Open-Systems-Pharmacology/PK-Sim#1106]
Hi all, I'm using Pk-Sim and Mobi (last release, on Windows 10) and I need to export a simulation from Mobi to Pk-Sim (I need to perform a simulation on a particular individual), and I'm doing that with right click on mouse and choosing "send simulation to Pk-Sim for population simulation" (I need to perform it on a single individual, but that's not a problem because I can create 2 identical individual as population), and to do this I select " Use a population building block (typically for Pk-Sim)" and after that I've developed the second and indentical individual (all parameters range have the same values in the fileds "from" and "to") to get a population (on both of them I have selected the same 2 metabolizing enzymes), but when I click on "Start Import" I get this 
![screen0](https://user-images.githubusercontent.com/29026000/52973493-99e16880-33be-11e9-8aa8-e02f0c804819.PNG) , but I did not have seen any field with "dimensioless" option when I developed my population (2 identical individual), so I'm not understanding what is the problem and how could I solve it.

Any help and advice will be very appreciate.

Thanks in advance.

**Comment by msevestre** [comment]
Hey @Dictatrix,

This issue is due to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/440

In short, MoBi generates sometimes dimensions on the fly that pksim does not understand.
I am assuming that you may have added a parameter in your model that has the dimension Dimensionless. You probably have defined a RHS for this parameter and as such the dimension is now dimension per time

Can you update the dimension of your base parameter to something else that is supported (Amount, Concentration, Mass). If this is not clear, I can check your MoBi model and let you know which parameter is to change

**Comment by msevestre** [comment]
OR
export your simulation to pkml
open the file
and replace "Dimensionless per time" with "Inversed time"
and load the pkml file. It will work

**Comment by Dictatrix** [comment]
I've done that, but after the replacement when I try to open it with Pk-Sim I have this
![screen1](https://user-images.githubusercontent.com/29026000/52978846-3d3c7880-33d3-11e9-875f-49007b94eaca.PNG) , and if I try to open it with Mobi (to export it using "send simulation to Pk-Sim for population simulation") I have this
![screen0](https://user-images.githubusercontent.com/29026000/52978883-72e16180-33d3-11e9-99ab-957e28e2f2ef.PNG)

The Mobi simulation that I'm trying to export in Pk-Sim is Ogtt (a part of GlucoseInsulinModel), and in Ogtt I've changed only the numerical values of 3 parameters.

This is the error I get after clicking on "copy on clickboard":

Application:
MoBi 7.4.0.138

Invalid character in the given encoding. Line 8, position 243.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.SerializationTask.Load[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.ProjectTask.loadSimulationTransferFromFileUsingDimensionMode(String fileName, ReactionDimensionMode dimensionMode)
   at MoBi.Presentation.Tasks.ProjectTask.LoadSimulationTransferDataFromFile(String fileName)
   at MoBi.Presentation.Tasks.ProjectTask.<>c__DisplayClass15_0.<loadSimulationFromFileInProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
@Dictatrix Yeah the editor you used probably corrupted the file 
Can you send me the pkml file then? I'll be able to edit it for you and put it back here (please zip the file)

**Comment by Dictatrix** [comment]
[Folder.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2877704/Folder.zip)

Thank you very much

**Comment by msevestre** [comment]
ok try with this one . I could load it in MoBi and PKSim.
[Folder.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2877823/Folder.zip)

**Comment by Dictatrix** [comment]
Thank you very much, it worked perfectly

**Comment by msevestre** [comment]
Ok great.
