### ISSUE TITLE
Exception after opening a read only PK-Sim file

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#1108]
I wanted to just open an older PK-Sim file (created with a version below 7.4) which is located in a “read only folder” with PK-Sim version 7.4.

Then I get the following exception - without being able to open the file (it seems PK-Sim wants to write a converted file before opening it. Might be related to MoBi issue #353 but I get the error when just trying to open the file):

Application:
PK-Sim® 7.4.0.127

attempt to write a readonly database
attempt to write a readonly database

Stack trace:
```
at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo6_2(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@Christoph27 This has to be a very old project correct? It's trying to migrate the project to version 6.2! 
In that case this is exactly MoBi 353

**Comment by Christoph27** [comment]
The file is from Jan 2016

**Comment by Yuri05** [comment]
Not much we can do here. Copy the project file to a "writable" location first.

**Comment by UlrichSi** [comment]
Maybe the solution could be that in such cases, PK-Sim automatically creates a copy in the (writable) default TEMP directory which it then opens.

**Comment by PavelBal** [comment]
> Maybe the solution could be that in such cases, PK-Sim automatically creates a copy in the (writable) default TEMP directory which it then opens.

I vote against, I don't like the idea of automatically creating something somewhere without the approval of the user. Perhaps a more informative error text could help.

**Comment by Yuri05** [comment]
>>Maybe the solution could be that in such cases, PK-Sim automatically creates a copy in the (writable) default TEMP directory which it then opens.

>I vote against, I don't like the idea of automatically creating something somewhere without the approval of the user. Perhaps a more informative error text could help.

Agree. I wouldn't do it "secretly". What we could do instead:
* Check if project file is writable
* If not: try to remove "Readonly-Attribute" first
  * If succeeded: continue without any further actions
  * If not: show warning and ask user if he would like to continue. Something like 
    "_Project file is read only. It is recommended to copy the project file to another location. Otherwise errors could occur. Continue with opening the project (Yes/No)?_"

**Comment by Christoph27** [comment]
I wouldn't let PK-Sim try to remove the "Readonly-Attribute" first. Probably it is there on purpose.
If it is not possible to open the file without changing it (e.g. by keeping the conversion in memory), I would just show the suggested warning & additional information.

**Comment by Yuri05** [comment]
>I wouldn't let PK-Sim try to remove the "Readonly-Attribute" first. Probably it is there on purpose.
If it is not possible to open the file without changing it (e.g. by keeping the conversion in memory), I would just show the suggested warning & additional information.

Ok. makes life easier :)

**Comment by UlrichSi** [comment]
To specify my proposal in detail, hopefully removing the "secrecy aura":

- Initially do it like Yuri05's protocol but change the last bullet point and append the points below:
...
  - If not: Show warning that project is read-only and that a temporary project file is created (in the system's TEMP directory)
- When project is closed, prompt the user if the project is to be saved.
  - If yes or if the SAVE button is actively pressed, execute a SAVE AS command where the user is prompted for a new project file name.
- The temporary copy in the TEMP directory is deleted as soon as the project is saved or closed without saving.

**Comment by Yuri05** [comment]
>If not: Show warning that project is read-only and that a temporary project file is created (in the system's TEMP directory)

Disagree. The user should create temp file with an **_explicit_** action. And delete/copy it when finished also with an **_explicit_** action.

**Comment by UlrichSi** [comment]
@Yuri05 the advantage of storing it TEMP would be that one could easily view it on a write-protected drive or folder (e.g. a project archive on CD-ROM). This is to my understanding what @Christoph27 originally intended to do.

But I agree that changes should be kept simple if such use case rarely occur.
