### ISSUE TITLE
A bug report 

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/PK-Sim#1110]
![_ny fh ypch2_ln2 n9acy](https://user-images.githubusercontent.com/45459593/53246831-b3e7b780-36ec-11e9-91ed-5a750de8e35a.png)
I encountered a problem that I can't solve. It suddenly pops up and I failed to find the cause. Need help.

**Comment by msevestre** [comment]
@regulus92 It is a bug report so I moved it to the PK-Sim issue

**Comment by Yuri05** [comment]
@regulus92 Can you attach the problematic project and describe the steps to reproduce the problem?

**Comment by msevestre** [comment]
@regulus92 We will need the project in order to reproduce the issue. If this is a confidential project you can send it to me at michael@design2code.ca

**Comment by regulus92** [comment]
@Yuri05 @msevestre  
I uploaded the problematic file.  It was strange that I used PKSim just fine before this problem suddenly appeared when running a simulation. 

[EST.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2896362/EST.zip)

**Comment by Yuri05** [comment]
@regulus92 Please describe the steps to reproduce the problem

**Comment by regulus92** [comment]
@Yuri05 Select any of the simulations incorporated in this file> run simulation. I don't find any abnormality  in the building blocks, this is the problem.

**Comment by regulus92** [comment]
@Yuri05 By the way, the simulation results you see were successfully made using present building blocks before the problem occurred.

**Comment by msevestre** [comment]
@regulus92 ok thanks. I'll look at it very soon and get back to you, at least with a workaround hopefully

**Comment by Yuri05** [comment]
@regulus92 Could not reproduce so far. Can run all simukations.
Might be a problem with your user settings.
Can you try the following:
 * close PK-Sim
 * temporarily rename the file "_C:\Users\**XXXXX**\AppData\Roaming\Open Systems Pharmacology\PK-Sim\7.4\UserSettings.xml_" (where XXXXX is your windows user id)
 * start PK-Sim, open your project and try again

If it did not help - close PK-Sim and rename user settings back again

**Comment by regulus92** [comment]
Sorry, I don't understand. The file was found, and renamed to what?

**Comment by regulus92** [comment]
@Yuri05 @msevestre I restored Windows system, reinstalled the software, and redo this project from the very first. It works. But the problem still exsits when running the former one. Anyway, thank you very much.

**Comment by StephanSchaller** [comment]
> Sorry, I don't understand. The file was found, and renamed to what?

just rename it to sth. different than `UserSettings.xml` so PK-Sim cannot find it and creates new User Settings...

**Comment by msevestre** [comment]
@regulus92 Same here
I downloaded your file, opened every single simulation, run a simulation and no problem

Is there a way you can send us the UserSettings.xml that was mentioned previously. I do not expect this file to be the cause of your issue but who knows

**Comment by msevestre** [comment]
@regulus92 Or maybe your are doing something that we are not doing
Could you describe exactly what steps need to be performed to reproduce the issue?

**Comment by regulus92** [comment]
@msevestre I think I find the cause, it's the project name. I delete non-english letters such as ø, ñ in the names of simulations and it goes well.

**Comment by msevestre** [comment]
@regulus92 This project with the non english names works great on my machine. So this is not the problem

What system are you using? 

Could you paste the issue using the `copy to clipboard` function instead of a screenshot? It actually allows us to see the different internal functions called

**Comment by regulus92** [comment]
Using Microsoft Windows.  I reproduced the error.

Application:
PK-Sim® 7.4.0.127

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Core.Services.SimulationResultsCreator.valuesFrom(DataColumn dataColumn)
   at PKSim.Core.Services.SimulationResultsCreator.CreateResultsFrom(DataRepository dataRepository)
   at PKSim.Core.Services.SimulationResultsSynchronizer.Synchronize(IndividualSimulation simulation, DataRepository newResults)
   at PKSim.Core.Services.IndividualSimulationEngine.<>c__DisplayClass14_0.<runSimulation>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.IndividualSimulationEngine.<RunAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.SimulationRunner.<runSimulation>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.InteractiveSimulationRunner.<RunSimulation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext()
```

**Comment by regulus92** [comment]
@msevestre Using Microsoft Windows. I reproduced the error.

Application:
PK-Sim® 7.4.0.127

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Core.Services.SimulationResultsCreator.valuesFrom(DataColumn dataColumn)
   at PKSim.Core.Services.SimulationResultsCreator.CreateResultsFrom(DataRepository dataRepository)
   at PKSim.Core.Services.SimulationResultsSynchronizer.Synchronize(IndividualSimulation simulation, DataRepository newResults)
   at PKSim.Core.Services.IndividualSimulationEngine.<>c__DisplayClass14_0.<runSimulation>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.IndividualSimulationEngine.<RunAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.SimulationRunner.<runSimulation>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.InteractiveSimulationRunner.<RunSimulation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext()
```

**Comment by msevestre** [comment]
@regulus92 
I still cannot reproduce the error

Could you please
- Attach the UserSettings.xml file as requested
- Describe exactly what you are doing. I mean a step by step guide on how to reproduce. Maybe you are doing something that we are not and that's why we cannot reproduce

If we cannot reproduce the problem, we cannot fix it.

**Comment by regulus92** [comment]
I recorded a video. Hope this will help.
[20190301_091527.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2917581/20190301_091527.zip)

**Comment by msevestre** [comment]
@regulus92 Ah ah this is awesome. Thanks so much. 

So I am doing the same actions on my machine and it works. I am going to try with adding a property with one of those weird characters and let you know but I think this may have  something to do with the windows system... What language is your OS?

**Comment by regulus92** [comment]
@msevestre Chinese, but file paths for data and software are all in English. Thank you for your help.

**Comment by Yuri05** [comment]
closing due to inactivity.
@regulus92 please reopen or create a new issue if you still face the problem with newer projects
