### ISSUE TITLE
Right click on simulation: Run does not load the lazy loaded simulation => crash

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1116]
using #1110 
Load, Right click on any sim and run

Application:
PK-Sim® 7.4.0.127

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Core.Model.Simulation.get_OutputSelections()
   at PKSim.Core.Services.InteractiveSimulationRunner.outputSelectionRequired(Simulation simulation, Boolean selectOutput)
   at PKSim.Core.Services.InteractiveSimulationRunner.<RunSimulation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext()
```

**Comment by UlrichSi** [comment]
Looks like this is a hardly used feature. Interestingly, the error will not occur if you do this with a simulation that is open for edit.

**Comment by msevestre** [comment]
Yes because if it's open, it has been loaded. So all good

**Comment by UlrichSi** [comment]
I guess the more common workflow is to have the simulation open, since you want to check the result.

I also tested a MoBi project for this bug - things appear to work fine there.
