### ISSUE TITLE
7.5 PDF Export does not work anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1135]
In 7.5 trying to export PDF report for any BB, Simulation or project leads to the error message below.

```
Application:
PK-Sim® 7.5.0.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.UI.Views.ReportingView.updateTemplateDescription(ReportTemplate template) in C:\projects\ospsuite-core\src\OSPSuite.UI\Views\ReportingView.cs:line 103
   at OSPSuite.UI.Views.ReportingView.BindTo(ReportConfiguration reportConfiguration) in C:\projects\ospsuite-core\src\OSPSuite.UI\Views\ReportingView.cs:line 39
   at OSPSuite.Presentation.Presenters.AbstractReportingPresenter.CreateReport(Object objectToReport, Boolean isDraft) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\AbstractReportingPresenter.cs:line 63
   at PKSim.Presentation.UICommands.ExportToPDFCommand`1.PerformExecute() in C:\VSS\PK-Sim\branches\7.5\src\PKSim.Presentation\UICommands\ExportToPDFCommand.cs:line 33
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\ObjectUICommands.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\UICommandExtensions.cs:line 26
```

**Comment by msevestre** [comment]
Cannot reproduce. Probably you forgot to run postclean.bat on PKsim that copies the template

**Comment by Yuri05** [comment]
probably. works now. closing
