### ISSUE TITLE
error message while saving a Pksim file with a new name (7.3.0.42)

### ISSUE THREAD

**Issue by amitvtaneja** [Open-Systems-Pharmacology/PK-Sim#1243]
Dear all

I have saved an existing project with a new name, but if I try to open it I get the following error message, probably a bug. Any help would be highly appreciated.

Thanks

Amit Taneja

Application:
PK-Sim® 7.3.0.42

The given path's format is not supported.

Stack trace:
```
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at OSPSuite.Utility.FileHelper.<>c.<.cctor>b__19_1(String fileFullPath)
   at OSPSuite.Infrastructure.Journal.JournalLoader.retrieveJournalAbsolutePath(String journalPath, String projectFullPath)
   at OSPSuite.Infrastructure.Journal.JournalLoader.Load(String journalPath, String projectFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
What's the full path of your file?(no just the file name but the path including folder hieararchy as it appears on the windows explorer tool bar)

Also please report bug in the PKSim or MoBI repo. The forum is for questions. I moved the question on your behalf

**Comment by msevestre** [comment]
No feedback in over two months. Closing
