### ISSUE TITLE
Problem with Inputs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1260]
[input.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/3211315/input.zip)

`.\QualificationRunner -i master_quali_plan.json -o C:\re_input -p C:\PK-Sim8 -f`

Error:
[logfile.txt](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/3211325/logfile.txt)

```
fail: Itraconazole[0]
      An item with the key 'PKSim.Core.Model.Formulation' has already been added
info: Itraconazole[0]
      -----------------------------------------------------
info: Itraconazole[0]
      An item with the same key has already been added.
info: Itraconazole[0]

info: Itraconazole[0]
      Stack trace:
info: Itraconazole[0]
      at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
info: Itraconazole[0]
         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
info: Itraconazole[0]
         at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Collections\Cache.cs:line 133
info: Itraconazole[0]
       --- End of inner exception stack trace ---
info: Itraconazole[0]
         at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Collections\Cache.cs:line 143
info: Itraconazole[0]
         at OSPSuite.Utility.BuilderRepository`1.BuilderFor(Type type) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\BuilderRepository.cs:line 50
info: Itraconazole[0]
         at OSPSuite.Utility.BuilderRepository`1.BuilderFor(Object objectToBuild) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\BuilderRepository.cs:line 73
info: Itraconazole[0]
         at PKSim.Infrastructure.Services.MarkdownReporterTask.ExportToMarkdownString(Object objectToExport) in C:\SW-Dev\PK-Sim\branches\7.5\src\PKSim.Infrastructure\Services\MarkdownReporterTask.cs:line 27
info: Itraconazole[0]
         at PKSim.Infrastructure.Services.MarkdownReporterTask.<>c__DisplayClass3_0.<ExportToMarkdown>b__0() in C:\SW-Dev\PK-Sim\branches\7.5\src\PKSim.Infrastructure\Services\MarkdownReporterTask.cs:line 22
info: Itraconazole[0]
         at System.Threading.Tasks.Task.Execute()
info: Itraconazole[0]
      --- End of stack trace from previous location where exception was thrown ---
info: Itraconazole[0]
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
info: Itraconazole[0]
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
info: Itraconazole[0]
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
info: Itraconazole[0]
         at PKSim.CLI.Core.Services.QualificationRunner.<exportInput>d__18.MoveNext() in C:\SW-Dev\PK-Sim\branches\7.5\src\PKSim.CLI.Core\Services\QualificationRunner.cs:line 225
info: Itraconazole[0]
      --- End of stack trace from previous location where exception was thrown ---
info: Itraconazole[0]
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
info: Itraconazole[0]
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
info: Itraconazole[0]
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
info: Itraconazole[0]
         at PKSim.CLI.Core.Services.QualificationRunner.<RunBatchAsync>d__10.MoveNext() in C:\SW-Dev\PK-Sim\branches\7.5\src\PKSim.CLI.Core\Services\QualificationRunner.cs:line 112
info: Itraconazole[0]
       --- End of inner exception stack trace ---
info: Itraconazole[0]
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
info: Itraconazole[0]
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
info: Itraconazole[0]
         at System.Threading.Tasks.Task.Wait()
info: Itraconazole[0]
         at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command) in C:\SW-Dev\PK-Sim\branches\7.5\src\PKSim.CLI\Program.cs:line 51
info: Itraconazole[0]
      Qualification run finished
fail: Qualification Runner[0]
      Project configuration for 'Itraconazole' is invalid. Please check log file at 'C:\2del\QualiExample01\re_input\temp\Itraconazole\log.txt' for details.
fail: Qualification Runner[0]
      Qualification Workflow failed
```

**Comment by msevestre** [comment]
I think it's because the export happens in // and somehow the implementation is not thread safe!

**Comment by msevestre** [comment]
This needs to be fixed in OSPSuite.Utility in fact
