### ISSUE TITLE
PK-Sim.CLI Crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1286]
OSP Version 8.0, project created with 8.0
[ExampleProject.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3349822/ExampleProject.zip)

Call: `PKSim.CLI export -p C:\Temp\ExampleProject.pksim5 -o C:\Temp\Out -x`

Error: 
```
Unhandled Exception: OSPSuite.Utility.Container.InterfaceResolutionException: Failed to resolve an implementation of IBatchRunner`1 ---> Castle.MicroKernel.ComponentNotFoundException: No component for supporting the service PKSim.CLI.Core.Services.IBatchRunner`1[[PKSim.CLI.Core.RunOptions.ExportRunOptions, PKSim.CLI.Core, Version=8.0.22.0, Culture=neutral, PublicKeyToken=null]] was found
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, IDictionary arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at OSPSuite.Utility.Container.IoC.Resolve[TImplementationOfInterface]()
   --- End of inner exception stack trace ---
   at OSPSuite.Utility.Container.IoC.Resolve[TImplementationOfInterface]()
   at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PKSim.CLI.Program.Main(String[] args)
```

**Comment by msevestre** [comment]
Of course it's always what's not tested automatically that fails...

Obviously

**Comment by Yuri05** [comment]
still failing, another exception now (tried id with dev and with portable version 9.0.98):

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Console, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
   at PKSim.CLI.Program.initializeLogger(CLICommand runCommand)
   at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PKSim.CLI.Program.Main(String[] args)
```

**Comment by msevestre** [comment]
ok I can reproduce
