### ISSUE TITLE
Ongoing Problem Loading Old PK-Sim Files

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/PK-Sim#1307]
Hi all,

After 1-2 updates I am frequently unable to open old Pk-Sim files. This is an example of the error. I'm wondering if anyone can provide insight. In the meantime I will be trying to reinstall an older release.

Application:
PK-Sim® 8.0.22

disk I/O error
disk I/O error

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Looking at the stack trace, it does not look like a PKSim error. It seems that the app cannot access the file (Disk I/O error).
Is the project file located on an external drive? Is your internet/network connection unstable? 
Can you try to copy the project to your local hard drive and see if you can open it from there?

Our test suites open projects from version 5.x and above (over 10 releases). I am extremely confident, that this error is not due to the software and that downgrading won't solve the problem. If it does, however, can you share the file with me so that we can give it a look?

**Comment by prvmalik** [comment]
Thank you for the helpful insight Michael. This narrows it down to a problem with the Egnyte cloud storage drive where the project files are located. Copy and pasting the project file from Egnyte to an HDD or SSD doesn't resolve the error, but it does prompt a slightly different error:

Application:
PK-Sim® 8.0.22

could not initialize a collection: [PKSim.Infrastructure.Serialization.ORM.MetaData.ProjectMetaData.ParameterIdentifications#1][SQL: SELECT parameteri0_.ProjectId as projectid6_20_2_, parameteri0_.Id as id1_20_2_, parameteri0_.Id as id1_20_1_, parameteri0_.Name as name2_20_1_, parameteri0_.Description as description3_20_1_, parameteri0_.ContentId as contentid4_20_1_, parameteri0_.PropertiesId as propertiesid5_20_1_, metadataco1_.Id as id1_18_0_, metadataco1_.Data as data2_18_0_ FROM PARAMETER_IDENTIFICATIONS parameteri0_ left outer join CONTENTS metadataco1_ on parameteri0_.PropertiesId=metadataco1_.Id WHERE parameteri0_.ProjectId=?]
-----------------------------------------------------
database disk image is malformed
database disk image is malformed

Stack trace:
```
at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.LoadCollection(ISessionImplementor session, Object id, IType type)
 --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.LoadCollection(ISessionImplementor session, Object id, IType type)
   at NHibernate.Event.Default.DefaultInitializeCollectionEventListener.OnInitializeCollection(InitializeCollectionEvent event)
   at NHibernate.Impl.SessionImpl.InitializeCollection(IPersistentCollection collection, Boolean writing)
   at NHibernate.Collection.AbstractPersistentCollection.ForceInitialization()
   at NHibernate.Engine.StatefulPersistenceContext.InitializeNonLazyCollections()
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFromDatabase(ISession session)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

I've lost 4 or more projects this way and it tends to happen with larger files, rather than smaller ones.

But get back to enjoying your vacation! It is not an urgent issue. Thanks again for the insight.

**Comment by msevestre** [comment]
I wonder if this is due to egnyte. You should be able to recover an older version of a file with egnyte.
I think however that there is a bug in pksim as we had this very error reported by someone not so long ago. Maybe you could send me the file per email and I could try to see if I can recover it (next week;;))

**Comment by prvmalik** [comment]
Lost another one - this one built in 8.0 and saved on an SSD.

Application:
PK-Sim® 8.0.22

Value cannot be null.
Parameter name: key

Stack trace:
```
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(ObservedDataMetaData observedDataMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<>c__DisplayClass5_0.<MapFrom>b__0(ObservedDataMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@prvmalik This is something different. I believe this has to do with some steps that you are doing that are creating this bug.
This is clearly a bug in PKSim and I'd like to understand what's happening
* Can you please send me the file (via email if it can't be public please!)
* Describe the steps that were taken prior to file crashing

I'll investigate and see what's the reason for the bug and maybe we can figure out what's going on. This is something very specific to you and your workflow as it does not seem to happen with anyone else. BUT THIS IS DEFINITELY A BUG
