### ISSUE TITLE
Cancelling observed data snapshot import throws error

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1311]
![Untitled](https://user-images.githubusercontent.com/26541603/63856564-39049f80-c9a2-11e9-81bd-6b9b95475e02.jpg)

Application:
PK-Sim® 8.0.22

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Services.ObservedDataTask.LoadFromSnapshot()
   at PKSim.Presentation.UICommands.LoadObservedDataFromSnapshotUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
not reproducible - seems to be fixed
