### ISSUE TITLE
SQL logic error no such table: SUMMARY_CHART

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/PK-Sim#1342]
Hello All,
Folowing is the issue iam facing

SQL logic error
no such table: SUMMARY_CHART

at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by msevestre** [comment]
Are you trying to open a file that is not a PKSim file?

Please check. This error usually happens when the file is not one of our file

**Comment by harishkaushikbugworks** [comment]
It is an PKSIM file only may be versions are different

Regards
Harish

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by msevestre** [comment]
It also happens when you open a file that is being downloaded but the download is not finished

Can you zip the file and upload it here so that we can give it a look?

**Comment by msevestre** [comment]
Assuming you got this sorted out. Closing. Please reopen with the file attached if you need more help
