### ISSUE TITLE
Error importing from Snapshot: Key 'µg*h/ml' could not be found

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1343]
When loading from [this snapshot](https://github.com/Open-Systems-Pharmacology/Oxycodone-Model/blob/master/Oxycodone.json) (PK-Sim 8 Build 22)

```
Information: Loading Project from snapshot file 'D:\Oxycodone.json'
Warning: Snapshot parameter 'Neighborhoods|Kidney_pls_Kidney_ur|OCD|Renal Clearances-fitted|Specific clearance' was not found.
Error: Key 'µg*h/ml' could not be found

Stack trace:
at OSPSuite.Utility.Collections.Cache`2.<>c.<.ctor>b__11_0(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.get_Item(TKey key)
   at OSPSuite.Core.Domain.UnitSystem.MergedDimensionFor`1.Unit(String name)
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapNumericFieldToModel(PopulationAnalysisField snapshot, INumericValueField field)
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapQuantityFieldToModel(PopulationAnalysisField snapshot, IQuantityField field)
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapPKParameterFieldToModel(PopulationAnalysisField snapshot, PopulationAnalysisPKParameterField field)
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapIf[T](PopulationAnalysisField snapshot, IPopulationAnalysisField populationAnalysisField, Action`2 mapAction)
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.<MapToModel>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  ...
```

**Comment by msevestre** [comment]
This is the full debug log
```
Information: Loading Project from snapshot file 'C:\tests\9.0\1343\Oxycodone.json'
Debug: Loading project '' from snapshot...
Debug: Loading simulation 'po 15mg'...
Debug: Loading simulation '0.1 mg/kg iv'...
Debug: Loading simulation 'Olkkola 1994'...
Debug: Loading simulation 'Kokki 2004 iv'...
Debug: Loading simulation 'iv 0.07mg/kg population'...
Debug: Loading simulation 'po 10mg population'...
Debug: Loading simulation 'po 15mg population'...
Debug: Loading simulation 'po 20mg CR population'...
Debug: Loading simulation 'po 40mg population'...
Debug: Loading simulation 'Kokki 2004 po'...
Warning: Snapshot parameter 'Neighborhoods|Kidney_pls_Kidney_ur|OCD|Renal Clearances-fitted|Specific clearance' was not found.
Debug: Loading simulation 'Adult'...
Debug: Loading simulation 'Newborn'...
Debug: Loading simulation 'Preschool'...
Debug: Loading simulation 'Adolescent'...
Debug: Loading simulation 'School Age'...
Debug: Loading simulation 'Toddler'...
Debug: Loading simulation 'Multidose CR'...
Debug: Loading simulation 'po 20mg population'...
Debug: Loading simulation 'Tahtawy 2006 iv'...
Debug: Loading simulation 'Tahtawy 2006 po'...
Debug: Loading simulation 'Adult po'...
Debug: Loading simulation 'Preschool po'...
Debug: Loading simulation 'Toddler po'...
Debug: Loading simulation 'School age po'...
Debug: Loading simulation 'Adolescent po'...
Debug: Loading simulation 'toddler calculation'...
Debug: Loading simulation 'preschool calculation'...
Debug: Loading simulation 'school age calculation'...
Debug: Loading simulation 'adolescent calculation'...
Debug: Loading simulation 'adult calculation'...
Error: Key 'µg*h/ml' could not be found

Stack trace:
at OSPSuite.Utility.Collections.Cache`2.<>c.<.ctor>b__11_0(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.get_Item(TKey key)
   at OSPSuite.Core.Domain.UnitSystem.MergedDimensionFor`1.Unit(String name)
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapNumericFieldToModel(PopulationAnalysisField snapshot, INumericValueField field) in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisFieldMapper.cs:line 125
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapQuantityFieldToModel(PopulationAnalysisField snapshot, IQuantityField field) in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisFieldMapper.cs:line 108
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapPKParameterFieldToModel(PopulationAnalysisField snapshot, PopulationAnalysisPKParameterField field) in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisFieldMapper.cs:line 71
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.mapIf[T](PopulationAnalysisField snapshot, IPopulationAnalysisField populationAnalysisField, Action`2 mapAction) in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisFieldMapper.cs:line 135
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisFieldMapper.<MapToModel>d__4.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisFieldMapper.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBaseExtensions.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisMapper.<MapToModel>d__10.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisMapper.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.PopulationAnalysisChartMapper.<MapToModel>d__6.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\PopulationAnalysisChartMapper.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBaseExtensions.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SimulationComparisonMapper.<updatePopulationComparisonModel>d__9.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SimulationComparisonMapper.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Snapshots.Mappers.SimulationComparisonMapper.<createSimulationComparisonFrom>d__8.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SimulationComparisonMapper.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SimulationComparisonMapper.<MapToModel>d__7.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SimulationComparisonMapper.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBaseExtensions.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<MapToModel>d__11.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\ProjectMapper.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBase`2.<MapToModel>d__1.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBase.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<loadModelsFromSnapshots>d__16`1.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Services\SnapshotTask.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadModelsFromSnapshotFile>d__15`1.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Services\SnapshotTask.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshotFile>d__17.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Services\SnapshotTask.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadProjectFromSnapshotPresenter.<LoadModelAsync>d__4.MoveNext() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Snapshots\LoadProjectFromSnapshotPresenter.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<PerformLoad>d__19.MoveNext() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Snapshots\LoadFromSnapshotPresenter.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<Start>d__14.MoveNext() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Snapshots\LoadFromSnapshotPresenter.cs:line 105
```

**Comment by msevestre** [comment]
Smallest reproducible version
[Oxycodone.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3856074/Oxycodone.zip)

**Comment by msevestre** [comment]
@Yuri05 I could reproduce for the first warning by adding a parameter as User Defined Variability and THEN removing the parameter for the simulation
We could add  a step after configure to remove all parameters that do not exist anymore

**Comment by msevestre** [comment]
Adding the step for configuration is quite complicated because of the undo
