### ISSUE TITLE
Deletion of MoBi-imported simulation from PI possible

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1389]
Following the subsequently described workflow, PK-Sim throws the error message below. I am not sure how to interpret it and where the error is exactly located. What I did is:

- Build simulations in PK-Sim
- Export a simulation to MoBi, add a new molecule/reaction and re-import the simulation to PK-Sim; the project file can be found [here](https://github.com/AndreDlm/Erythromycin-Model)
- Run a PI that includes the simulation imported from MoBi
- Delete the simulation imported from MoBi (this is possible without an error!)
- Export the project to Snapshot; the JSON file can be found [here](https://github.com/AndreDlm/Erythromycin-Model)
- Re-import the Snapshot file throws the following error:

____________

Information: Loading Project from snapshot file 'C:\Projects\GitHub\Erythromycin.json'
Error: Object reference not set to an instance of an object.

Stack trace:
at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.<>c.<ensureThatDimensionsAreEqual>b__8_0(IParameter x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.ensureThatDimensionsAreEqual(IEnumerable`1 parameters)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.CreateFor(IEnumerable`1 parameterSelections, ParameterIdentification parameterIdentification)
   at PKSim.Core.Snapshots.Mappers.IdentificationParameterMapper.<MapToModel>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ParameterIdentificationMapper.<MapToModel>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<MapToModel>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBase`2.<MapToModel>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<loadModelsFromSnapshots>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadModelsFromSnapshotFile>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshotFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadProjectFromSnapshotPresenter.<LoadModelAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<PerformLoad>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<Start>d__14.MoveNext()

**Comment by Yuri05** [comment]
I think it has nothing to do with the MoBi simulations (in your project they are not part of the PI anyway). It's something in the PI itself which prevents importing it from the snapshot

**Comment by msevestre** [comment]
There is no way that the simulation can be recreated from snapshot. An error/warning should be shown when exporting to snapshot that the project won't be valid anymore

**Comment by Yuri05** [comment]
As long as MoBi simulations are part of the project, Export to snapshot stops with an error (as expected).
![grafik](https://user-images.githubusercontent.com/25061876/72890885-3f116900-3d13-11ea-93fc-4e22a0c99c90.png)
After 2 MoBi simulations are removed from the project, it can be exported to snapshot, but reimport crashes during recreation of PI.

**Comment by msevestre** [comment]
Oh I see. Is it possible to delete a normal simulation from a project when used in a PI? (E.g would we have the same behavior when taking Mobi out if the picture?)

If yes the snapshot reimport needs to be more resilient
