### ISSUE TITLE
v9: error opening pop simulation in 7.3 project

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1423]
[Theophylline_PopDummy.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4186937/Theophylline_PopDummy.zip)
Trying to open the (only) simulation produces the error below in v9. Project was created with 7.3, then changed and saved with 7.4.

Works in v8.

```
Application:
PK-Sim® 9.0.0

Object reference not set to an instance of an object.

Stack trace:

at PKSim.Core.Services.PopulationAnalysisFlatTableCreator.Create(IPopulationDataCollector populationDataCollector, IReadOnlyCollection`1 populationAnalysisFields) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\PopulationAnalysisFlatTableCreator.cs:line 60
   at PKSim.Core.Services.PopulationAnalysisFlatTableCreator.Create(IPopulationDataCollector populationDataCollector, PopulationAnalysis populationAnalysis) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\PopulationAnalysisFlatTableCreator.cs:line 218
   at PKSim.Core.Services.PivotResultCreator.Create(PopulationPivotAnalysis pivotAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\PivotResultCreator.cs:line 34
   at PKSim.Core.Services.ChartDataCreator`2.CreateResult[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\ChartsDataCreator.cs:line 90
   at PKSim.Core.Services.TimeProfileChartDataCreator.CreateResult[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\TimeProfileChartsDataCreator.cs:line 225
   at PKSim.Core.Services.ChartDataCreator`2.CreateFor[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\ChartsDataCreator.cs:line 85
   at PKSim.Core.Services.ChartDataCreator`2.CreateFor[TPopulationAnalysis](PopulationAnalysisChart`1 populationAnalysisChart, Aggregate aggregate) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Core\Services\ChartsDataCreator.cs:line 80
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.CreateChartData() in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Charts\EditTimeProfileAnalysisChartPresenter.cs:line 80
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.RefreshData() in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Charts\EditPopulationAnalysisChartPresenter.cs:line 84
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.RefreshData() in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Charts\EditTimeProfileAnalysisChartPresenter.cs:line 73
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IPopulationDataCollector populationDataCollector) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Charts\EditPopulationAnalysisChartPresenter.cs:line 77
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IAnalysable analysable) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Charts\EditPopulationAnalysisChartPresenter.cs:line 71
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Charts\EditPopulationAnalysisChartPresenter.cs:line 94
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 44
   at PKSim.Presentation.Services.BuildingBlockTask.Edit(IPKSimBuildingBlock buildingBlockToEdit) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Services\BuildingBlockTask.cs:line 72
   at PKSim.Presentation.Presenters.Main.ExplorerPresenter`2.EditBuildingBlock(IPKSimBuildingBlock buildingBlock) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Main\ExplorerPresenter.cs:line 105
   at PKSim.Presentation.Presenters.Main.SimulationExplorerPresenter.NodeDoubleClicked(ITreeNode node) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Presenters\Main\SimulationExplorerPresenter.cs:line 276
   at OSPSuite.UI.Views.BaseExplorerView.<>c__DisplayClass16_0.<nodeDoubleClick>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Fixes in #1426
