### ISSUE TITLE
Changing error type and unit of observed data to dimensionless throws unhandled exception error

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1459]
Using the attached hypothetical data, I ran into an unhandled exception error following these steps:
- Load data in PK-Sim
- Change error type from `Geometric Standard Deviation` to `Arithmetic Standard Deviation` (this sets the unit of the fraction columns to molar concentration)
- Setting the unit of the fraction column to `Dimensionless` throws the error below

![Picture1](https://user-images.githubusercontent.com/26541603/78665500-340fb300-78d6-11ea-8192-c459da1204bb.png)

[Test_UrinaryRecovery.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4443913/Test_UrinaryRecovery.xlsx)
___________________

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
OSPSuite.Core.Domain.InvalidArgumentException: Wrong Dimension for ArithmeticStdDev: Concentration (molar) instead of Dimensionless
   at OSPSuite.Core.Domain.Data.DataColumn.validateDimensionIs(AuxiliaryType auxiliaryType, IDimension dimension, IDimension targetDimension)
   at OSPSuite.Core.Domain.Data.DataColumn.AddRelatedColumn(DataColumn relatedColumn)
   at OSPSuite.Core.Importer.Mappers.ImportDataTableToDataRepositoryMapper.associateColumns(IList`1 colInfos, DataRepository dataRepository)
   at OSPSuite.Core.Importer.Mappers.ImportDataTableToDataRepositoryMapper.ConvertImportDataTable(ImportDataTable importDataTable, IEnumerable`1 columnInfos, Boolean& errorNaN)
   at OSPSuite.UI.Views.Importer.ImportDataTableControl.rePlot()
   at OSPSuite.UI.Views.Importer.ImportDataTableControl.<buildControl>b__15_0(Object sender, EventArgs args)
   at OSPSuite.UI.Views.Importer.ImportDataTableControl.UnitChangedHandler.Invoke(Object sender, EventArgs e)
   at OSPSuite.UI.Views.Importer.ImportDataTableControl.onSetUnitClick(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportDataTableGridPresenter.RaiseSetUnitEvent(Object sender, EventArgs eventArgs)
   at OSPSuite.UI.Views.Importer.ImportDataTableGridView.onSetUnitClick(Object sender, EventArgs e)
   at DevExpress.Utils.Menu.DXMenuItem.OnClick()
   at DevExpress.XtraBars.Utils.DXPopupXtraMenu.OnBarMenuClick(Object sender, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3610.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PKSim
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/PKSim.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.Utils.v18.2.DLL
----------------------------------------
DevExpress.Data.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.Data.v18.2.DLL
----------------------------------------
OSPSuite.Utility
    Assembly Version: 3.0.1.7
    Win32 Version: 3.0.1.7
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Utility.DLL
----------------------------------------
PKSim.UI
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/PKSim.UI.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.18315
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
OSPSuite.Core
    Assembly Version: 8.0.4.0
    Win32 Version: 8.0.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Core.DLL
----------------------------------------
PKSim.Infrastructure
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/PKSim.Infrastructure.DLL
----------------------------------------
OSPSuite.Presentation
    Assembly Version: 8.0.4.0
    Win32 Version: 8.0.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Presentation.DLL
----------------------------------------
PKSim.Presentation
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/PKSim.Presentation.DLL
----------------------------------------
PKSim.Assets
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/PKSim.Assets.DLL
----------------------------------------
OSPSuite.UI
    Assembly Version: 8.0.4.0
    Win32 Version: 8.0.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.UI.DLL
----------------------------------------
OSPSuite.Assets
    Assembly Version: 8.0.4.0
    Win32 Version: 8.0.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Assets.DLL
----------------------------------------
Northwoods.Go
    Assembly Version: 5.2.0.45
    Win32 Version: 5.2.0.45
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Northwoods.Go.DLL
----------------------------------------
OSPSuite.Infrastructure
    Assembly Version: 8.0.4.0
    Win32 Version: 8.0.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Infrastructure.DLL
----------------------------------------
Castle.Windsor
    Assembly Version: 4.0.0.0
    Win32 Version: 4.1.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.3.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Castle.Core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PKSim.Core
    Assembly Version: 8.0.22.0
    Win32 Version: 8.0.22
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/PKSim.Core.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3610.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.18315
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.18315
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Microsoft.Extensions.Options.DLL
----------------------------------------
DevExpress.RichEdit.v18.2.Core
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.RichEdit.v18.2.Core.DLL
----------------------------------------
DevExpress.Office.v18.2.Core
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.Office.v18.2.Core.DLL
----------------------------------------
DevExpress.XtraBars.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraBars.v18.2.DLL
----------------------------------------
DevExpress.XtraEditors.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraEditors.v18.2.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
DevExpress.XtraRichEdit.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraRichEdit.v18.2.DLL
----------------------------------------
DevExpress.XtraGrid.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraGrid.v18.2.DLL
----------------------------------------
DevExpress.XtraTreeList.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraTreeList.v18.2.DLL
----------------------------------------
Northwoods.Go.Layout
    Assembly Version: 5.2.0.45
    Win32 Version: 5.2.0.45
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Northwoods.Go.Layout.DLL
----------------------------------------
DevExpress.XtraPivotGrid.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraPivotGrid.v18.2.DLL
----------------------------------------
DevExpress.PivotGrid.v18.2.Core
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.PivotGrid.v18.2.Core.DLL
----------------------------------------
DevExpress.XtraCharts.v18.2.UI
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraCharts.v18.2.UI.DLL
----------------------------------------
DevExpress.XtraCharts.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraCharts.v18.2.DLL
----------------------------------------
DevExpress.Charts.v18.2.Core
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.Charts.v18.2.Core.DLL
----------------------------------------
DevExpress.Printing.v18.2.Core
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.Printing.v18.2.Core.DLL
----------------------------------------
DevExpress.XtraLayout.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraLayout.v18.2.DLL
----------------------------------------
OSPSuite.DataBinding
    Assembly Version: 2.3.0.3
    Win32 Version: 2.3.0.3
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.DataBinding.DLL
----------------------------------------
OSPSuite.Serializer
    Assembly Version: 2.0.1.4
    Win32 Version: 2.0.1.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Serializer.DLL
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.18315
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Microsoft.Extensions.Logging.Debug.DLL
----------------------------------------
OSPSuite.SimModel
    Assembly Version: 0.0.0.0
    Win32 Version: 3.0.1.27
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.SimModel.DLL
----------------------------------------
OSPSuite.Engine
    Assembly Version: 8.0.4.0
    Win32 Version: 8.0.4
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.Engine.DLL
----------------------------------------
OSPSuite.FuncParser
    Assembly Version: 0.0.0.0
    Win32 Version: 3.0.1.14
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.FuncParser.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.2.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/System.ValueTuple.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
OSPSuite.TeXReporting
    Assembly Version: 2.1.1.9
    Win32 Version: 2.1.1.9
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.TeXReporting.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.3.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Castle.Core.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
NHibernate
    Assembly Version: 5.2.0.0
    Win32 Version: 5.2.5.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/NHibernate.DLL
----------------------------------------
FluentNHibernate
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/FluentNHibernate.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Newtonsoft.Json.DLL
----------------------------------------
MarkdownLog
    Assembly Version: 0.10.1.0
    Win32 Version: 0.10.1.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/MarkdownLog.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.109.0
    Win32 Version: 1.0.109.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
OSPSuite.DataBinding.DevExpress
    Assembly Version: 3.0.0.3
    Win32 Version: 3.0.0.3
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/OSPSuite.DataBinding.DevExpress.DLL
----------------------------------------
DevExpress.BonusSkins.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.BonusSkins.v18.2.DLL
----------------------------------------
Newtonsoft.Json.Schema
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.11.23222
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/Newtonsoft.Json.Schema.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3535.0 built by: NET472REL1LAST
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
DevExpress.Images.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.Images.v18.2.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
DevExpress.XtraPrinting.v18.2
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraPrinting.v18.2.DLL
----------------------------------------
DevExpress.XtraCharts.v18.2.Wizard
    Assembly Version: 18.2.7.0
    Win32 Version: 18.2.7.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/DevExpress.XtraCharts.v18.2.Wizard.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.1.0.145
    Win32 Version: 1.1.0.145
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/ICSharpCode.SharpZipLib.DLL
----------------------------------------
SX
    Assembly Version: 2.6.4.1
    Win32 Version: 2.6.4.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/PK-Sim%208.0/SX.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Yuri05** [comment]
obsolete after data import redesign
