### ISSUE TITLE
check test that is randomly failing on appveyor

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#146]
```
PKSim.IntegrationTests.When_deleting_the_reference_to_another_template.should_have_deleted_the_reference
  Expected: False
  But was:  True
at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeEqualTo[T](T actual, T expected, String message) in C:\projects\ospsuite-bddhelper\src\OSPSuite.BDDHelper\Extensions\BDDExtensions.cs:line 240
at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeEqualTo[T](T actual, T expected) in C:\projects\ospsuite-bddhelper\src\OSPSuite.BDDHelper\Extensions\BDDExtensions.cs:line 184
at OSPSuite.BDDHelper.Extensions.BDDExtensions.ShouldBeFalse(Boolean item) in C:\projects\ospsuite-bddhelper\src\OSPSuite.BDDHelper\Extensions\BDDExtensions.cs:line 160
at PKSim.IntegrationTests.When_deleting_the_reference_to_another_template.should_have_deleted_the_reference() in C:\projects\pk-sim\tests\PKSim.Tests\IntegrationTests\TemplateTaskQuerySpecs.cs:line 190
```
see
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/build/7.1.0.43

**Comment by msevestre** [comment]
@rwmcintosh Any idea what might be wrong here?

**Comment by msevestre** [comment]
If we cannot find why this fails sometimes, we need to either make sure it cannot fail for stupid reasons or disable that test
