### ISSUE TITLE
Crash when loading a PI recreated from snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1469]
Load project from snapshot and open the PI "**global Parameter Identification**".
(was the same in PK-Sim 8)
[Alfentanil.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4535209/Alfentanil.zip)

```
Application:
PK-Sim® 9.0.0

Object reference not set to an instance of an object.

Stack trace:
at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.CalculateConfidenceIntervalFor(ParameterIdentification parameterIdentification, ParameterIdentificationRunResult runResult)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationCovarianceAnalysisPresenter.UpdateAnalysis()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 44
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
ok so this is because we do not return the PI when loaded from snapshot. However here we have confidence interval plots that needs to take this use case into account . Moving to core
