### ISSUE TITLE
 I can`t save my graph on excel - error >  InvalidSheetName

### ISSUE THREAD

**Issue by fredsevmartins** [Open-Systems-Pharmacology/PK-Sim#1494]
Hi 
I cant save my graphs on excel.
The error message is attached  

Application:
PK-Sim® 8.0.22

InvalidSheetName

Stack trace:
```
at l7.d(String A_0)
   at l7.b(String A_0)
   at l7.e(String A_0)
   at re.a(Int32 A_0, String A_1)
   at OSPSuite.Infrastructure.Services.ExportToExcelTask.exportDataTableToWorkBook(WorkBook workBook, DataTable dataTable, Int32 sheetIndex)
   at OSPSuite.Infrastructure.Services.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, Action`2 workbookConfiguration)
   at OSPSuite.Infrastructure.Services.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, Action`1 workbookConfiguration)
   at OSPSuite.Infrastructure.Services.DataRepositoryTask.ExportToExcel(IEnumerable`1 dataTables, String fileName, Boolean launchExcel)
   at OSPSuite.Infrastructure.Services.DataRepositoryTask.ExportToExcel(IEnumerable`1 dataColumns, String fileName, Boolean launchExcel, DataColumnExportOptions exportOptions)
   at OSPSuite.Core.Services.CurveChartExportTask.ExportToExcel(CurveChart chart)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.ExportToExcel()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
@fredsevmartins Does it happen with every graph or only with this one?
Did you give a name to the graph ? If yes, what is it?

**Comment by fredsevmartins** [comment]
@msevestre any graph, and I didn't give any name.

**Comment by fredsevmartins** [comment]
@msevestre I found the problem. My observed data has [ ]  and -. I removed those  and it is back to normal.
Many thanks

**Comment by msevestre** [comment]
Going to reopen this as this is a bug.
Can you please upload an observed data file with the same shape as what you are describing so that we can reproduce the bug
even better... a small project to reproduce the issue. At least we can make sure we give a better error message

**Comment by fredsevmartins** [comment]
@msevestre  I  can't share this file because it is confidential. 
But was named like  [FR 2763].  FR. XXXX 101 1001 Human Peripheral Venous Blood Plasma 5 PO SD
and it worked when I replaced the  [  ] and  .
FR 2763  FR XXXX 101 1001 Human Peripheral Venous Blood Plasma 5 PO SD

**Comment by Yuri05** [comment]
should be fixed in V10. Closing
