### ISSUE TITLE
Deleting referenced compound template corrupts the template database

### ISSUE THREAD

**Issue by jgg1822** [Open-Systems-Pharmacology/PK-Sim#1498]
When trying to import a compound file from a previously saved template, I keep getting the error below. This happens even after restarting PK-Sim and trying to use a different project file. Thanks!

Application:
PK-Sim® 8.0.22

There is no row at position 0.

Stack trace:
```
at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at PKSim.Infrastructure.ORM.DAS.DASDataRowCollection.ItemByIndex(Int32 Index)
   at PKSim.Infrastructure.Extensions.DASExtensions.ExecuteQueryForSingleRow(DAS connection, String query)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.loadTemplateBy(TemplateDatabaseType templateDatabaseType, String templateName, String templateType, DAS connection)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.addReferencesToTemplate(Template template, DAS connection, List`1 loadedReferenceNames)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateDatabaseType templateDatabaseType, TemplateType templateType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateType templateType)
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplate[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.LoadFromTemplate[TBuildingBlock](PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate()
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadSingleFromTemplate()
   at PKSim.Presentation.UICommands.LoadBuildingBlockFromTemplateUICommand`2.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
@jgg1822 The templates are not saved in the pksim project
Rather they are saved in the path specified in your user settings  under General
see https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-options

Can you please share with us your database so that we can investigate (zip the db)

Also can you describe what you did? Did you save a new building block as template? If it very hard for us to fix a bug if we cannot reproduce it

Thanks for your feedback

**Comment by jgg1822** [comment]
Thanks for the quick reply!

Attached is the folder where the templates are saved. I right-clicked on a compound building block and saved it to a template, and I got a message that it saved correctly. When I tried to right-click and import it, I got the error message. I was able to do this successfully for a few other compound files just before this. I am still able to save compounds to a template with a successful message.

**Comment by msevestre** [comment]
@jgg1822 Unfortunatley, attachement do not work via email. You need to upload them via github :)

**Comment by jgg1822** [comment]
Oops! See attached.
[7.4.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4752395/7.4.zip)

**Comment by msevestre** [comment]
@jgg1822 I think this is a bug in the software. I'd like to know how you manage to induce it
Here are my observations

1. Compound S-Meth_v8 references a metabolite EDDP_v4
1. EDDP_v4 does not exist in the database anymore

What actions did you perform to create this state? Did you rename, delete, save and overwrite etc..

That would be very helpful

**Comment by msevestre** [comment]
Ok this happens when removing a template that was used as reference.

**Comment by jgg1822** [comment]
Thanks for looking into this. When I saved S-Meth_v8, it asked me if I wanted to save the metabolite as well, which I did. But I then realized that the metabolite it’s linked to is the incorrect one, so I right-clicked and deleted EDDP_v4 from the database the next time I went in to save a compound file as a template. Should I save EDDP_v4 as a template again to fix this?

**Comment by msevestre** [comment]
[7.4_fixed.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4752794/7.4_fixed.zip)

use this folder instead. I fixed if for you by pointing to the EDDP_v7

This is a bug in the software. Thanks for pointing it out

**Comment by jgg1822** [comment]
Thank you! It’s working now.

**Comment by msevestre** [comment]
@jgg1822 I renamed the issue to be more explicit now that we know what's going on

**Comment by Yuri05** [comment]
assumed fixed
