### ISSUE TITLE
WJ not saved after project closed unsaved

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#150]
PK-sim project and WJ was created. New Page in WJ was created and filled with text. Nothing was done in the project however. When project is closed, user is not asked to save changes as there were none in the project. However the changes in the WJ are lost...that should not be...empty project and WJ attached
WJ not saved.zip
(saved.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/973837/WJ.not.saved.zip))
 same is most likely true for MoBi...

**Comment by Yuri05** [comment]
Cannot reproduce with 7.3.
Created page is added to WJ even if PK-Sim project was not saved.

**Comment by tobiasK2001** [comment]
Reproduced it PK-sim Portable 7.3.0
The error below occured and WJ was not saved. Is it just the Portable Version?

Application:
PK-Sim® 7.3.0.42

SQL logic error
no such table: SUMMARY_CHART

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass16_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
This is something completely different. Please describe exactly what you are doing @Tobiask2001  . This is the only way we can reproduce and fix the problem

**Comment by tobiasK2001** [comment]
OK, 
1. PK.sim 7.3 portable version  opend. 
2. Saved PK-sim project under  name Test2 without any input.
3. clicked button add WJ Page and selcted create new WJ saved it under name Test2.
4. Filled new Page with some text. Nothing was done in the project however. 
5. Closed Project. When project is closed, user is not asked to save changes as there were none in the project. 
6. After closing of Project WJ was created. However the changes in the WJ page are lost. when reopened

Repeated Step 1.-4. but clicked save button in WJ page "file" tab.
then modev on with steps 5.-6. Input in WJ Page was saved. 
I gues this is the way It should be:

Tried to reproduse error message above by redoing Step 1.-6. with new project and adding two WJ Pages without clicking save button in WJ page "file" tab. But this time no error appeard and changes in WJ Page 1 was saved. Only changed in WJ Page 2 were not saved. 
Again I guess it should be like that. So Error is not reproducable and I think the Proble is fixed.
Thanks for that! :-)

**Comment by StephanSchaller** [comment]
But how is it fixed?

Wasn't above error occurring in PK-Sim® 7.3.0.42? You still have the same version, right?

**Comment by tobiasK2001** [comment]
Yes I was using 7.3.0.42 portable, when Issue didn't appear again.

**Comment by Yuri05** [comment]
seems to fixed. please reopen if the error is still there
