### ISSUE TITLE
PK-Sim loading a project error

### ISSUE THREAD

**Issue by AyaSaleh90** [Open-Systems-Pharmacology/PK-Sim#1589]
Hello all,

I was working normally on PK-Sim version 9.0, and last thing I did was a parameter Identification step then saved everything yesterday and today I started to work back on it I got this error message and everything is gone from the project (like a new project from a scratch)
It was suggested by interface to copy the stack Trace and paste here so someone can help me out

Thanks in advance
Aya

Application:
PK-Sim® 9.0.170

Value cannot be null.
Parameter name: key

Stack trace:
```
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(ObservedDataMetaData observedDataMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<>c__DisplayClass5_0.<MapFrom>b__0(ObservedDataMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass17_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@AyaSaleh90 Can you attach the project to this issue so that we can take a look? you can also send it to me directly at michael@design2code.ca

**Comment by AyaSaleh90** [comment]
@msevestre I have sent it to you on mail, Thanks in advance

**Comment by AyaSaleh90** [comment]
@msevestre I have sent it to you on mail, thanks in advance

**Comment by msevestre** [comment]
@AyaSaleh90 I have looked at your project. It looks like one of the observed data is corrupted `K449TeilI.Midazolam.1`

@Yuri05 The reason seems to be that some ExtendedProperties have no name property
```
<McDataRepository id="a3ab5f0e-0db2-4f1b-9a95-3b5014939f9b" name="K449TeilI.Midazolam.1" icon="ObservedData" xmlVersion="77">
...



   <ExtendedProperties>
...
    <StringExtendedProperty name="xx" readOnly="0" value="1" />
  **HERE=>>> <StringExtendedProperty readOnly="0" />**

  </ExtendedProperties>
</McDataRepository>
```
