### ISSUE TITLE
Parameter identification: Maximum number of iterations = 0 does not behave as designed

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#159]
If the parameter "Maximum number of iterations" in the PI-configuration is set to 0, the algorithm should not optimize but only calculate error/sensitivities. However, the setting is ignored and the algorithm optimizes.

Steps to reproduce:
1) Open the "Theophylline" example project in PK-Sim
2) Select simulation "Kaumeier oral solution 185mg" and select "Start parameter identification..."
3) In the "Configuration"-tag of the PI, set the value of "Maximum number of iterations" to 0.
4) Start the PI.
5) When finished, go to "Results-tab. As can be seen, 17 evaluation were performed and the parameter values are changed.

**Comment by msevestre** [comment]
Bug in MPFit it seems. I have fixed the issue and submitted a PR
https://github.com/cureos/csmpfit/issues/8

**Comment by msevestre** [comment]
@PavelBal Some iterations will be performed as the algo needs to evaluate the error. But no optimization will run

**Comment by PavelBal** [comment]
Almost there, but now an exception is thrown.

Steps to reproduce:

1.     Open the "Theophylline" example project in PK-Sim
2.     Select simulation "Kaumeier oral solution 185mg" and select "Start parameter identification..."
3.     Select "Lipophilicity" as the parameter to optimize
3.     In the "Configuration"-tag of the PI, set the value of "Maximum number of iterations" to 0.
4.     Start the PI and open the Visual Feedback window.
5.     When finished, an exception is thrown. This happens only after the first run! If the same optimization is started one more time, no exception is thrown. Also, when starting the optimization with "Maximum number of iterations" > 0, no exception is thrown.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationChartFeedbackPresenter`1.UpdateColumn(DataColumn valueColumn, OptimizationRunResult runResult)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationChartFeedbackPresenter`1.UpdateFeedback(ParameterIdentificationRunState runState)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.SingleParameterIdentificationFeedbackPresenter.<updateFeedback>b__9_0(IParameterIdentificationRunFeedbackPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.SingleParameterIdentificationFeedbackPresenter.updateFeedback()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.SingleParameterIdentificationFeedbackPresenter.updateFeedbackIfRequired()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.SingleParameterIdentificationFeedbackPresenter.<.ctor>b__3_0(Object o, ElapsedEventArgs e)

**Comment by msevestre** [comment]
@PavelBal Thanks man. Probably we did not try with the Feedback view open.

**Comment by msevestre** [comment]
Can you reproduce that ? I tried several times but no problems there

**Comment by PavelBal** [comment]
I could reproduce it on the remote machine today morning, but not any more. Something changed?

**Comment by PavelBal** [comment]
Have to be quick to catch a bug :D

**Comment by msevestre** [comment]
Fix in core https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/273
