### ISSUE TITLE
System issue when I save the parameter identification

### ISSUE THREAD

**Issue by Celin7391** [Open-Systems-Pharmacology/PK-Sim#1689]
Application:
PK-Sim® 9.1.2

Array cannot be null.
Parameter name: bytes

Stack trace:
```
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.ParameterIdentificationContentLoader.LoadContentFor(ParameterIdentification parameterIdentification)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
Closing. Please reopen if you can give us some steps on how to reproduce the issue
