### ISSUE TITLE
Import observed data from Configuration: Crash if configuration selection cancelled

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1705]
```
at OSPSuite.UI.Services.DataImporter.ImportFromConfiguration(ImporterConfiguration configuration, IReadOnlyList`1 metaDataCategories, IReadOnlyList`1 columnInfos, DataImporterSettings dataImporterSettings)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.getObservedDataFromImporter(ImporterConfiguration configuration, Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit) in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_13.04\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 179
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataFromConfiguration(ImporterConfiguration configuration, Func`1 importConfiguration, Compound compound, String dataRepositoryName, Boolean allowCompoundNameEdit) in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_13.04\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 152
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataFromConfigurationToProjectForCompound(Compound compound, ImporterConfiguration configuration) in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_13.04\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 141
   at PKSim.Presentation.UICommands.ImportConcentrationDataFromConfigurationCommand.PerformExecute() in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_13.04\src\PKSim.Presentation\UICommands\ImportConcentrationDataFromConfigurationCommand.cs:line 20
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by georgeDaskalakis** [comment]
fixed
