### ISSUE TITLE
Data import crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1714]
"Add observed data..." in empty project with the file attached crashes:
[011_TAllMetaData_C.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379362/011_TAllMetaData_C.xlsx)

```
Application:
PK-Sim® 10.0.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Infrastructure.Import.Services.Importer.<>c.<CheckWhetherAllDataColumnsAreMapped>b__9_2(MappingDataFormatParameter cm)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Infrastructure.Import.Services.Importer.CheckWhetherAllDataColumnsAreMapped(IReadOnlyList`1 dataColumns, IEnumerable`1 mappings)
   at OSPSuite.Presentation.Presenters.Importer.ColumnMappingPresenter.ValidateMapping()
   at OSPSuite.Presentation.Presenters.Importer.ColumnMappingPresenter.setDataFormat(IList`1 formatParameters)
   at OSPSuite.Presentation.Presenters.Importer.ColumnMappingPresenter.SetDataFormat(IDataFormat format)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.onFormatChanged(Object sender, FormatChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.SetDataFormat(IDataFormat format, IEnumerable`1 availableFormats)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.SetDataSource(String dataSourceFileName)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.SetSourceFile(String path)
   at OSPSuite.UI.Services.DataImporter.ImportDataSets(IReadOnlyList`1 metaDataCategories, IReadOnlyList`1 columnInfos, DataImporterSettings dataImporterSettings)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.addObservedData(Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit) in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_26.04\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 228
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProjectForCompound(Compound compound) in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_26.04\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 137
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProject() in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_26.04\src\PKSim.Infrastructure\Services\ImportObservedDataTask.cs:line 62
   at PKSim.Presentation.UICommands.ImportConcentrationDataCommand.Execute() in C:\SW-Dev\PK-Sim\branches\10.0_ImporterTest_26.04\src\PKSim.Presentation\UICommands\ImportConcentrationDataCommand.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
same for:
[002_TF.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379706/002_TF.xlsx)
[003_TCNoUnit.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379707/003_TCNoUnit.xlsx)
[005_TC_Unit2ndRow.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379708/005_TC_Unit2ndRow.xlsx)
[013_TAllMetaDataDiff_C.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379709/013_TAllMetaDataDiff_C.xlsx)
[015_TAllPlusUnknownMetaData_C.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379711/015_TAllPlusUnknownMetaData_C.xlsx)
[022_TCEUnit2ndRow_Bug.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6379712/022_TCEUnit2ndRow_Bug.xlsx)
