### ISSUE TITLE
Snapshot: PI is corrupted

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1767]
If parameters from >1 simulation are linked to the same identification parameter in a PI and then one of the simulations is deleted from **the project** and the project is exported to a snapshot: snapshot is corrupted.

Example:
1. Open the project [PI_DeleteSim.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6538025/PI_DeleteSim.zip)
In the (only) PI 2 simulations (S1 and S2) are used and Specific (Hepatic) Clearance from both simulations is linked to the same identification parameter in the PI: 
<img width="500" src="https://user-images.githubusercontent.com/25061876/119472610-aa75ab80-bd4a-11eb-962e-fb9f81c16be6.png">

2. Delete simulation S2 **from the project**
3. Export the project to snapshot

In the snapshot, Identification parameter **Specific Clearance** is now corrupted.
```
      "IdentificationParameters": [
        {
          "Name": "Specific clearance",
          "Scaling": "Linear",
          "LinkedParameters": [
            "S1|C1-Total Hepatic Clearance-Human fitted|Specific clearance",
            ""
          ],
```

When trying to import the snapshot: it crashes
```
Information: Loading Project from snapshot file 'C:\bug\PI_DeleteSim.json'
Error: Object reference not set to an instance of an object.

Stack trace:
at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.<>c.<CreateFor>b__5_1(ParameterSelection x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.CreateFor(IEnumerable`1 parameterSelections, ParameterIdentification parameterIdentification)
   at PKSim.Core.Snapshots.Mappers.IdentificationParameterMapper.<MapToModel>d__6.MoveNext()
```

**Comment by Yuri05** [comment]
@msevestre FYI

**Comment by msevestre** [comment]
Let's try to fix this one. what's with all these parameters used in PI that are deleted afterwards. Mensch!

**Comment by Yuri05** [comment]
... and https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1662 😉
