### ISSUE TITLE
Error opening observed data 

### ISSUE THREAD

**Issue by fredsevmartins** [Open-Systems-Pharmacology/PK-Sim#1785]
Hi, I get the error below when I try to open my observed data.
No: The file name hasn't  " - () or /" 

What could be?
thanks  
Application:
PK-Sim® 9.1.2

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.Data.DataRepositoryExtensions.valueMapper(IEnumerable`1 properties, IExtendedProperty value)
   at OSPSuite.Core.Domain.Data.DataRepositoryExtensions.<>c__DisplayClass2_0.<IntersectingMetaData>b__3(IExtendedProperty x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryMetaDataPresenter.rebind()
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryMetaDataPresenter.editObservedData(IEnumerable`1 observedData, IEnumerable`1 rules)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryMetaDataPresenter.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.<>c__DisplayClass8_0.<Edit>b__0(IDataRepositoryItemPresenter presenter)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.Edit(DataRepository repositoryToEdit)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject)
   at PKSim.Presentation.UICommands.EditSubjectUICommand`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
any chance you can upload your project? Can you export the obs data to file or sthg like this from PK-Sim?

**Comment by msevestre** [comment]
@fredsevmartins any feedback on this?

**Comment by fredsevmartins** [comment]
@msevestre the problem was solved. The observed data was replaced and the error disappeared.

Thanks
