### ISSUE TITLE
Import Ontogeny and cancel => crash

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1786]
FYI: @abdelr 

Application:
PK-Sim® 10.0.0

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at PKSim.Presentation.Services.OntogenyTask`1.LoadOntogenyForMolecule(IndividualMolecule molecule, TSimulationSubject simulationSubject) in C:\projects\PK-Sim\src\PKSim.Presentation\Services\OntogenyTask.cs:line 65
   at PKSim.Presentation.Presenters.Individuals.OntogenySelectionPresenter`1.LoadOntogeny() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Individuals\OntogenySelectionPresenter.cs:line 96
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@abdelr The reason is that upon cancel,. the method ImportDataSets returns NULL and not an empty liust
