### ISSUE TITLE
Error loading compound building block from template

### ISSUE THREAD

**Issue by jgg1822** [Open-Systems-Pharmacology/PK-Sim#1797]
Hello,

I'm getting the error message copied below when I try to load a compound building block from templates. I'm still able to load other building block types from template (formulation, etc), and to save a compound building block to a template. Can you help me troubleshoot this?

Thanks!

Application:
PK-Sim® 9.1.2

There is no row at position 0.

Stack trace:
```
at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at PKSim.Infrastructure.ORM.DAS.DASDataRowCollection.ItemByIndex(Int32 Index)
   at PKSim.Infrastructure.Extensions.DASExtensions.ExecuteQueryForSingleRow(DAS connection, String query)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.loadTemplateBy(TemplateDatabaseType templateDatabaseType, String templateName, String templateType, DAS connection)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.addReferencesToTemplate(Template template, DAS connection, List`1 loadedReferenceNames)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateDatabaseType templateDatabaseType, TemplateType templateType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateType templateType)
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplate[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.LoadFromTemplate[TBuildingBlock](PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate()
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadSingleFromTemplate()
   at PKSim.Presentation.UICommands.LoadBuildingBlockFromTemplateUICommand`2.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
@jgg1822 If you can zip your DB and attached it here (or send it over to me), I could check it out and let you know. Otherwise, this will be very hard to troubleshoot

**Comment by jgg1822** [comment]
Yes, please see attached. I think this is the template DB you are referring to?

[PKSimTemplateDBUser.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6678363/PKSimTemplateDBUser.zip)

**Comment by msevestre** [comment]
ok checking this out now. We'll update the DB soon

**Comment by msevestre** [comment]
ok this is because you have metabolite saved that referenced a compound (EDDP_v4) that was deleted.
I'll remove the reference for now. I think we fixed this bug in v10 but I'll double check

**Comment by msevestre** [comment]
@jgg1822 Here is the fixed version
[PKSimTemplateDBUser.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6710258/PKSimTemplateDBUser.zip)

**Comment by msevestre** [comment]
@Yuri05 Well..we still have this bug. Going to fix this

**Comment by jgg1822** [comment]
Awesome, thank you - it's working now!
