### ISSUE TITLE
Excel export/import stopped working

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#184]
On the  test machine excel export stopped working

Application:
PK-Sim® 7.1.0 - Build 57

Could not load file or assembly 'SX, Version=2.6.3.3, Culture=neutral, PublicKeyToken=882b9c044052e7f6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack trace:
```
at OSPSuite.Infrastructure.Services.ReportTask.CreateReport(IHistoryManager historyManager, ReportOptions reportOptions)
   at PKSim.Presentation.UICommands.ExportHistoryToExcelCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
What do you mean stopped working? Suddenly it does not work anymore?

**Comment by Yuri05** [comment]
Yes. Just installed the latest nightly.

**Comment by msevestre** [comment]
latest nightly is 7.1.0.59 .

**Comment by msevestre** [comment]
installing latest on VM

**Comment by msevestre** [comment]
yes could reproduce. For some reason, the PKSim.exe,config  is not using the latest version of SX. Weird

**Comment by msevestre** [comment]
This is fixed now
