### ISSUE TITLE
Open simulation then comparison causes exception

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#188]
Comparison contains a simulation

Open the simulation first, then the comparison and exception is thrown.

```
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at DevExpress.XtraEditors.ScrollTouchBase.SetVisibility(Boolean visible)
   at DevExpress.XtraEditors.VScrollBar.SetVisibility(Boolean visible)
   at DevExpress.XtraTreeList.Scrolling.ScrollInfo.set_VScrollVisible(Boolean value)
   at DevExpress.XtraTreeList.TreeList.UpdateVScrollBarCore()
   at DevExpress.XtraTreeList.TreeList.UpdateVScrollBar()
   at DevExpress.XtraTreeList.TreeList.UpdateScrollBars()
   at DevExpress.XtraTreeList.TreeList.get_FocusedRow()
   at DevExpress.XtraTreeList.TreeList.OnSetValue(TreeListNode node, Object columnID, Object val)
   at DevExpress.XtraTreeList.Nodes.TreeListNode.SetValue(Object columnID, Object val)
   at OSPSuite.UI.Controls.UxTreeView.setNodeText(TreeListNode node, String text) in C:\projects\ospsuite-core\src\OSPSuite.UI\Controls\UxTreeView.cs:line 306
   at OSPSuite.UI.Controls.UxTreeView.nodeTextChanged(ITreeNode node) in C:\projects\ospsuite-core\src\OSPSuite.UI\Controls\UxTreeView.cs:line 301
   at System.Action`1.Invoke(T obj)
   at OSPSuite.Presentation.Nodes.AbstractNode.set_Text(String value) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Nodes\AbstractNode.cs:line 65
   at OSPSuite.Presentation.Presenters.Nodes.ObjectWithIdAndNameNode`1.UpdateText() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\Nodes\ObjectWithIdAndNameNode.cs:line 21
   at OSPSuite.Presentation.Nodes.AbstractNode`1.propertyNameChanged(Object sender, PropertyChangedEventArgs e) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Nodes\AbstractNode.cs:line 199
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at OSPSuite.Utility.Reflection.Notifier.RaisePropertyChanged(String propertyName) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Reflection\Notifier.cs:line 38
   at OSPSuite.Utility.Reflection.Notifier.OnPropertyChanged(String propertyName) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Reflection\Notifier.cs:line 25
   at OSPSuite.Core.Domain.Classifiable`1.<set_Subject>b__19_0(Object o, PropertyChangedEventArgs e) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Classifiable.cs:line 60
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at OSPSuite.Utility.Reflection.Notifier.RaisePropertyChanged(String propertyName) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Reflection\Notifier.cs:line 38
   at OSPSuite.Utility.Reflection.Notifier.OnPropertyChanged[TPropertyType](Expression`1 exp) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Reflection\Notifier.cs:line 33
   at OSPSuite.Core.Chart.CurveChart.set_Name(String value) in C:\projects\ospsuite-core\src\OSPSuite.Core\Chart\CurveChart.cs:line 208
   at lambda_method(Closure , Object , Object )
   at OSPSuite.Serializer.Reflection.ReadWritePropertyAccessor.SetValue(Object destination, Object value) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\Reflection\ReadWritePropertyAccessor.cs:line 17
   at OSPSuite.Serializer.PropertyMap.SetValue(Object destination, Object valueToSet) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\PropertyMap.cs:line 70
   at OSPSuite.Serializer.Xml.XmlAttributeMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\Xml\XmlAttributeMapper.cs:line 31
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\Xml\XmlSerializer.cs:line 149
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(Object objectToDeserialize, XElement outputToDeserialize, TContext context) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\Xml\XmlSerializer.cs:line 62
   at PKSim.Infrastructure.Serialization.Xml.Serializers.PKSimChartXmlSerializer`1.TypedDeserialize(TChart chart, XElement chartElement, SerializationContext serializationContext) in C:\Users\rob\repos\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\Serializers\PKSimChartXmlSerializer.cs:line 36
   at PKSim.Infrastructure.Serialization.Xml.Serializers.IndividualSimulationComparisonXmlSerializer.TypedDeserialize(IndividualSimulationComparison chart, XElement chartElement, SerializationContext serializationContext) in C:\Users\rob\repos\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\Serializers\PKSimChartXmlSerializer.cs:line 67
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(Object objectToDeserialize, XElement outputToDeserialize, TContext context) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\Xml\XmlSerializer.cs:line 62
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(T objectToRead, XElement element, SerializationContext serializationContext) in C:\Users\rob\repos\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\XmlReader.cs:line 37
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext) in C:\Users\rob\repos\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\XmlSerializationManager.cs:line 115
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext) in C:\Users\rob\repos\PK-Sim\src\PKSim.Core\Services\CompressedSerializationManager.cs:line 47
   at PKSim.Infrastructure.Services.SimulationComparisonContentLoader.LoadContentFor(ISimulationComparison simulationComparison) in C:\Users\rob\repos\PK-Sim\src\PKSim.Infrastructure\Services\SimulationComparisonContentLoader.cs:line 23
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad) in C:\Users\rob\repos\PK-Sim\src\PKSim.Infrastructure\Services\LazyLoadTask.cs:line 46
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0() in C:\Users\rob\repos\PK-Sim\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 31
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Services\HeavyWorkManager.cs:line 97
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Services\HeavyWorkManager.cs:line 62
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by Yuri05** [comment]
not reproducible anymore, prob. fixed
