### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Mwilaputa** [Open-Systems-Pharmacology/PK-Sim#1938]
Application:
PK-Sim® 9.1.2

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Views.Charts.ChartDisplayView.GetPointsForSecondaryAxis(Single x, Single y, AxisTypes yAxisType)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.setSecondaryAxisRange(Single xMin, Single xMax, Single yMin, Single yMax, AxisTypes axisType)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.<>c__DisplayClass38_0.<SetVisibleRange>b__0(AxisTypes axisType)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.SetVisibleRange(Nullable`1 xMin, Nullable`1 xMax, Nullable`1 yMin, Nullable`1 yMax)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.postZoom(RangeInfo xRange, RangeInfo yRange)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.onZoom(ChartZoomEventArgs e)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.<>c__DisplayClass22_2.<InitializeResources>b__13()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Hey @Mwilaputa Thanks for reporting
Can you attach a project so that we can reproduce and potentially let us know how to reproduce the issue?

**Comment by msevestre** [comment]
@Mwilaputa Can you send us the project? That would be very helpful

**Comment by Mwilaputa** [comment]
> @msevestre I am trying to attach the PK-Sim file but seems it's not supported.  Is there any other way I can attach the PkSim file. Sorry I am new Github and trying to learn how to use it.

**Comment by Mwilaputa** [comment]
> @Mwilaputa Can you send us the project? That would be very helpful

[Dolutegravir.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7625497/Dolutegravir.zip)
@msevestre finally I have managed to upload the file.

**Comment by msevestre** [comment]
Thank you :)

**Comment by msevestre** [comment]
@abdelr @georgeDaskalakis If you want to check it out..
.

**Comment by Yuri05** [comment]
seems to be fixed. closing
