### ISSUE TITLE
PK-Sim® 10.0.256  Key 'ExpressionParameters.PARAM_f_endo' could not be found

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1952]
I tried to create a rat iv simulation but I got this.
Is it a known bug?

Application:
PK-Sim® 10.0.256

Key 'ExpressionParameters.PARAM_f_endo' could not be found

Stack trace:
```
at OSPSuite.Utility.Collections.Cache`2.<>c.<.ctor>b__10_0(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.get_Item(TKey key)
   at PKSim.Infrastructure.ORM.Repositories.RateFormulaRepository.FormulaFor(RateKey rateKey)
   at PKSim.Core.Model.FormulaFactory.createFormula(RateKey rateKey)
   at PKSim.Core.Model.FormulaFactory.RateFor(RateKey rateKey, IFormulaCache formulaCache)
   at PKSim.Core.Model.FormulaFactory.RateFor(String calculationMethod, String rate, IFormulaCache formulaCache)
   at PKSim.Core.Services.PKSimParameterStartValuesCreator.setParameter(IParameter parameter, Boolean isSmallMolecule)
   at PKSim.Core.Services.PKSimParameterStartValuesCreator.<>c__DisplayClass8_0.<updateMoleculeParametersValues>b__0(IParameter p)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Core.Services.PKSimParameterStartValuesCreator.updateMoleculeParametersValues(IndividualMolecule molecule, Individual individual, Simulation simulation)
   at PKSim.Core.Services.PKSimParameterStartValuesCreator.<>c__DisplayClass5_1.<CreateFor>b__0(IndividualMolecule molecule)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Core.Services.PKSimParameterStartValuesCreator.CreateFor(IBuildConfiguration buildConfiguration, Simulation simulation)
   at PKSim.Core.Services.BuildConfigurationTask.CreateFor(Simulation simulation, Boolean shouldValidate, Boolean createAgingDataInSimulation)
   at PKSim.Core.Services.SimulationModelCreator.CreateModelFor(Simulation simulation, Boolean shouldValidate, Boolean shouldShowProgress)
   at PKSim.Presentation.Presenters.Simulations.CreateSimulationPresenter.UpdateSimulationProperties()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
@tobiasK2001 Cannot reproduce
![image](https://user-images.githubusercontent.com/1041237/140962269-4b7914df-c688-4c01-8999-bc2820b2926e.png)


Is this an old project?

**Comment by Yuri05** [comment]
@tobiasK2001 This probably will not solve your problem, but I just noticed that you are using PK-Sim 10.0.**256** - but OSP Suite 10 final release includes PK-Sim 10.0.**257**

**Comment by tobiasK2001** [comment]
@ Juri. Yes I am using the portable setup, for which I only found 10.0.256. Is there a newer portable Version? Sorry, I cannot install the full setup as by now.
@msevestre : It is an newly created project. I attached it here:
Steps to reproduce: 
![image](https://user-images.githubusercontent.com/25585248/141072962-320bc210-65fc-4ea7-80ce-72eeec832fd1.png)
![image](https://user-images.githubusercontent.com/25585248/141073045-a76059ce-8d4b-4238-96b7-cc5029cd7be0.png)
![image](https://user-images.githubusercontent.com/25585248/141073091-abc76755-84d8-4b95-84d1-2547f04d6fac.png)
than clicked next and 
[Session1-Midazolam.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7510851/Session1-Midazolam.zip)
OK

**Comment by Yuri05** [comment]
Regarding the PK-Sim portable: the latest PK-Sim release was updated with 10.0.257 now, you can take it from there:
https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/tag/v10.0

For the initial problem: it crashes if you name your protein as an organ (e.g. "Liver" in your case).
So please remove your individual and recreate it, giving a "more valid" name to your protein
(It seems that trying to create a simulation with a protein named like "Liver" makes an individual corrupted, so even after renaming the protein or removing the protein and adding a new one with valid name simulation creation still does not work)

**Comment by tobiasK2001** [comment]
Awesome Thanks! Good to know that!

Best, Tobias
