### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by watt0005** [Open-Systems-Pharmacology/PK-Sim#2019]
When I try to save or save as, I get the error below. I am unable to share the project file.

Thanks,
Kevin Watt

Application:
PK-Sim® 9.1.2

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Infrastructure.Serialization.Xml.Serializers.PopulationXmlAttributeMapper.Convert(SpeciesPopulation speciesPopulation, SerializationContext context)
   at OSPSuite.Serializer.Attributes.AttributeMapper`2.Convert(Object valueToConvert, Object context)
   at OSPSuite.Serializer.Xml.XmlAttributeMapper`2.Serialize(TObject objectToSerialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedSerialize(TObject objectToSerialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Serialize(Object objectToSerialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlWriter`1.WriteFor(T objectToSerialize, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom[TObject](TObject objectToSerialize, SerializationContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Serialize[TObject](TObject objectToSerialize)
   at PKSim.Core.Services.CompressedSerializationManager.Serialize[TObject](TObject objectToSerialize)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.Visit(Individual individual)
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitMethod[T](IVisitor visitor, T objectToVisit, MethodInfo method)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitForType[T](Type visitorType, IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorInvoker.InvokeVisit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorExtensions.Visit[T](IVisitor visitor, T objectToVisit)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.mapFrom(IPKSimBuildingBlock buildingBlock)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.<>c__DisplayClass4_0.<MapFrom>b__0(IPKSimBuildingBlock x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectToProjectMetaDataMapper.MapFrom(PKSimProject project)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectMetaDataFrom(PKSimProject project)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Save(PKSimProject projectToSave, ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.SaveSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.SaveProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass21_0.<saveProjectToFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by watt0005** [comment]
Problem solved. We created a new population that is located in mobile PK Sim. When I opened the PK Sim file directly by double clicking, it defaulted to opening in normal PK Sim. The error occurred because that population was not available in normal PK Sim. Once I launched mobile PK Sim, and then opened the project file, everything was fine.

**Comment by Yuri05** [comment]
With "mobile PK Sim" you mean a portable version of PK-Sim I guess? Which portable version of PK-Sim are you using?
That's correct: if started per double click, the PK-Sim version which was installed with the setup will be launched.
The error message could be a bit more user friendly though :)

**Comment by watt0005** [comment]
Correct, portable PK Sim v 9.1.2

Kevin

Kevin Watt, MD, PhD
Robert M. Ward Endowed Chair in Clinical Pharmacology
Chief, Division of Clinical Pharmacology
Division of Pediatric Critical Care Medicine
Department of Pediatrics
University of Utah School of Medicine
Phone: 801-587-7404
***@***.******@***.***>

**Comment by msevestre** [comment]
There is absolutely no reason why the portable version would behave differently than the real version, especially when they are both 9.1.3
What do you mean with "The error occurred because that population was not available in normal PK Sim."

What population is not available in the normal pksim?

**Comment by watt0005** [comment]
Hi Michael – hope all is well. Kate Job and I worked with Andre Dallmann to create a post-partum population and housed this population in the portable version of PK sim.

Kevin

Kevin Watt, MD, PhD
Robert M. Ward Endowed Chair in Clinical Pharmacology
Chief, Division of Clinical Pharmacology
Division of Pediatric Critical Care Medicine
Department of Pediatrics
University of Utah School of Medicine
Phone: 801-587-7404
***@***.******@***.***>

**Comment by msevestre** [comment]
Ah ah ok that makes sense;-)
Thanks Kevin. Merry Christmas to you and yours

@Yuri05 let's indeed improve the error message with something that is not so cryptical

**Comment by rwmcintosh** [comment]
We hit this again on 13.0, this time with a different trigger, so here is the full picture and a proposed fix.

## Why it crashes

`PopulationXmlAttributeMapper.Convert` dereferences `speciesPopulation.Name` without a null check, unlike its siblings `SpeciesXmlAttributeMapper` and `DiseaseStateXmlAttributeMapper`, which both handle null. `XmlAttributeMapper.Serialize` (OSPSuite.Serializer) passes the property value straight into `Convert`, null included, so an `OriginData` whose `Population` is null throws on serialization.

That makes the project **unsavable for the rest of the session**, because `ProjectToProjectMetaDataMapper.Visit(Individual)` serializes `individual.OriginData` unconditionally — no `IsLoaded` / `HasChanged` guard, unlike the BB content right above it:

```csharp
serializeContentFor(individual);                                                     // guarded
_metaData.Properties.Data = _serializationManager.Serialize(individual.OriginData);   // unguarded
```

## Two ways `OriginData.Population` becomes null

**1. A population name that this installation's database does not have** (the original report above: a post-partum population added to a portable PK-Sim, project then opened in a standard one). `PopulationXmlAttributeMapper.ConvertFrom` calls `FindByName`, gets null, and silently hands back a broken `OriginData`.

**2. Extracting individuals from an imported population** (the case we just saw). `IndividualExtractor.extractIndividualFrom`:

```csharp
originData.Gender     = population.AllGenders(_genderRepository)[individualId];
originData.Population = population.AllSpeciesPopulations(_populationRepository)[individualId];
```

Both resolve a **covariate string** via `FindByName`, and both write null straight into the domain model when the lookup fails. The extracted individual is a clone of `population.FirstIndividual`, so it arrives with a perfectly valid `Population` — these two lines overwrite it with null.

The covariate strings are never validated: `ImportPopulationFactory.validate` only checks parameter paths. And OSPSuite.Core actively produces unresolvable values — `CovariateValuesCache.Merge` pads any covariate missing from one of the merged files with `Constants.UNKNOWN` ("Unknown") via `CovariateValues.AddEmptyItems`, and `CovariateValues.ValueAt` returns "Unknown" for out-of-range indices. A `Population` column holding a display name (`European (ICRP, 2002)` instead of `European_ICRP_2002`), or `Gender` as `M`/`F` instead of `MALE`/`FEMALE`, has the same effect.

Note `Gender` has exactly the same defect one line up: `GenderXmlAttributeMapper.Convert` dereferences `gender.Name` unguarded, and `Gender` is mapped right after `Population` in `OriginDataXmlSerializer` — so it is the next exception after this one is fixed.

## There is no recovery inside the affected session

Everything that could repair or remove the individual is blocked:

- **Edit individual** — `loadFromIndividual` ends in `updatePopulationControls()`, which dereferences `Population.IsAgeDependent`; the dialog cannot open. Origin data is read-only there anyway.
- **Scale individual** — same `loadFromIndividual`, same exception.
- **Delete individual** — `RemoveBuildingBlockFromProjectCommand` serializes the BB for the undo stream (the stack in this issue).
- **Undo the extraction** — the inverse of `AddBuildingBlockToProjectCommand` is that same remove command.
- **Clone** — `OriginData.Clone()` copies `Population`, so the clone is broken too.
- **Save / Save As / project snapshot export** — all serialize the origin data; `OriginDataMapper.MapToSnapshot` also dereferences `originData.Population.Name`.

The only workaround we could give the user was to save each building block individually to the template DB or as a per-BB snapshot, and redo the extraction later.

## Proposed fix

1. **Null-guard `PopulationXmlAttributeMapper.Convert` and `GenderXmlAttributeMapper.Convert`**, matching `SpeciesXmlAttributeMapper`. `XmlAttributeMapper.Serialize` drops the attribute when `Convert` returns null or empty, so this makes an already-broken individual savable and deletable — the immediate unblock for anyone sitting on an unsavable project.

2. **Stop creating broken individuals** in `IndividualExtractor` — do not overwrite a valid reference with a failed lookup:

```csharp
originData.Gender     = population.AllGenders(_genderRepository)[individualId] ?? originData.Gender;
originData.Population = population.AllSpeciesPopulations(_populationRepository)[individualId] ?? originData.Population;
```

The base individual's values are the right fallback: same species, and the values the population itself was built from. A warning naming the unresolved covariate value would help users spot a bad population file.

3. **Repair existing broken individuals on load** — override `TypedDeserialize` in `OriginDataXmlSerializer`: after the base call, if `Population` is null assign `Species.DefaultPopulation`, and if `Gender` is null assign `Population.DefaultGender`. `Species` is resolved first and has its own null guard, so it is available at that point. This is what actually rescues an existing project: reopen it and the individuals come back valid, with no manual deletion.

Without (3), users have to delete every affected individual and redo the work; with it, the project heals on open.

Optionally, validating covariate values at population import (warning + falling back to the base individual's population/gender, in the spirit of the existing `ParameterWithPathNotFoundInBaseIndividual` warning) would stop the bad values entering the population in the first place. That is the deeper fix, but it does not help projects that already contain them.
