### ISSUE TITLE
CKD: Scaling from "Healthy individual" to "CKD individual" crashes

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2031]
Create healthy indicvidual with all defaults.
Scale it; in the scaling dialog change disease state from "Healthy" to "CKD" and click Next: the error below appears

Application:
PK-Sim® 11.0.0

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Core.Services.CKDDiseaseStateImplementation.getTargetGFRValue(Double gfrValueInLPerMinPerDm2) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\CKDDiseaseStateImplementation.cs:line 271
   at PKSim.Core.Services.CKDDiseaseStateImplementation.applyTo(Individual individual, Action`2 updateParameterFunc) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\CKDDiseaseStateImplementation.cs:line 108
   at PKSim.Core.Services.CKDDiseaseStateImplementation.ApplyTo(Individual individual) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\CKDDiseaseStateImplementation.cs:line 94
   at PKSim.Core.Model.IndividualFactory.CreateAndOptimizeFor(OriginData originData, Nullable`1 seed) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Model\IndividualFactory.cs:line 67
   at PKSim.Presentation.DTO.Mappers.IndividualSettingsDTOToIndividualMapper.MapFrom(IndividualSettingsDTO individualSettingsDTO) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\DTO\Mappers\IndividualSettingsDTOToIndividualMapper.cs:line 24
   at PKSim.Presentation.Presenters.Individuals.IndividualSettingsPresenter.<CreateIndividual>b__42_0() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\Individuals\IndividualSettingsPresenter.cs:line 227
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment]
EDIT: it's not the scaling, seems that I cannot create a CKD individual at all now.
I get the error above with new CKD individual as soon as I click "Next" in CreateIndividual-Dialog

**Comment by msevestre** [comment]
Same issue. Your dimension file locally is not up to date

**Comment by Yuri05** [comment]
yep, that was the reason. closing
