### ISSUE TITLE
Adding Variablity in Population Simulations from MoBi Parameter

### ISSUE THREAD

**Issue by mags0728** [Open-Systems-Pharmacology/PK-Sim#2033]
For my population simulations in PK-Sim, I am attempting to add a parameter under "User Defined Variability". This parameter ("BP") is an empirical equation that was constructed and defined in MoBi to capture the RBC concentration-dependent binding seen in my study drug. However, it gives me an error when I try to add this parameter (BP). Any guidance is much appreciated. 

Application:
PK-Sim® 10.0.257

Function does not accept floating point Not-a-Number values.

Stack trace:
```
at System.Math.Sign(Double value)
   at OSPSuite.Core.Maths.RootFinding.Zbrent.Compute(Func`2 func, Double x1, Double x2, Double tol)
   at OSPSuite.Core.Maths.Statistics.NormalDistribution.CalculateValueFromPercentile(Double percentile)
   at OSPSuite.Core.Domain.Formulas.NormalDistributionFormula.CalculateValueFromPercentile(Double percentile, IUsingFormula dependentObject)
   at OSPSuite.Core.Domain.Formulas.NormalDistributionFormula.CalculateFor(IEnumerable`1 usedObjects, IUsingFormula dependentObject)
   at OSPSuite.Core.Domain.Formulas.Formula.Calculate(IUsingFormula refObject)
   at OSPSuite.Core.Domain.Quantity.get_Value()
   at OSPSuite.Core.Domain.DistributedParameter.get_Value()
   at PKSim.Core.Model.ParameterFactory.updateDefaultValueFor(IParameter parameter)
   at PKSim.Core.Model.ParameterFactory.create(ParameterDistributionMetaData distributionMetaData, Func`2 createFormula)
   at PKSim.Core.Model.ParameterFactory.CreateFor(ParameterDistributionMetaData distributionMetaData)
   at PKSim.Core.Model.AdvancedParameterFactory.Create(IParameter parameter, DistributionType distributionType)
   at PKSim.Core.Model.AdvancedParameterFactory.CreateDefaultFor(IParameter parameter)
   at PKSim.Core.Services.AdvancedParametersTask.AddAdvancedParameter(IParameter parameter, IAdvancedParameterContainer advancedParameterContainer)
   at PKSim.Presentation.Presenters.AdvancedParameters.AdvancedParametersPresenter.AddAdvancedParameter()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment]
Can you attach your projects (both PK-Sim and MoBi)?
If not: please provide the screenshots of
* how is your parameter defined in MoBi
* how is your parameter variation defined in PK-Sim

**Comment by mags0728** [comment]
@Yuri05 I provided screenshots of the following: 
**How parameter is defined in MoBi:** 
![InkedMOBI BP Defined](https://user-images.githubusercontent.com/97306838/148774479-c1114159-c93f-47d3-8580-0e8e35ef0e66.jpg)

**Application of parameter in an individual simulation:** 
![InkedMOBI BP Clark Simulation](https://user-images.githubusercontent.com/97306838/148774576-7f414d65-e9af-4d5f-bcd9-fe2308b95f09.jpg)

**How parameter variation defined in PK-Sim in an adult population** (error when I attempt to add this parameter): 
![InkedPK Sim BP Parameter](https://user-images.githubusercontent.com/97306838/148774656-c7319411-18a2-442f-acea-1408a5c8d7e6.jpg)

Please let me know if you need further information. Thank you!

**Comment by Yuri05** [comment]
The problem is that the initial value of your parameter is `Infinity ` due to the fact that the initial concentration is zero.
When you try to add distribution for this parameter, PK-Sim sets the distribution **as per default** to the Normal Distribution with `Mean = initial parameter value` which crashes then.
Set your **BP** parameter in the MoBi simulation to a constant value before sending the simulation to PK-Sim.

When working in MoBi: apart from being Infinity at t=0: the formula of the BP parameter might become even NaN. The concentration might become slightly negative (e.g. -1e-14 or so) which is just a numerical zero and does not affect the simulation results as long as all formulas are properly defined.
If your parameter really needs to be Infinity for Zero concentration in MoBi: define it as following
`Conc > 0 ? A*Conc^B : Infinity`
Otherwise, just define a (positive) threshold and define your parameter e.g. as 
`Conc > Threshold ? A*Conc^B : A*Threshold^B `

**Comment by msevestre** [comment]
Maybe the error should be better formulated in PKSim...

**Comment by mags0728** [comment]
@Yuri05 Thank you for the feedback. Your explanation makes sense as to why I'm initially unable to add parameter BP as a variability. 

I implemented your suggestion of defining Conc as `Conc > 0 ? A*Conc^B : Infinity` and I was able to add BP parameter under "User Defined Variability" but unable to run the population simulation since BP = 0 (see screenshots below).
I kept BP = A*Conc^(B)

![GH1](https://user-images.githubusercontent.com/97306838/149187326-b77a31b7-1ef2-47d9-89f0-13870e52babb.PNG)
![GH1 on PK Sim](https://user-images.githubusercontent.com/97306838/149187343-69b12d8a-65e1-4a97-aeb2-0cc3321223b1.PNG)

I also tried defining a positive threshold but that resulted in a PK profile that doesn't capture the observed data well 
![GH2 Threshold](https://user-images.githubusercontent.com/97306838/149188688-acbdcb3b-ef48-406d-bfc9-b55efd78fad6.PNG)

Please let me know if you need further information. Thank you!

**Comment by Yuri05** [comment]
hard to say what's going on without the project. Can you attach both the PK-Sim project and the MoBi project?

**Comment by mags0728** [comment]
@Yuri05 please see files attached. Thank you

[TPM_for_GitHub.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7871265/TPM_for_GitHub.zip)

**Comment by Yuri05** [comment]
Well, in all your PK-Sim simulations `TPM|Conc` is defined differently as in your MoBi simulations - I don't know why.
In MoBi you define `TPM|Conc` as `Max(Venosublood/Plasma/TPM/Concentration ; 0)`

![grafik](https://user-images.githubusercontent.com/25061876/149550589-6f795ec9-2776-4067-9ed2-690192d2b19e.png)

In PK-Sim as shown in the screenshot below. So you `TPM|Conc` is **infinity** at the beginning which leads to inavlid negative value of the partition coefficient - and the simulation cannot start.
![grafik](https://user-images.githubusercontent.com/25061876/149550056-ba0d3757-2ac8-4d01-95b1-ae8712eb49fa.png)

**Comment by Yuri05** [comment]
P.S. When importing the simulation from the MoBi project you attached above in PK-Sim, it looks like this.
So obviously it was some other simulation that was imported in PK-Sim, not the attached one.
![grafik](https://user-images.githubusercontent.com/25061876/149551649-c7a454a2-a6a7-4eb1-a68c-15603d6c4f7d.png)

**Comment by mags0728** [comment]
Hi @Yuri05, thank you for your feedback and for catching those errors. Please see the attachment for cleaner versions of PK-Sim and MoBi files, I hope these will better highlight the issue. With regards to the partition coefficient being a negative value, what is your suggestion to circumvent that issue? What are other suggestions I could implement to add BP as a variability in the population simulations?
[TPM_GH_sandbox_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7908632/TPM_GH_sandbox_2.zip)

Thank you.
