### ISSUE TITLE
Saving a project in PKSim with Parameter Identification => Crash

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2050]
Application:
PK-Sim® 11.0.0

Unable to cast object of type 'OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationFeedback' to type 'OSPSuite.Core.Domain.IWithId'.

Stack trace:
```
at OSPSuite.Utility.Extensions.ConversionExtensions.DowncastTo[T](Object objectToCast)
   at PKSim.Presentation.Services.WorkspaceLayoutUpdater.createNewWorkspaceLayoutWithOpenPresenters() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\WorkspaceLayoutUpdater.cs:line 70
   at PKSim.Presentation.Services.WorkspaceLayoutUpdater.SaveCurrentLayout() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\WorkspaceLayoutUpdater.cs:line 50
   at PKSim.Presentation.Services.ProjectTask.saveProjectToFile(String fileName) in C:\dev\PK-Sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 181
   at PKSim.Presentation.Services.ProjectTask.SaveCurrentProject() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 130
   at PKSim.Presentation.UICommands.SaveProjectCommand.Execute() in C:\dev\PK-Sim\src\PKSim.Presentation\UICommands\SaveProjectCommand.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
Due to new addition of PIFeedback object.. should probably not be saved in layout.

**Comment by msevestre** [comment]
@abdelr This needs to be fixed to

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1488](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1488) via [**ZenHub**](https://www.zenhub.com/)
