### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by TitusRoy** [Open-Systems-Pharmacology/PK-Sim#2089]
Application:
PK-Sim® 10.0.257

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Presentation.DTO.Mappers.FormulationMappingDTOToFormulationMappingMapper.MapFrom(FormulationMappingDTO formulationMappingDTO, Simulation simulation)
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolFormulationPresenter.<SaveConfiguration>b__21_0(FormulationMappingDTO formulationMappingDTO)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolFormulationPresenter.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolPresenter.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundCollectorPresenterBase`2.<>c.<SaveConfiguration>b__11_0(TSubCompoundPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundCollectorPresenterBase`2.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationCompoundProtocolCollectorPresenter.SaveConfiguration()
   at PKSim.Presentation.Presenters.Simulations.SimulationWizardPresenter`1.<SaveBuildingBlocksConfiguration>b__15_0(ISubPresenterItem`1 x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Presentation.Presenters.Simulations.SimulationWizardPresenter`1.SaveBuildingBlocksConfiguration()
   at PKSim.Presentation.Presenters.Simulations.CreateSimulationPresenter.ModelConfigurationDone()
   at PKSim.Presentation.Presenters.Simulations.SimulationWizardPresenter`1.WizardCurrent(Int32 previousIndex, Int32 newIndex)
   at OSPSuite.Presentation.Presenters.WizardPresenter`3.WizardNext(Int32 currentIndex)
   at OSPSuite.UI.Views.WizardView.<InitializeWizard>b__27_3()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Thanks for reporting this @TitusRoy 
Can you describe how we can reproduce the issue?
What were you doing? What steps are required to reproduce?
If you have a project file that helps reproduce the issue, you can update it here as well (you'll need to zip it first)

**Comment by TitusRoy** [comment]
The error message was just suddenly popped up when I was in " Simulation -
Observers " tab.

Even when I was using observers tab a while ago, there was no issue. But
once the error message came, I couldn't accessible to any of the options.

I could help you only with these information.

**Comment by msevestre** [comment]
Unable to reproduce the issue.
