### ISSUE TITLE
Build 63 - error

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/PK-Sim#212]
Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Object reference not set to an instance of an object.

at OSPSuite.Core.Domain.Services.ParameterIdentificationValidator.<>c.<allDataPointWeights>b__5_0(OutputMapping x)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at OSPSuite.Core.Domain.Services.ParameterIdentificationValidator.validateWeights(ParameterIdentification parameterIdentification, ValidationResult validationResult)
   at OSPSuite.Core.Domain.Services.ParameterIdentificationValidator.Validate(ParameterIdentification parameterIdentification)
   at OSPSuite.Core.Domain.Services.EntityValidator.Visit(ParameterIdentification parameterIdentification)
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitMethod[T](IVisitor visitor, T objectToVisit, MethodInfo method)
   at OSPSuite.Utility.Visitor.VisitorInvoker.InvokeVisit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorExtensions.Visit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Core.Domain.ObjectBase.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.ParameterIdentifications.ParameterIdentification.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Services.EntityValidator.<validateEntities>b__6_0(IObjectBase entity)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Services.EntityValidator.validateEntities(IReadOnlyList`1 entities, IReadOnlyList`1 compoundNames)
   at OSPSuite.Core.Domain.Services.EntityValidator.Validate(IObjectBase objectBase)
   at OSPSuite.Presentation.Services.EntityValidationTask.Validate(IObjectBase objectToValidate)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunner.<Run>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext()

*******************************************************************************************************
<img width="971" alt="output" src="https://cloud.githubusercontent.com/assets/27323536/26766203/09566b5a-49d0-11e7-9e80-39ba806e1796.png">

I am trying to add my observed data into the Observed Data tab under Parameter Identification. I am not getting a drop down menu. could you please advice what is the issue.

Kind regards
Chandramouli

**Comment by msevestre** [comment]
@moulirc: Thanks for reporting the issue. Could you please attach your project to the issue as well ( you will need to zip the project in order to attach it). This will help us understand what's going on.

**Comment by msevestre** [comment]
@moulirc Looking at the screenshot, it seems that you have not added the observed data to the simulation. That's why there are no observed data in the drop down menu. You need to drag and drop the observed data from the tree into a simulation chart. This will effectively adds the observed data to the simulation and make the data available in the selection.

We will correct the error message in the next release

**Comment by msevestre** [comment]
Fixes in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/114
