### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2129]
When opening any observed data set and performing right mouse click on the highlighted area: the error below occurs.
![grafik](https://user-images.githubusercontent.com/25061876/159510365-4810401e-08aa-4e80-b618-69fd04f8e581.png)

Application:
PK-Sim® 11.0.0

Cannot find column 2.

Stack trace:
```
at System.Data.DataColumnCollection.get_Item(Int32 index)
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.GetColumnIdFromColumnIndex(Int32 columnIndex)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryDataPresenter.columnFromColumnIndex(Int32 columnIndex)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryDataPresenter.AvailableUnitsFor(Int32 columnIndex)
   at OSPSuite.UI.Binders.UnitsMenuBinder`1.CreateMenuUnits(T identifier, DXPopupMenu menu)
   at OSPSuite.UI.Binders.GridViewColumnUnitsMenuBinder`1.onPopUpMenuShowing(PopupMenuShowingEventArgs e)
   at OSPSuite.UI.Binders.GridViewColumnUnitsMenuBinder`1.<>c__DisplayClass1_0.<.ctor>b__1()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@georgeDaskalakis This is an issue in Core

**Comment by msevestre** [comment]
@georgeDaskalakis Tagging again to make sure you saw this
