### ISSUE TITLE
Cant add simulation into Parameter identification - getting this error. project file attache.

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/PK-Sim#218]
I am trying to add a simulation into Parameter identification and getting this error.

I have also included the project file attached.

kind regards

*****
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes, Int32& version)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.ParameterIdentificationContentLoader.LoadContentFor(ParameterIdentification parameterIdentification)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
[Simulation.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1060550/Simulation.zip)

**Comment by msevestre** [comment]
hi @moulirc 
Optimization is only supported for Individual Simulation at the moment. 

This is the full errror 

Application:
PK-Sim® 7.1.0 - Build 63

Array cannot be null.
Parameter name: bytes

Stack trace:
```
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte) in C:\projects\ospsuite-serializer\src\OSPSuite.Serializer\Xml\XmlHelper.cs:line 29
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\XmlSerializationManager.cs:line 214
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes, Int32& version) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\XmlSerializationManager.cs:line 87
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Serialization\Xml\XmlSerializationManager.cs:line 99
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext) in C:\projects\PK-Sim\src\PKSim.Core\Services\CompressedSerializationManager.cs:line 47
   at PKSim.Infrastructure.Services.ParameterIdentificationContentLoader.LoadContentFor(ParameterIdentification parameterIdentification) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\ParameterIdentificationContentLoader.cs:line 32
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad) in C:\projects\PK-Sim\src\PKSim.Infrastructure\Services\LazyLoadTask.cs:line 49
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0() in C:\projects\PK-Sim\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 31
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Services\HeavyWorkManager.cs:line 97
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Services\HeavyWorkManager.cs:line 62
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
The problem is that the ParameterIdentification is empty and the flag `HasChanged` is set by default to `false`.

**Comment by msevestre** [comment]
We need to ensure that a PI is saved even if it has nothing in it. Very minor bug

**Comment by moulirc** [comment]
Thanks for your clarification.

kind regards
mouli
