### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MouFan1** [Open-Systems-Pharmacology/PK-Sim#2250]
Application:
PK-Sim® 10.0.256

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.ParameterIdentifications.OutputMapping.UsesObservedData(DataRepository observerData)
   at PKSim.Infrastructure.Services.ObservedDataTask.<>c__DisplayClass15_0.<findParameterIdentificationsUsing>b__3(OutputMapping x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PKSim.Infrastructure.Services.ObservedDataTask.<>c__DisplayClass15_0.<findParameterIdentificationsUsing>b__1(<>f__AnonymousType14`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PKSim.Infrastructure.Services.ObservedDataTask.RemoveUsedObservedDataFromSimulation(IReadOnlyList`1 usedObservedDataList)
   at PKSim.Presentation.UICommands.DeleteUsedObservedDataUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
Hi @MouFan1 

Thanks for reporting 
Can you explain what you were doing? Can you reproduce the problem?  Can you attach the project wheee this problem occurred?
It is very hard for us to understand the problem without any context whatsoever

**Comment by finattig** [comment]
Hello,
I am having a similar problem when I try to export results from a simulation to Excel. The message is as follows:

![error_exportexcel](https://user-images.githubusercontent.com/72104369/185808489-f6d430bd-4bd4-4da2-9f58-4d5465032a89.jpg)


Application:


PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.<>c__DisplayClass14_0.<getColumnName>b__0(PivotGridField field)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.getColumnName(PivotGridCells input, Int32 columnIndex)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.configureDataTable(PivotGridCells input, DataTable dt, Func`2 useColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.map(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter, Func`2 shouldUseRow, Func`2 shouldUseColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.MapFrom(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter)
   at OSPSuite.UI.Controls.UxPivotGrid.GetCellsSummary()
   at PKSim.UI.Views.Simulations.PKAnalysisPivotView.GetSummaryData()
   at PKSim.UI.Views.Simulations.IndividualPKAnalysisView.GetSummaryData()
   at PKSim.Presentation.Presenters.Simulations.IndividualPKAnalysisPresenter.ExportToExcel()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Can you attach your project?

**Comment by Yuri05** [comment]
Closing due to inactivity
