### ISSUE TITLE
v11 project will not open after loaded as snapshot from v9 

### ISSUE THREAD

**Issue by jhunt8** [Open-Systems-Pharmacology/PK-Sim#2258]
Loaded project in v11 from v9 snapshot and saved. (Often, a project loaded from snapshot will only save as a "corrupted" 240 KB or 440 KB file unless changes are made to building blocks before saving). Project gives the following error instead of opening:

Application:
PK-Sim® 11.0.150

Array cannot be null.
Parameter name: bytes

Stack trace:
```
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserialize(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<MapFrom>b__6_2(BuildingBlockMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass17_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>g__openProject|0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by Yuri05** [comment]
Where do you save your projects? (on the local drive or on network/remote drive or ...)

**Comment by jhunt8** [comment]
Hi @Yuri05, thank you for the response. Originally the v9, .json, and v11 files were all saved on a remote drive. When the .json file was saved to the hard drive instead, the import was successful. Thank you!
