### ISSUE TITLE
Error message when opening the project

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2264]
When opening the project attached, the error message below comes. [Erythromycin-Model_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9218761/Erythromycin-Model_2.zip)

After that the project is opened and all objects (BBs/Simulations) seems to be there, and the Working Journal is assigned as well

```
Application:
PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Presentation.Presenters.Diagram.BaseDiagramPresenter`3.Refresh()
   at OSPSuite.Presentation.Presenters.Journal.JournalDiagramPresenter.Handle(JournalPageUpdatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by msevestre** [comment]
Can't reproduce. Probably because the working journal is missing in the folder

**Comment by msevestre** [comment]
Can you add it to the issue?

**Comment by Yuri05** [comment]
Attaching the journal
[Journal.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9226058/Journal.zip)

**Comment by msevestre** [comment]
seems to be an issue in core (note the project needs to be under V10 to be loaded)
