### ISSUE TITLE
Application: PK-Sim® 11.0.150  Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by WTY-tt** [Open-Systems-Pharmacology/PK-Sim#2336]
Application:
PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Core.Services.SimulationResultsCreator.valuesFrom(DataColumn dataColumn)
   at PKSim.Core.Services.SimulationResultsCreator.CreateResultsFrom(DataRepository dataRepository)
   at PKSim.Core.Services.SimulationResultsSynchronizer.Synchronize(IndividualSimulation simulation, DataRepository newResults)
   at PKSim.Core.Services.IndividualSimulationEngine.<>c__DisplayClass14_0.<runSimulation>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Services.IndividualSimulationEngine.<RunAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Services.SimulationRunner.<runSimulation>d__10`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.InteractiveSimulationRunner.<RunSimulation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.ExceptionExtensions.<DoWithinExceptionHandler>d__6.MoveNext()
```
[克唑替尼.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9557689/default.zip)

**Comment by msevestre** [comment]
Hey @WTY-tt 
Thanks for reporitng the issue
How do we reproduce the problem? What simulation do we need to run?

**Comment by PavelBal** [comment]
No error with v12.
