### ISSUE TITLE
Parameter optimization error reported

### ISSUE THREAD

**Issue by WTY-tt** [Open-Systems-Pharmacology/PK-Sim#2360]
Application:
PK-Sim® 11.0.150

Values.Length = 10 != 12 = BaseGrid.Count

Stack trace:
```
at OSPSuite.Core.Domain.Data.DataColumn.set_Values(IReadOnlyList`1 value)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.createWeightColumn(BaseGrid baseGrid, WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.MapFrom(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.MapDataTableFromColumns()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.Rebind()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.EditObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataPresenter.Edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.AddObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.<>c__DisplayClass10_0.<addWeightedObservedDataToView>b__0()
   at OSPSuite.Utility.Extensions.LatchableExtensions.DoWithinLatch(ILatchable latchable, Action action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.addWeightedObservedDataToView(List`1 allWeightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationDataSelectionPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.<>c__DisplayClass2_0.<InitializeSubPresentersWith>b__0(IParameterIdentificationItemPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.InitializeSubPresentersWith(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject)
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
Can you attach the project to reproduce the issue?

**Comment by PavelBal** [comment]
Not reproducible without an example.
