### ISSUE TITLE
11.1 Unhandled error when closing empty Residual vs Time plot in a simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2395]
E.g. create a simulation and don't add any observed data.
Click on "Residuals vs. Time" button - empty plot is created.
Close the plot tab - the error below comes
```
Application:
PK-Sim® 11.1.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Chart.CurveChart.RemoveCurvesForColumns(IEnumerable`1 dataColumns)
   at OSPSuite.Core.Chart.CurveChart.RemoveCurvesForDataRepository(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.SimulationResidualVsTimeChartPresenter.Clear()
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.RemoveAnalysis(ISimulationAnalysisPresenter simulationAnalysisPresenter)
   at OSPSuite.UI.Views.EditAnalyzableView.closeButtonClick(ClosePageButtonEventArgs e)
   at OSPSuite.UI.Views.BaseView.<>c__DisplayClass27_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Views.BaseView.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1761](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1761) via [**Zenhub**](https://www.zenhub.com/)
