### ISSUE TITLE
11.1 Unhandled exception in predicted vs observed plot when (only) fraction data is mapped 

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2396]
[02_Alfentanil.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9931077/02_Alfentanil.zip)

In the project attached only a fraction observed data is mapped to a simulation output:
![grafik](https://user-images.githubusercontent.com/25061876/199776870-02749563-53fd-4a5f-b0ea-db4ce6bf8ae6.png)

When trying to create Predicted vs Observed plot - exception below comes
```

Application:
PK-Sim® 11.1.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Core.Services.PredictedVsObservedChartService.setAxisDimension(IDimension dimension, PredictedVsObservedChart chart, Axis axis)
   at OSPSuite.Core.Services.PredictedVsObservedChartService.ConfigureAxesDimensionAndTitle(IReadOnlyList`1 observationColumns, PredictedVsObservedChart chart)
   at OSPSuite.Presentation.Presenters.SimulationPredictedVsObservedChartPresenter.UpdateAnalysis()
   at OSPSuite.Presentation.Presenters.SimulationVsObservedDataChartPresenter`1.UpdateAnalysisBasedOn(IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.Charts.SimulationAnalysisChartPresenter`3.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Handle(SimulationAnalysisCreatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by georgeDaskalakis** [comment]
@Yuri05 this is an interesting error: it does not have to do with the fraction, it has to do with the fact that all the measurements for the observed data are 0. Still there should not be an exception here, but I am not sure what the desired behaviour should be. Let's briefly discuss this today when you have time.

**Comment by Yuri05** [comment]
>but I am not sure what the desired behaviour should be

0 is a valid value for fraction (and in the attached example the simulated fraction is const zero as far as I remember) - so I would expect
* if the axes are in linear scale: the plot with the only point (0,0) 
* if the axes are in log scale - empty plot

**Comment by georgeDaskalakis** [comment]
I would say since this is not an one line change ( the whole issue comes from plotting the identity curve, and 0 values have been till now explicitely filtered out), and it has always been like this plus since it has to do with fraction observed data having exclusively 0 values, my suggestion would be to leave it for now and not to consider it for this versiojn at least.

@Yuri05 @rwmcintosh @msevestre @PavelBal your thoughts on that?

**Comment by Yuri05** [comment]
>my suggestion would be to leave it for now and not to consider it for this versiojn at least.

I can live with it. It is a rather artificial use case

**Comment by PavelBal** [comment]
1) Exception must be caught

2) 
> 0 values have been till now explicitely filtered out

I do not like this at all, on linear scale the 0 values should be considered. In theory even on log scale this should be highlighted somehow. We can skip it for 11.1 but let's not ignore it at all.

**Comment by georgeDaskalakis** [comment]
Again just to make this clear, this is not about filtering something out in presenting the data, but an Observed Data Set having only 0 values:

![image](https://user-images.githubusercontent.com/37107428/201113636-691b8a4a-5ec1-42af-a0d0-26374efb86ab.png)
 
which when having no other dataset plotted results in the rror because the whole data set is filtered out for the deviation line:

![image](https://user-images.githubusercontent.com/37107428/201114212-010151b7-1d7f-4532-b564-92dc0171941f.png)

![image](https://user-images.githubusercontent.com/37107428/201114552-87b78e52-7762-4561-b284-12bdafcc20da.png)


and that was that way already with the PI implementation I would say. Possibly without exception because of the order of identity line creation/ axis adjustment. 

I would guess an empty plot is in order in this case.

**Comment by Yuri05** [comment]
>I would guess an empty plot is in order in this case.

:+1:

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1767](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1767) via [**Zenhub**](https://www.zenhub.com/)
