### ISSUE TITLE
Unhandled exception when trying to load event template during configure simulation if not templates available

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2407]
If I try to load an event template during Create/Configure of the simulation (and I don't have any templates for events), unhandled exception is shown.
PK-Sim does not crash after that, so I can just close the window and continue, but explicite message would be better.
(Happens both in 11.0 and 11.1)

![grafik](https://user-images.githubusercontent.com/25061876/200077214-06850a2b-ca67-4a92-b5fd-274278f8a0b3.png)

```
************** Exception Text **************
PKSim.Core.Services.NoTemplateAvailableException: No template 'Event' available in the template databases.
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplateAsync[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.<LoadFromTemplateAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Services.BuildingBlockTask.<LoadSingleFromTemplateAsync>d__29`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Simulations.SimulationEventsConfigurationPresenter.<LoadEventAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass24_0.<<OnEvent>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

**Comment by msevestre** [comment]
same with observers 

![Uploading image.png…]()

**Comment by AndreDlm** [comment]
In v11.3 I still get the unhandled exception error:
![image](https://github.com/user-attachments/assets/967f05aa-efd1-4402-92c8-9e827cce759b)

**Comment by Yuri05** [comment]
yes, because the issue was fixed in V12 :)
