### ISSUE TITLE
11.1 Error when adding Bioavailability to a Box-Whisker-Plot in the population simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2409]
[test11.1_Alfentanil-Pediatrics.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9942490/test11.1_Alfentanil-Pediatrics.pksim5.zip)
* Open the (only) population simulation
* Click on the Box-Whisker plot in the ribbon bar
* Go to PK-Parameters and expand the "Bioavailability" node (Biovailability was calculated before in the simulation)
![grafik](https://user-images.githubusercontent.com/25061876/200088917-599b4a28-3084-4a35-8c77-8c264aa21d82.png)

The error message below comes

```
Application:
PK-Sim® 11.1.0

Object reference not set to an instance of an object.

Stack trace:

at PKSim.Core.Services.DistributionDataCreator.<>c__DisplayClass11_0.<CreateFor>b__0(Double value) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\DistributionDataCreator.cs:line 85
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PKSim.Core.Services.DistributionDataCreator.CreateFor(IVectorialParametersContainer parameterContainer, DistributionSettings settings, IReadOnlyList`1 values, IDimension dimension, Unit displayUnit) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\DistributionDataCreator.cs:line 85
   at PKSim.Core.Services.DistributionDataCreator.CreateFor(IPopulationDataCollector populationDataCollector, DistributionSettings settings, QuantityPKParameter parameter, IDimension dimension, Unit displayUnit) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Core\Services\DistributionDataCreator.cs:line 49
   at PKSim.Presentation.Presenters.Populations.PopulationDistributionPresenter.plot[TObjectToPlot,TVectorialParametersContainer](TVectorialParametersContainer populationDataCollector, TObjectToPlot objectToPlot, Func`6 distributionCreator, Action`3 updatePlotOptionAction, DistributionSettings settings, IDimension dimension, Unit displayUnit) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\Populations\PopulationDistributionPresenter.cs:line 83
   at PKSim.Presentation.Presenters.Populations.PopulationDistributionPresenter.Plot(IPopulationDataCollector populationDataCollector, QuantityPKParameter pkParameter, DistributionSettings settings, IDimension dimension, Unit displayUnit) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\Populations\PopulationDistributionPresenter.cs:line 72
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisFieldDistributionPresenter.plotContinousData[TObject](IPopulationDataCollector populationDataCollector, TObject objectToPlot, INumericValueField numericValueField, Func`2 plotFunc) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\PopulationAnalyses\PopulationAnalysisFieldDistributionPresenter.cs:line 104
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisFieldDistributionPresenter.Plot(IPopulationDataCollector populationDataCollector, QuantityPKParameter pkParameter, PopulationAnalysisPKParameterField pkParameterField) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\PopulationAnalyses\PopulationAnalysisFieldDistributionPresenter.cs:line 62
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisPKParameterSelectionPresenter.drawDistributionFor(QuantityPKParameter pkParameter, PopulationAnalysisPKParameterField populationAnalysisPKParameterField) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\PopulationAnalyses\PopulationAnalysisPKParameterSelectionPresenter.cs:line 52
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisPKParameterSelectionPresenter.<.ctor>b__2_1(Object o, PKParameterSelectedEventArgs e) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\PopulationAnalyses\PopulationAnalysisPKParameterSelectionPresenter.cs:line 40
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisAvailablePKParametersPresenter.QuantityPKParameterSelected(QuantityPKParameterDTO quantityPKParameterDTO) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\PopulationAnalyses\PopulationAnalysisAvailablePKParametersPresenter.cs:line 97
   at PKSim.UI.Views.PopulationAnalyses.PopulationAnalysisAvailablePKParametersView.gridViewRowChanged(FocusedRowChangedEventArgs e) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.UI\Views\PopulationAnalyses\PopulationAnalysisAvailablePKParametersView.cs:line 45
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment]
Same in Scatter/Range Plots
