### ISSUE TITLE
Importing observed data crash

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2417]

**Comment by PavelBal** [comment]
[pksim-2417-importerCrash.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9972230/pksim-2417-importerCrash.zip)

Trying to import with the provided excel file and configuration (accept that some columns cannot be mapped):

Application:
PK-Sim® 11.1.78

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.parseMappingOnSameGivenColumn(MappingDataFormatParameter currentParameter, DataSheet dataSheet, UnformattedRow row)
   at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.<>c__DisplayClass27_2.<parseMappings>b__1(UnformattedRow row)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.parseMappings(IEnumerable`1 rawDataSet, DataSheet dataSheet, Cache`2 columnInfos)
   at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.<>c__DisplayClass26_0.<buildDataSets>b__0(List`1 rows)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at OSPSuite.Infrastructure.Import.Core.DataSet.AddData(IEnumerable`1 range)
   at OSPSuite.Infrastructure.Import.Core.DataSheetCollection.GetDataSets(IDataFormat format, ColumnInfoCache columnInfos)
   at OSPSuite.Infrastructure.Import.Services.Importer.AddFromFile(IDataFormat format, DataSheetCollection dataSheets, ColumnInfoCache columnInfos, IDataSource alreadyExisting)
   at OSPSuite.Infrastructure.Import.Core.DataSource.AddSheets(DataSheetCollection dataSheets, ColumnInfoCache columnInfos, String filter)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.loadSheets(IDataSourceFile dataSourceFile, IReadOnlyList`1 sheetNames, String filter, String selectedNamingConvention)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.loadSheetsFromDataPresenter(Object sender, ImportSheetsEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.ImportDataForConfirmation(String sheetName)
   at OSPSuite.UI.Views.Importer.ImporterDataView.onButtonImportClicked(Object sender, EventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by georgeDaskalakis** [comment]
@PavelBal the whole issue comes from the lloq of the "Measurement" being mapped to the "LLOQ" excel column in the configuration. In the given excel such a column does not exist. I am fixing this check in code, but just till then a workaround is to manually correct the LLOQ mapping after applying the configuration.

**Comment by georgeDaskalakis** [comment]
@PavelBal @Yuri05 @msevestre @rwmcintosh regarding the fix of this:

The LLOQ mapping will not be automatically cleared when applying the configuration, but we are going to notify the user about the non existent "LLOQ" excel-column when he is trying to load the sheet - then he should have the chance to clear that mapping himself.

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1822](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1822) via [**Zenhub**](https://www.zenhub.com/)
