### ISSUE TITLE
Major Issue: Cannot run Population in QualificationRunner

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2427]
It looks like this guy
 `OSPSuite.Core.Domain.Services.PopulationSimulationPKAnalysesToDataTableConverter` probably has a problem. I am assuming this is with the parameters that were added to the population simulation

How to reproduce for now

Get the CKD Workflow from msevestre/CKD-Qualification

from the QualificationRunner, run

QualificationRunner.exe -i C:/dev/CKD-Qualification/input/CKD_rough.json -o C:/dev/CKD-Qualification/re_input --pksim C:/dev/PK-Sim/src/PKSim/bin/Debug/net472 -f

```
Stack trace:
at OSPSuite.Core.Domain.Services.PopulationSimulationPKAnalysesToDataTableConverter.PKAnalysesToDataTable(PopulationSimulationPKAnalyses pkAnalyses, IModelCoreSimulation simulation)
   at OSPSuite.Core.Domain.Services.PopulationSimulationPKAnalysesToDataTableConverter.<>c__DisplayClass3_0.<PKAnalysesToDataTableAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Infrastructure.Services.SimulationExportTask.<ExportPKAnalysesToCSVAsync>d__26.MoveNext() in C:\dev\PK-Sim\src\PKSim.Infrastructure\Services\SimulationExportTask.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.CLI.Core.Services.SimulationExporter.<exportPopulationSimulationResultsToCsvAsync>d__13.MoveNext() in C:\dev\PK-Sim\src\PKSim.CLI.Core\Services\SimulationExporter.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.CLI.Core.Services.ExportSimulationRunner.<ExportSimulation>d__9.MoveNext() in C:\dev\PK-Sim\src\PKSim.CLI.Core\Services\ExportSimulationRunner.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.CLI.Core.Services.ExportSimulationRunner.<ExportSimulationsIn>d__8.MoveNext() in C:\dev\PK-Sim\src\PKSim.CLI.Core\Services\ExportSimulationRunner.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.CLI.Core.Services.QualificationRunner.<RunBatchAsync>d__10.MoveNext() in C:\dev\PK-Sim\src\PKSim.CLI.Core\Services\QualificationRunner.cs:line 114
 --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command) in C:\dev\PK-Sim\src\PKSim.CLI\Program.cs:line 53 
```

**Comment by Yuri05** [comment]
>I am assuming this is with the parameters that were added to the population simulation

You mean new PK parameters in popsim?

**Comment by msevestre** [comment]
@rwmcintosh 

I can reproduce with the following steps

1. Load the attached project
2. Go to simulation and export pk analysis to csv
![image](https://user-images.githubusercontent.com/1041237/201699702-28c11663-6202-4b2a-9d60-828679de7d9f.png)

Crash

Application:
PK-Sim® 11.1.0

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.Services.PopulationSimulationPKAnalysesToDataTableConverter.PKAnalysesToDataTable(PopulationSimulationPKAnalyses pkAnalyses, IModelCoreSimulation simulation)
   at OSPSuite.Core.Domain.Services.PopulationSimulationPKAnalysesToDataTableConverter.<>c__DisplayClass3_0.<PKAnalysesToDataTableAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Infrastructure.Services.SimulationExportTask.<ExportPKAnalysesToCSVAsync>d__26.MoveNext() in C:\dev\PK-Sim\src\PKSim.Infrastructure\Services\SimulationExportTask.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Infrastructure.Services.SimulationExportTask.<exportToFileAsync>d__28.MoveNext() in C:\dev\PK-Sim\src\PKSim.Infrastructure\Services\SimulationExportTask.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.ExceptionExtensions.<DoWithinExceptionHandler>d__6.MoveNext()
```

**Comment by msevestre** [comment]
[2427.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10004479/2427.zip)

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1783](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1783) via [**Zenhub**](https://www.zenhub.com/)
