### ISSUE TITLE
Error when exporting to Excel

### ISSUE THREAD

**Issue by cfahner** [Open-Systems-Pharmacology/PK-Sim#2440]
Whenever I try to export to Excel from a Simulation, I get the error pasted below.

Application:
PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.<>c__DisplayClass14_0.<getColumnName>b__0(PivotGridField field)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.getColumnName(PivotGridCells input, Int32 columnIndex)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.configureDataTable(PivotGridCells input, DataTable dt, Func`2 useColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.map(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter, Func`2 shouldUseRow, Func`2 shouldUseColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.MapFrom(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter)
   at OSPSuite.UI.Controls.UxPivotGrid.GetCellsSummary()
   at PKSim.UI.Views.Simulations.PKAnalysisPivotView.GetSummaryData()
   at PKSim.UI.Views.Simulations.IndividualPKAnalysisView.GetSummaryData()
   at PKSim.Presentation.Presenters.Simulations.IndividualPKAnalysisPresenter.ExportToExcel()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by cfahner** [comment]
I have attached screenshots and the relevant project file (inside the zip-file). It happens when I try to export the PK analysis to Excel with the button visible in the screenshots.

[Metoprolol.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10084071/Metoprolol.zip)

![Screenshot from 2022-11-24 12-29-22](https://user-images.githubusercontent.com/3216275/203773771-9693dcfc-5054-4c5b-be0b-5eea3bb9d474.png)

![Screenshot from 2022-11-24 12-27-29](https://user-images.githubusercontent.com/3216275/203773773-0de72b9c-44bd-4bb4-8487-c0c4798712c6.png)

**Comment by Yuri05** [comment]
Thank you. In you project is reproducible

**Comment by Yuri05** [comment]
@cfahner It seems that the problem is that you observed datasets arenot assigned to a molecule (compound).
In PK-Sim, it's always recommended to assign the molecule during the data import process (either via calling **Add Observed Data for** and then selecting one of the project compounds or by assigning a molecule during the data import process).

You can also assign a molecule afterwards. For that, open you observed data set for editing, click on **Add meta data**, 
name the new meta data **Molecule** and enter the name of the molecule
![grafik](https://user-images.githubusercontent.com/25061876/203804767-cbbbb541-e26f-4f43-bce0-22c53a9c6f86.png)

After that you will see e.g. that the mol weight is locked (because now it is bound to the MW of the molecule):
![grafik](https://user-images.githubusercontent.com/25061876/203805098-4962f55c-2e6e-4bf9-8932-92e231a188c9.png)

After this change was done, click once on "Hide PK Analysis" (if it was shown during the meta data change) and again on "Show PK Analysis" - you will see that you observed data is now assigned to the selected molecule:
![grafik](https://user-images.githubusercontent.com/25061876/203811965-8b5ce7e5-24df-489c-9017-a5c2beec5c0f.png)

Now when you export - it should work.

**Comment by cfahner** [comment]
Yes it works, thanks a lot!

I would still suggest implementing some informational popup if this occurs, since it is hard to keep track of all these kinds of settings sometimes if you work in multiple projects with multiple datasets. Might be less confusing for the next person to make this mistake.

**Comment by msevestre** [comment]
Yes absolutely. The application should never crash like this

**Comment by msevestre** [comment]
Ok this is is something that was never possible before the Excel Improter change. I guess we are allowing it now @Yuri05 ?
