### ISSUE TITLE
error when trying to export to excel

### ISSUE THREAD

**Issue by Fate-afshar** [Open-Systems-Pharmacology/PK-Sim#2443]
Dear all,
I've been having some trouble trying to export my project to excel . when I click on my desired chart it gives an error exclaiming : 

The workbook already contains a sheet named 'actual time.Sheet1.vancomycin_10'

Stack trace:
```
at NPOI.XSSF.UserModel.XSSFWorkbook.ValidateSheetName(String sheetName)
   at NPOI.XSSF.UserModel.XSSFWorkbook.CreateSheet(String sheetname)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.exportDataTableToWorkBook(IWorkbookConfiguration workBookConfiguration, DataTable dataTable)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, IWorkbookConfiguration workBookConfiguration)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataTables, String fileName, Boolean launchExcel)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataColumns, String fileName, Boolean launchExcel, DataColumnExportOptions exportOptions)
   at OSPSuite.Core.Services.CurveChartExportTask.ExportToExcel(CurveChart chart)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.ExportToExcel()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

I'd appreciate your help
thank you

**Comment by msevestre** [comment]
@Fate-afshar Can you attach your project file here?

**Comment by Fate-afshar** [comment]
sure. 
I'm having this problem with parameter identification 13 and 14 
[export error.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10101934/export.error.zip)

the rest seem to be working 
not sure why

**Comment by msevestre** [comment]
this has to do with the # in the name of the observed data
