### ISSUE TITLE
simulations error

### ISSUE THREAD

**Issue by neutro-jina** [Open-Systems-Pharmacology/PK-Sim#2446]
Application:
PK-Sim® 11.0.150

could not execute query
[ select metadataco1_.Id as id1_19_, metadataco1_.Data as data2_19_ from BUILDING_BLOCKS buildingbl0_ inner join CONTENTS metadataco1_ on buildingbl0_.ContentId=metadataco1_.Id where buildingbl0_.Id=@p0 ]
  Name:id - Value:IL62UlSIvESETAG4EEEq_Q
[SQL: select metadataco1_.Id as id1_19_, metadataco1_.Data as data2_19_ from BUILDING_BLOCKS buildingbl0_ inner join CONTENTS metadataco1_ on buildingbl0_.ContentId=metadataco1_.Id where buildingbl0_.Id=@p0]
-----------------------------------------------------
SQL logic error
no such table: BUILDING_BLOCKS

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
 --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Impl.AbstractQueryImpl.UniqueResult[T]()
   at PKSim.Infrastructure.Serialization.ORM.Queries.MetaDataContentQuery.ResultFor(String objectId)
   at PKSim.Infrastructure.Services.ContentLoader.LoadContentFor[T](T objectToLoad)
   at PKSim.Infrastructure.Services.LazyLoadTask.loadObjectBase[T](T objectToLoad)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
What are you trying to do? Or Load? We'll need some help to be able to reproduce the problem.
Do you have a project file that you could share?
