### ISSUE TITLE
Populationsimulation cannot be compared if ' is used in Simulation Name

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#245]
e.g. using "Karrash '04" in Simulation name and comparing POP-Sim using Simulation Name was not possible and through exception. Workaround: rename Simulation to e.g. "Karrash 04" worked without problems

**Comment by msevestre** [comment]
Would you please paste the exception for further reference? (use the copy to clipboard button). Thanks )

**Comment by tobiasK2001** [comment]
Syntax error: Missing operand after '96' operator.

Stack trace:
at System.Data.ExpressionParser.Parse()
   at System.Data.DataExpression..ctor(DataTable table, String expression, Type type)
   at System.Data.DataTable.Select(String filterExpression)
   at BTS.Utility.Data.Pivoter.getData(DataView data, String filter, String dataField, Aggregate aggregate)
   at BTS.Utility.Data.Pivoter.pivotDataFlat(DataView data, PivotInfo pivotInfo)
   at BTS.Utility.Data.Pivoter.PivotData(DataView data, PivotInfo pivotInfo)
   at (Object , DataView , PivotInfo )
   at A.KR.A(Object A, DataView B, PivotInfo C)
   at PKSim.Core.Services.PivotResultCreator.Create(PopulationPivotAnalysis pivotAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.ChartDataCreator`2.CreateResult[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.TimeProfileChartDataCreator.CreateResult[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.ChartDataCreator`2.CreateFor[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Presentation.Presenters.PopulationAnalyses.TimeProfileAnalysisResultsPresenter.CreateChartData()
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisResultsPresenter`5.RefreshChart()
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisResultsPresenter`5.handle(PopulationAnalysisEvent eventToHandle)
   at PKSim.Presentation.Presenters.PopulationAnalyses.PopulationAnalysisResultsPresenter`5.Handle(FieldsMovedInPopulationAnalysisEvent eventToHandle)
   at BTS.Utility.Events.EventPublisher.<>c__DisplayClass4_0`1.<PublishEvent>b__1()
   at BTS.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)

**Comment by tobiasK2001** [comment]
hope this might help you.

**Comment by msevestre** [comment]
absolutely. That way we know exactly what component is causing the issue. Thanks

**Comment by msevestre** [comment]
Solution:
Either forbid `'` in name or ensure that sql expressions are escaped properly

**Comment by tobiasK2001** [comment]
Yes fixed. Check With PKsim 7.3.0 portable
