### ISSUE TITLE
Importing observed data chrash (2)

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2451]
[pksim-importerCrash.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10125377/pksim-importerCrash.zip)

- Open the excel file
- Load the provided configuration
- "Add all sheets"

Application:
PK-Sim® 11.1.78

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Infrastructure.Import.Core.DataSource.<>c__DisplayClass21_1.<validateUnitsSupportedAndSameDimension>b__2(IDimension x)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Infrastructure.Import.Core.DataSource.validateUnitsSupportedAndSameDimension(Cache`2 columnInfos)
   at OSPSuite.Infrastructure.Import.Core.DataSource.ValidateDataSourceUnits(ColumnInfoCache columnInfos)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.validateDataSource(IDataSource dataSource)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.loadSheets(IDataSourceFile dataSourceFile, IReadOnlyList`1 sheetNames, String filter, String selectedNamingConvention)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.loadSheetsFromDataPresenter(Object sender, ImportSheetsEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.ImportDataForConfirmation()
   at OSPSuite.UI.Views.Importer.ImporterDataView.onButtonImportAllClicked(Object sender, EventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
This happens for the sheet `Crew2001`. The error is "Arithmetic" but the error unit column is empty. It is correct that the sheet cannot be imported, but it should not crash.

**Comment by msevestre** [comment]
Yep. This app should never crash

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1837](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1837) via [**Zenhub**](https://www.zenhub.com/)
