### ISSUE TITLE
Increase project version?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2487]
In general, 11,1 projects can be opened and run in 11.0 without problems.
However, if we have e.g. a GOF chart in a simulation and try to open this simulation in 11.0, the error below comes:

```
Application:
PK-Sim® 11.0.150

Unable to find a serializer for 'OSPSuite.Core.Domain.ISimulationAnalysis'

Stack trace:

at OSPSuite.Serializer.Xml.XmlSerializerRepository`1.SerializerFor(Type typeOfObjectToSerialize)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.resolveSerializer(Type typeOfObject, XElement element)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.SimulationChartsLoader.mapFrom(SimulationChartMetaData chart)
   at PKSim.Infrastructure.Services.SimulationChartsLoader.<>c__DisplayClass4_0.<LoadChartsFor>b__0(SimulationChartMetaData chart)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Services.SimulationChartsLoader.LoadChartsFor(Simulation simulation)
   at PKSim.Infrastructure.Services.LazyLoadTask.loadSimulations(Simulation simulation)
   at PKSim.Infrastructure.Services.LazyLoadTask.loadObjectBase[T](T objectToLoad)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

Should we increase the project version in 11.0?

~And to be more robust for the future: should we just produce a warning and not an error in such a case and continue loading the simulation?~ EDIT: it's already the case

**Comment by Yuri05** [comment]
@msevestre @georgeDaskalakis @rwmcintosh

**Comment by Yuri05** [comment]
Update: I was a bit too fast: after I click on OK in the error message, the simulation opens in 11.0 and shows everything except the new GOF plots.

**Comment by msevestre** [comment]
Hum ...I feel that we should still update the version if it's nos compatible

**Comment by msevestre** [comment]
Hum no. Think about it, we need to add converter that do nothing. Too much work for an edge case
