### ISSUE TITLE
11.1 Cannot run population simulations imported from pkml

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2516]
Seems population simulations which were imported from pkml cannot be run anymore
e.g. open the project **P2** and try to run the simulation S2
[P2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10465818/P2.zip)

```

Application:
PK-Sim® 11.1.131

Object reference not set to an instance of an object.

Stack trace:

at PKSim.Core.Services.PKAnalysesTask.calculateGlobalPKAnalysisFor(Simulation simulation, Compound compound, DataColumn peripheralVenousBloodCurve, DataColumn venousBloodCurve, DataColumn fractionAbsorbedCurve, PKCalculationOptions options, Int32 individualId, CompoundPKContext compoundPKContext)
   at PKSim.Core.Services.PKAnalysesTask.calculateGlobalPKParameters(PopulationSimulation simulation, Int32 individualId, String moleculeName, PKCalculationOptions calculationOptions, CompoundPKContext compoundPKContext)
   at PKSim.Core.Services.PKAnalysesTask.<>c__DisplayClass17_1.<CalculateFor>b__1(Int32 individualId, PKCalculationOptions options, String compoundName)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.<>c__DisplayClass6_1.<CalculateFor>b__0(IndividualResults results)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.scaledIndividualIteration(IModelCoreSimulation simulation, SimulationResults simulationResults, Action`1 performIndividualScalingAction, String moleculeName, PKCalculationOptions pkCalculationOptions, IReadOnlyList`1 allApplicationParameters, Action`1 actionToPerform)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.CalculateFor(IModelCoreSimulation simulation, SimulationResults runResults, Action`1 performIndividualScalingAction, Action`3 calculateAppSpecificPKAnalysis)
   at PKSim.Core.Services.PKAnalysesTask.CalculateFor(PopulationSimulation populationSimulation, CompoundPKContext compoundPKContext)
   at PKSim.Core.Services.SimulationResultsSynchronizer.Synchronize(PopulationSimulation populationSimulation, SimulationResults newResults)
   at PKSim.Core.Services.PopulationSimulationEngine.<RunAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Services.SimulationRunner.<runSimulation>d__10`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Services.InteractiveSimulationRunner.<RunSimulation>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.ExceptionExtensions.<DoWithinExceptionHandler>d__6.MoveNext()
```

(Simulation S2 was created by importing simulation S1 to pkml and then reimporting the pkml as POP simulation and combining it withe the population building block POP from the project)

![grafik](https://user-images.githubusercontent.com/25061876/213685290-7f3c0523-04f0-4376-aa45-c9c357118f57.png)

**Comment by Yuri05** [comment]
Another example for testing:
[POP_MiniModel.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10465948/POP_MiniModel.zip)

**Comment by rwmcintosh** [comment]
Something is wrong in the configuration of the simulation. There are no compounds (nor any other building blocks) in S2. See the view compared to S1

![image](https://user-images.githubusercontent.com/261477/213689822-e3e048e5-12f4-4859-833b-676c0837eb7c.png)

**Comment by Yuri05** [comment]
It's because the simulation was imported from pkml and not created from PK-Sim BBs.
Such simulations never have any PK-Sim BBs

**Comment by rwmcintosh** [comment]
Yeah, most likely easy.
