### ISSUE TITLE
Build-63 error - Admin protocol creation

### ISSUE THREAD

**Issue by nmidde** [Open-Systems-Pharmacology/PK-Sim#253]
![image](https://user-images.githubusercontent.com/29755212/29038886-31cac134-7b77-11e7-8910-cad493e72597.png)

Application:
PK-Sim® 7.1.0 - Build 63

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
```
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartData.createDataToPlot()
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartData..ctor(ICache`2 allSchemaItemDTO, IDimension timeDimension, Unit timeUnit, Double endTimeInMin)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartPresenter.dataToPlotFrom(ICache`2 protocols, Unit timeUnit)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartPresenter.PlotProtocols(ICache`2 protocols)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartPresenter.PlotProtocol(Protocol protocol)
   at PKSim.Presentation.Presenters.Protocols.CreateProtocolPresenter.refreshPlot()
   at PKSim.Presentation.Presenters.Protocols.CreateProtocolPresenter.subPresenterChanged(Object sender, EventArgs eventArgs)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OSPSuite.Presentation.Presenters.AbstractPresenter`2.OnStatusChanged(Object sender, EventArgs e)
   at OSPSuite.Presentation.Presenters.AbstractPresenter`2.OnStatusChanged()
   at OSPSuite.Presentation.Presenters.AbstractCommandCollectorPresenter`2.AddCommand(ICommand command)
   at PKSim.Presentation.Presenters.Protocols.AdvancedProtocolPresenter.AddCommand(ICommand commandToAdd)
   at PKSim.Presentation.Presenters.Protocols.ProtocolItemPresenter`2.SetParameterValue(IParameterDTO parameterDTO, Double newValue)
   at PKSim.UI.Views.Protocols.AdvancedProtocolView.<>c__DisplayClass22_0.<setParameterValue>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Thanks for the big report.

Would you let us know what you were trying to do? A step by step
instructions on how to reproduce the issue would be very helpful

Thanks again

**Comment by nmidde** [comment]
Hello Michael,
Thanks for your quick response. I was trying to create an infusion
administration protocol with a loading dose and continuous infusion. When I
was trying change the value in 'Number of Repetitions' from 1 or 0 I was
getting this error.

This is what I was trying to capture 'Aminophylline, 7 mg/kg, was
administered via a Harvard infusion pump over 20 minutes, followed by
continuous infusion of 0.65 mg/kg per hour for at least 24 hours'.

Thank you,
Narasimha Midde

**Comment by rwmcintosh** [comment]
As far as I understood the instructions I was not able to reproduce that. Can you put a screenshot of your Administration Protocol dialog?

**Comment by nmidde** [comment]
![image](https://user-images.githubusercontent.com/29755212/29043571-b0b5ea7a-7b89-11e7-80bd-1ebc2c835c22.png)
Here it is..

**Comment by rwmcintosh** [comment]
I see, I think your number of repetitions should be 1 in this case. The value 1 means single administration (as in only once without repeating).

The bug here is that the value 0 should not result in this error message.
