### ISSUE TITLE
Developer version: Load compound from Snapshot error

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2535]
When trying to load a compound from snapshot into a project where a compound with the same name exist:

Application:
PK-Sim® 11.1.137

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Presentation.Services.BuildingBlockTask.BuildingBlockNameIsAlreadyUsed(IPKSimBuildingBlock buildingBlock)
   at PKSim.Presentation.Services.BuildingBlockTask.RenameBuildingBlockIfAlreadyUsed(IPKSimBuildingBlock buildingBlock)
   at PKSim.Presentation.Services.BuildingBlockTask.AddToProject[TBuildingBlock](TBuildingBlock buildingBlock, Boolean editBuildingBlock, Boolean addToHistory)
   at PKSim.Presentation.Services.BuildingBlockTask.<addBuildingBlocksToProject>b__32_0[TBuildingBlock](TBuildingBlock bb)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PKSim.Presentation.Services.BuildingBlockTask.LoadFromSnapshot[TBuildingBlock](PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromSnapshot(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromSnapshot()
   at PKSim.Presentation.UICommands.LoadBuildingBlockFromSnapshotUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

I would expect a "Renam"-dialog.

**Comment by msevestre** [comment]
I would expect no crash lol
But this feature is only available in dev mode right?

**Comment by PavelBal** [comment]
Yes only in dev... I would gladly see this in "normal" mode, too :)

**Comment by Yuri05** [comment]
@PavelBal BBs can be loaded from snapshot now (without dev mode) in v13. Can the issue be closed now?
