### ISSUE TITLE
Export to Excel button (on Time Profile Analysis) returned error

### ISSUE THREAD

**Issue by RajFer** [Open-Systems-Pharmacology/PK-Sim#2562]
Application:
PK-Sim® 11.1.137

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.<>c__DisplayClass14_0.<getColumnName>b__0(PivotGridField field)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.getColumnName(PivotGridCells input, Int32 columnIndex)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.configureDataTable(PivotGridCells input, DataTable dt, Func`2 useColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.map(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter, Func`2 shouldUseRow, Func`2 shouldUseColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.MapFrom(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter)
   at OSPSuite.UI.Controls.UxPivotGrid.GetCellsSummary()
   at PKSim.UI.Views.Simulations.PKAnalysisPivotView.GetSummaryData()
   at PKSim.UI.Views.Simulations.IndividualPKAnalysisView.GetSummaryData()
   at PKSim.Presentation.Presenters.Simulations.IndividualPKAnalysisPresenter.ExportToExcel()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
@RajFer  Thanks for reporting
Can you attach a project to reproduce ?

**Comment by FishinW** [comment]
Hi, Michael. I encounter the same error when I tried to export the PK result of simulation. The time-concentration profile can be export successfully. However, the error occur when I export the PK analysis result. I attached the project file.

Application:
PK-Sim® 11.2.142

Object reference not set to an instanc
[Error File.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/14600007/Error.File.zip)
e of an object.

Stack trace:
```
at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.<>c__DisplayClass14_0.<getColumnName>b__0(PivotGridField field)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.getColumnName(PivotGridCells input, Int32 columnIndex)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.configureDataTable(PivotGridCells input, DataTable dt, Func`2 useColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.map(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter, Func`2 shouldUseRow, Func`2 shouldUseColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.MapFrom(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter)
   at OSPSuite.UI.Controls.UxPivotGrid.GetCellsSummary()
   at PKSim.UI.Views.Simulations.PKAnalysisPivotView.GetSummaryData()
   at PKSim.UI.Views.Simulations.IndividualPKAnalysisView.GetSummaryData()
   at PKSim.Presentation.Presenters.Simulations.IndividualPKAnalysisPresenter.ExportToExcel()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by FishinW** [comment]
Hi, Michael. I encounter the same error when I tried to export the PK result of simulation. The time-concentration profile can be export successfully. However, the error occur when I export the PK analysis result. I found that the PK analysis result can be exported when the observation was not added to the simulation, while fail when the observation was added.

I attached the project file for your information.

Application:
[Error File.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/14600163/Error.File.zip)

PK-Sim® 11.2.142

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.<>c__DisplayClass14_0.<getColumnName>b__0(PivotGridField field)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.getColumnName(PivotGridCells input, Int32 columnIndex)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.configureDataTable(PivotGridCells input, DataTable dt, Func`2 useColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.map(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter, Func`2 shouldUseRow, Func`2 shouldUseColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.MapFrom(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter)
   at OSPSuite.UI.Controls.UxPivotGrid.GetCellsSummary()
   at PKSim.UI.Views.Simulations.PKAnalysisPivotView.GetSummaryData()
   at PKSim.UI.Views.Simulations.IndividualPKAnalysisView.GetSummaryData()
   at PKSim.Presentation.Presenters.Simulations.IndividualPKAnalysisPresenter.ExportToExcel()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```
