### ISSUE TITLE
Cannot load observe data in the course of Scaling Across Species

### ISSUE THREAD

**Issue by FishinW** [Open-Systems-Pharmacology/PK-Sim#2566]
Application:
PK-Sim® 11.1.137

Don't know how to build curve binder for 'Invalid'

Stack trace:
```
at OSPSuite.UI.Services.CurveBinderFactory.CreateFor(Curve curve, Object chartControl, CurveChart chart, IAxisBinder yAxisBinder)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.getOrCreateCurveBinderFor(Curve curve)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.refreshCurveBinderFor(Curve curve)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.updateCurves()
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.updateChart()
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.Edit(CurveChart chart, ChartFontAndSizeSettings displayChartFontAndSizeSettings)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.Edit(CurveChart chart)
   at OSPSuite.Presentation.Presenters.Charts.SimpleChartPresenter.bindToChart()
   at OSPSuite.Presentation.Presenters.Charts.SimpleChartPresenter.PlotObservedData(IEnumerable`1 observedData)
   at OSPSuite.Presentation.Presenters.Charts.SimpleChartPresenter.PlotObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryChartPresenter.plotObservedData(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryChartPresenter.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.<>c__DisplayClass8_0.<Edit>b__0(IDataRepositoryItemPresenter presenter)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.Edit(DataRepository repositoryToEdit)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject)
   at PKSim.Presentation.UICommands.EditSubjectUICommand`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```
[Data.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/11010533/Data.xlsx)

**Comment by msevestre** [comment]
Hi there,

Thanks for reporting this issue
Can you let us know how to reproduce the problem? Just loading the file is enough? Or do we need to do something special with the observed data to trigger the problem?

Thanks

**Comment by FishinW** [comment]
Just loading the file and as follow the instrument in the chapter of BUILDING BLOCKS: HUMAN of Scaling Across Species is enough.
First, I load the file named species_extropolation_4 in this chapter. Then I just follow the guidance to build the Individual and Administration Protocol of Human. Until this step, everything work normal. And then I try to load the observe data following the step in the website, PK-Sim report error.

**Comment by FishinW** [comment]
Just loading the file and as follow the instrument in the chapter of BUILDING BLOCKS: HUMAN of Scaling Across Species is enough.
First, I load the file named species_extropolation_4 in this chapter. Then I just follow the guidance to build the Individual and Administration Protocol of Human. Until this step, everything work normal. And then I try to load the observe data following the step in the website, PK-Sim report error.

**Comment by msevestre** [comment]
Can you save the project until the step where everything is normal and attached it here as well?
What chapter are you talking about? Can you copy the url please?

**Comment by FishinW** [comment]
The URL is https://learn-esqlabs.talentlms.com/unit/view/id:4563
I tried the instrument again and successfully load the observe data this time !
It might because I didn't adjust the _Mapping Setting_ correctly before.
The _Mapping Setting_ should look like this 
![image](https://user-images.githubusercontent.com/128284693/226179395-186dfb92-9751-4b29-96fc-88e3cf48563f.png)
But last time I didn't adjust the _Error_ correctly
![image](https://user-images.githubusercontent.com/128284693/226180368-674ae26a-53a1-485a-be4a-3ca47306a6c6.png)

Thanks for your help !

**Comment by msevestre** [comment]
It still should not crash 🙂

**Comment by msevestre** [comment]
@georgeDaskalakis can you check this out maybe? Looks like omitting a settings crashes the app?

**Comment by PavelBal** [comment]
@georgeDaskalakis Yes definitely should not crash... Try it out with the latest nightly first, I think we had something similar and fixed it.

**Comment by PavelBal** [comment]
@georgeDaskalakis Please create an issue on MOnday.com for this so we don't forget it...

**Comment by georgeDaskalakis** [comment]
@msevestre @PavelBal I reproduced this (and also added it to our monday board). Working on it - this should be a quick fix actually.

**Comment by georgeDaskalakis** [comment]
@msevestre @PavelBal @Yuri05 

The issue occurs when the user newly mapps an Error column where the unit is mapped automatically (from the column name fe) but the Standard Deviation remains undefined. 

I would propose in the case we have a unit automatically assigned  to also automatically set the Standard Deviation to Arithmetic. If there is no objections I will implement it like that.

Alternatively we could really just invalidate the error in that case - but I see this as a worse choice from the users perspective.

**Comment by PavelBal** [comment]
> I would propose in the case we have a unit automatically assigned to also automatically set the Standard Deviation to Arithmetic. If there is no objections I will implement it like that.

I agree. However it should be still possible to change the error type to geometric afterwards.

**Comment by georgeDaskalakis** [comment]
Yes of course, this would be just the automatic mapping in the beginning - changing this to whatever the user wants is still always gonna be possible.

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1931](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1931) via [**Zenhub**](https://www.zenhub.com/)
