### ISSUE TITLE
Updating the reference concentration of an enzyme (not distributed) in a population simulation produces error message

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#2568]
I created a population with UGT2B15 (database query) which comes without a distribution from the PK-Sim database and used this population in a population simulation. After running the population simulation, I wanted to overwrite the UGT2B15 reference concentration in the population simulation.
First of all, unlike distributed parameter, it can be only found under parameters when switching to hierarchical view.
Secondly, when changing the value of the parameter, the following error message appears (see also attached screenshot):

at PKSim.Core.Model.Simulation.GetAltered(String usedBuildingBlockId)
   at PKSim.Core.Commands.EditParameterCommand.setBuildingBlockAlteredFlag(IExecutionContext context)
   at PKSim.Core.Commands.EditParameterCommand.PerformExecuteWith(IExecutionContext context)
   at PKSim.Core.Commands.BuildingBlockChangeCommand.ExecuteWith(IExecutionContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at PKSim.Core.Services.ParameterTask.ResetParameter(IParameter parameter)
   at PKSim.Presentation.Services.EditParameterPresenterTask.ResetParameter(ICommandCollector presenter, IParameterDTO parameterDTO)
   at PKSim.Presentation.Presenters.Parameters.EditParameterPresenter`2.ResetParameter(IParameterDTO parameterDTO)
   at PKSim.UI.Views.Parameters.ParameterSetView.resetParameter()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)

**Comment by TWendl** [comment]
![error message - popsim](https://user-images.githubusercontent.com/26460649/226410022-a3a0b2ec-5d8b-4ed7-b45e-ac626d4d3c36.PNG)

**Comment by Yuri05** [comment]
related to #1010

**Comment by Yuri05** [comment]
>Ref Conc is not available anymore in the list of parameter that can be varied as user defined?

It is available - in the Population BB. However if you did not distribute it, then you cannot see parameters in the simulation at all.

It's actually a general problem, not specific to RefConc or other protein parameters: ALL parameters which are created in a population BB and NOT distributed, cannot be seen in the simulation.
So e.g. all highlighted params below like surface areas, GI-dimensions etc. are not shown in the Pop simulation:

![grafik](https://user-images.githubusercontent.com/25061876/226593601-4d88e9ec-a6aa-44aa-a5ce-ac19f162a8d1.png)

![grafik](https://user-images.githubusercontent.com/25061876/226594148-8733070c-eca5-499a-be84-767892383a57.png)![grafik](https://user-images.githubusercontent.com/25061876/226595278-df13e69d-5c51-48b2-a54b-f2ea922397f2.png)

However you can show those parameters in a pop simulation if you switch to the **hierarchy** view:
![grafik](https://user-images.githubusercontent.com/25061876/226594461-d96b87d8-71a4-4196-be98-842d5eae2dda.png)

Here you can even change the parameters - and if you e.g. try to change the RefConc - you get the error message described by @TWendl 

In general, it would be good to show those parameters in the pop simulation under User Defined variability.

**Comment by msevestre** [comment]
so what's the suggestion? Show all parameters in the parameter list? IMO, the distributed parameter should not be shown. It feels like the logic is backward
