### ISSUE TITLE
EthinylEstradiol PK Sim project file issue

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/PK-Sim#2606]
Hello All,

Unable to open the EE PK-Sim project file in new version 11.2

below is the error message i get

Regards
Harish

Application:
PK-Sim® 11.2.142

file is not a database
file is not a database

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass17_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>g__openProject|0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by PavelBal** [comment]
Where did you get the model? If you download the file from here: https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/tree/master/Ethinylestradiol

you can open it in v11.3 and v12.

Please re-open if the problem persists.
