### ISSUE TITLE
ISSUE/Problem

### ISSUE THREAD

**Issue by Cheruvh** [Open-Systems-Pharmacology/PK-Sim#2608]
Application:
PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Core.Model.ParameterExtensions.IsIndividualMoleculeGlobal(IParameter parameter)
   at PKSim.Core.Model.ParameterExtensions.IsExpressionProfile(IParameter parameter)
   at PKSim.Core.Services.ParameterTask.SetParameterValue(IParameter parameter, Double value, Boolean shouldUpdateDefaultStateAndValueOriginForDefaultParameter)
   at PKSim.Core.Services.ParameterTask.SetParameterValue(IParameter parameter, Double value, ISimulation simulation)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.TransferOptimizedParametersToSimulationsTask`1.updateParameterValue(IdentificationParameter identificationParameter, Double optimalValue, ParameterSelection linkedParameter)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.TransferOptimizedParametersToSimulationsTask`1.<>c__DisplayClass4_0.<setOptimalParameterValueIn>b__0(ParameterSelection linkedParameter)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Commands.Core.MacroCommand`1.AddRange(IEnumerable`1 commandsToAdd)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.TransferOptimizedParametersToSimulationsTask`1.TransferParametersFrom(ParameterIdentification parameterIdentification, ParameterIdentificationRunResult runResult)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.MultipleParameterIdentificationResultsPresenter.TransferToSimulation(ParameterIdentificationRunResultDTO runResultDTO)
   at OSPSuite.UI.Views.ParameterIdentifications.MultipleParameterIdentificationResultsView.transferToSimulation()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Anyways you can help us reproduce the issue?
Can you try with a newer version of the Software
