### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by jhunt8** [Open-Systems-Pharmacology/PK-Sim#2609]
Upon trying to open a previously functioning .pksim5 file:

Application:
PK-Sim® 11.2.142

database disk image is malformed
database disk image is malformed

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite)
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass17_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>g__openProject|0()
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
can you attach the file here so that we can see if we can reproduce?
Is the file saved on a shared drive? Can you copy it locally in this case?

**Comment by msevestre** [comment]
as a note for later

I managed to save the file using
https://www.sqlite.org/recovery.html

and then removing the one entry that was corrupted

**Comment by jhunt8** [comment]
Thank you so much for saving this corrupted file!
