### ISSUE TITLE
Parameter Identification error v.11.2

### ISSUE THREAD

**Issue by AyaSaleh90** [Open-Systems-Pharmacology/PK-Sim#2619]
Hi all,
Recently I have been doing some parameter identification steps but I get this error in either PK-sim or MoBi, so I updated the software to the latest version and now whenever I open the P.I. created earlier I get this error:

Application:
PK-Sim® 11.2.142

An item with the key 'Measurement' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:
```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Presentation.Presenters.Charts.DataBrowserPresenter.<AddDataColumns>b__13_0(DataColumn c)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.Charts.DataBrowserPresenter.AddDataColumns(IEnumerable`1 dataColumns)
   at OSPSuite.Presentation.Presenters.Charts.ChartEditorPresenter.AddDataRepositories(IEnumerable`1 dataRepositories)
   at OSPSuite.Presentation.Presenters.Charts.ChartPresenter`3.AddDataRepositoriesToEditor(IEnumerable`1 dataRepositories)
   at OSPSuite.Presentation.Presenters.Charts.SimulationAnalysisChartPresenter`3.AddObservedDataForOutput(IGrouping`2 outputMappingsByOutput)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationAnalysisChartPresenter`3.AddUsedObservedDataToChart()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationTimeProfileChartPresenter.UpdateAnalysisBasedOn(IReadOnlyList`1 parameterIdentificationResults)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.Charts.SimulationAnalysisChartPresenter`3.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject)
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
This is a follow-up to a known bug that was fixed in V11.3.
An update to version 11.3 is highly recommended.
For now: check your parameter identification configuration for duplicate pairs of {Outputs; Observed Data} and remove duplicate entries. 
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/b410eb8d-bee3-431d-b586-efd784887ffb)
