### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Txl117** [Open-Systems-Pharmacology/PK-Sim#2631]
Application:
PK-Sim® 11.1.137

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending)
   at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at PKSim.Core.Mappers.ProtocolToSchemaItemsMapper.MapFrom(Protocol protocol)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.<CanCalculateGlobalPK>b__33_0(Compound compound)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.CanCalculateGlobalPK()
   at PKSim.Presentation.Presenters.Simulations.PopulationPKAnalysisPresenter.CalculatePKAnalyses(IPopulationDataCollector populationDataCollector, ChartData`2 timeProfileChartData, PopulationStatisticalAnalysis populationAnalysis)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.calculatePKAnalysis()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.RefreshData()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.OnDragDrop(Object sender, IDragEvent e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at PKSim.UI.Views.PopulationAnalyses.BaseChartView`2.OnDragDrop(DragEventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
seems to be related to #2632 

Can you let us know how to reproduce the issue @Txl117 ? Thanks
