### ISSUE TITLE
Error:Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by Atekton** [Open-Systems-Pharmacology/PK-Sim#2632]
Hello,
When I tried to create the population simulation, the PK-analysis failed and the final time profile was very different from the individual on which the model was based.
Were there any steps I missing?
Thanks for any suggestions.
Best,
Atekton
------------------------------------------------------------------------------------------------------------------
<img width="743" alt="螢幕擷取畫面 2023-05-23 185201" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/96116651/e96e295c-d8af-4404-a9cf-ce11caff76d6">
<img width="347" alt="螢幕擷取畫面 2023-05-23 185505" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/96116651/1a0c4914-0929-4104-a9d9-3f46de1d1cae">

Application:
PK-Sim® 11.2.142

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending)
   at System.Linq.Enumerable.OrderBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at PKSim.Core.Mappers.ProtocolToSchemaItemsMapper.MapFrom(Protocol protocol)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.<CanCalculateGlobalPK>b__33_0(Compound compound)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PKSim.Presentation.Presenters.Simulations.GlobalPKAnalysisPresenter.CanCalculateGlobalPK()
   at PKSim.Presentation.Presenters.Simulations.PopulationPKAnalysisPresenter.CalculatePKAnalyses(IPopulationDataCollector populationDataCollector, ChartData`2 timeProfileChartData, PopulationStatisticalAnalysis populationAnalysis)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.calculatePKAnalysis()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.showAnalysis()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.setViewMode(Boolean shouldShowAnalysis)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.SwitchPKAnalysisPlot()
   at PKSim.UI.Views.Charts.BasePKAnalysisWithChartView.switchPKAnalysis()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment]
Can you zip and attach your project?

**Comment by Yuri05** [comment]
@rwmcintosh It happens if we have compounds without administrations.
Simple project to reproduce: [P1_2C_1A.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/11546742/P1_2C_1A.zip)

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/235247f7-256f-452b-9e4b-af739f9cd7c8)

**Comment by Atekton** [comment]
@Yuri05 Did it result from the administration setting? Could I fix it by myself?
Thanks for your help
Best,
Atekton

**Comment by Yuri05** [comment]
@Atekton As a workaround: create dummy administration protocols with ZERO dose and assign them to compounds which are not administered in your population simulations. Then you will be able to show PK analysis
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/a7846ab5-fbf4-49aa-89b9-466fe1b48f3b)

**Comment by Atekton** [comment]
@Yuri05 Thank you! It is really helpful!

**Comment by Yuri05** [comment]
@Atekton Please don't close the issue: it's a bug which must be fixed.

**Comment by Atekton** [comment]
> @Yuri05 Okay! Thanks for your help.

**Comment by Atekton** [comment]
Did I do the right thing.....

**Comment by msevestre** [comment]
We fixed the issue now. It can be closed. Thanks for reporting it 😁
