### ISSUE TITLE
Unhandled Exception when removing PI

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2634]
- open the project from https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2632#issuecomment-1559646687
- open parameter identification for editing
- delete parameter identification
- the error below comes

If you click on Continue: PK-Sim does not work properly anymore (Crashes wehn open any new project, etc.)

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/b02c1d1f-1bd3-436d-bacc-f172541a94ba)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Chart.CurveChart.RemoveCurvesForColumns(IEnumerable`1 dataColumns)
   at OSPSuite.Core.Chart.CurveChart.RemoveCurvesForDataRepository(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationResidualVsTimeChartPresenter.Clear()
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.<>c.<ReleaseFrom>b__13_0(ISimulationAnalysisPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.ReleaseFrom(IEventPublisher eventPublisher)
   at OSPSuite.Presentation.Core.ApplicationController.removePresenter(ISingleStartPresenter presenterToClose)
   at OSPSuite.Presentation.Core.ApplicationController.removePresenter(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OSPSuite.Presentation.Presenters.SingleStartPresenter`2.OnFormClosed()
   at OSPSuite.Presentation.Presenters.SingleStartContainerPresenter`4.OnFormClosed()
   at OSPSuite.UI.Views.BaseMdiChildView.<.ctor>b__2_0(Object o, FormClosedEventArgs e)
   at System.Windows.Forms.FormClosedEventHandler.Invoke(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)



```

**Comment by msevestre** [comment]
this is a core issue. Closing
