### ISSUE TITLE
PKSIM not saving

### ISSUE THREAD

**Issue by audreyoc** [Open-Systems-Pharmacology/PK-Sim#2680]
Application:
PK-Sim® 11.2.142

could not execute query
[ SELECT this_.Id as id1_22_0_, this_.Name as name2_22_0_, this_.Description as description3_22_0_, this_.Version as version4_22_0_, this_.ContentId as contentid5_22_0_ FROM PROJECTS this_ ]
[SQL: SELECT this_.Id as id1_22_0_, this_.Name as name2_22_0_, this_.Description as description3_22_0_, this_.Version as version4_22_0_, this_.ContentId as contentid5_22_0_ FROM PROJECTS this_]
-----------------------------------------------------
SQL logic error
no such table: PROJECTS

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(DbCommand st, QueryParameters queryParameters, ISessionImplementor session, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
 --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFromDatabase(ISession session)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Save(PKSimProject projectToSave, ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.SaveSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.SaveProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass21_0.<saveProjectToFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
@audreyoc Are you saving on your local drive?

**Comment by audreyoc** [comment]
> @audreyoc Are you saving on your local drive?

Yes I am. My local drive has enough space.
