### ISSUE TITLE
after my PI completed I tried to click on time profile button to see the analysis but an error window pops up 

### ISSUE THREAD

**Issue by daniaobd** [Open-Systems-Pharmacology/PK-Sim#2695]
Application:
PK-Sim® 11.2.142

An item with the key 'Measurement' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:
```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Presentation.Presenters.Charts.DataBrowserPresenter.<AddDataColumns>b__13_0(DataColumn c)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.Charts.DataBrowserPresenter.AddDataColumns(IEnumerable`1 dataColumns)
   at OSPSuite.Presentation.Presenters.Charts.ChartEditorPresenter.AddDataRepositories(IEnumerable`1 dataRepositories)
   at OSPSuite.Presentation.Presenters.Charts.ChartPresenter`3.AddDataRepositoriesToEditor(IEnumerable`1 dataRepositories)
   at OSPSuite.Presentation.Presenters.Charts.SimulationAnalysisChartPresenter`3.AddObservedDataForOutput(IGrouping`2 outputMappingsByOutput)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationAnalysisChartPresenter`3.AddUsedObservedDataToChart()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationTimeProfileChartPresenter.UpdateAnalysisBasedOn(IReadOnlyList`1 parameterIdentificationResults)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.Charts.SimulationAnalysisChartPresenter`3.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Handle(SimulationAnalysisCreatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by Yuri05** [comment]
This is a follow-up to a known bug that was fixed in V11.3.
An update to version 11.3 is highly recommended.
For now: check your parameter identification configuration for duplicate pairs of {Outputs; Observed Data} and remove duplicate entries. 
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/b410eb8d-bee3-431d-b586-efd784887ffb)
