### ISSUE TITLE
Unable to import preset compounds,prompt SQL logic error

### ISSUE THREAD

**Issue by stopthinking828** [Open-Systems-Pharmacology/PK-Sim#2698]
I can't import any of the preset compounds and keep getting SQL logic errors,like this.

![1dcec11287813dcb825151cab5d3d53](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/103625340/1b66604e-cf37-4cac-82d4-07df6b4ccc33)

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/103625340/9c7128b7-97fc-4ef1-94d0-7d7b892fbd9b)

at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at PKSim.Infrastructure.ORM.DAS.DAS.FillDataTable(DASDataTable dataTable, String sql)
 --- End of inner exception stack trace ---
   at PKSim.Infrastructure.ORM.DAS.DAS.FillDataTable(DASDataTable dataTable, String sql)
   at PKSim.Infrastructure.Extensions.DASExtensions.ExecuteQueryForDataTable(DAS connection, String query)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateDatabaseType templateDatabaseType, TemplateType templateType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateType templateType)
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplateAsync[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.<LoadFromTemplateAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Services.BuildingBlockTask.<LoadSingleFromTemplateAsync>d__29`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Extensions.ExceptionExtensions.<DoWithinExceptionHandler>d__8`1.MoveNext()

**Comment by Yuri05** [comment]
Seems your user templates database became corrupted. Please create the new one. For this:
Open the program options and click on the ➕ sign (s. screen) then select the new location for the database.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/3a796d20-740e-4f49-a033-26cbbfbbfe8f)
