### ISSUE TITLE
Error when configuring a simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2774]
I cannot share the project, but I will share it internally with @rwmcintosh and @georgeDaskalakis 

Application:
PK-Sim® 11.2.142

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.SimulationQuantitySelection.Clone()
   at OSPSuite.Core.Domain.OutputMapping.Clone()
   at OSPSuite.Core.Domain.OutputMappings.<>c.<UpdatePropertiesFrom>b__1_0(OutputMapping x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at OSPSuite.Core.Domain.OutputMappings.UpdatePropertiesFrom(IUpdatable source, ICloneManager cloneManager)
   at PKSim.Core.Model.Simulation.UpdatePropertiesFrom(IUpdatable sourceObject, ICloneManager cloneManager)
   at OSPSuite.Core.Domain.Services.CloneManagerStrategy.Clone[T](T objectToClone)
   at PKSim.Core.Services.Cloner.createClone[T](T objectToClone, ICloneManager cloneManager)
   at PKSim.Core.Services.Cloner.CloneForModel[T](T objectToClone)
   at PKSim.Presentation.Presenters.Simulations.ConfigureSimulationPresenterBase`1.createSimulationToConfigureBasedOn()
   at PKSim.Presentation.Presenters.Simulations.ConfigureSimulationPresenterBase`1.configureSimulation(Simulation simulation, ISubPresenterItem subPresenterItem, Action actionToPerformBeforeDisplayingView)
   at PKSim.Presentation.Presenters.Simulations.ConfigureSimulationPresenterBase`1.ConfigureSimulation(Simulation simulation)
   at PKSim.Presentation.Services.ConfigureSimulationTask.<>c__DisplayClass8_0.<Configure>b__0(IConfigureSimulationPresenter x)
   at PKSim.Presentation.Services.ConfigureSimulationTask.configure(Simulation simulationToConfigure, Func`2 configureAction)
   at PKSim.Presentation.Services.ConfigureSimulationTask.Configure(Simulation simulationToConfigure)
   at PKSim.Presentation.UICommands.ConfigureSimulationCommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
Happens when not all observed data are mapped to a simulation output.

**Comment by msevestre** [comment]
CAnnot reproduce also in v12. Please try again and reopen if this is not the case
