### ISSUE TITLE
PK-Sim refuses to compare two simulations

### ISSUE THREAD

**Issue by marleysoueu** [Open-Systems-Pharmacology/PK-Sim#2786]
I'm trying to compare two simulations (one with 10 people and the other one with 100) and the software refuses to configure and run :(
What could I do?

This message appears:
Application:
PK-Sim® 11.2.142

Syntax error: Missing operand after 's' operator.

Stack trace:
```
at System.Data.ExpressionParser.Parse()
   at System.Data.DataExpression..ctor(DataTable table, String expression, Type type)
   at System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   at System.Data.DataTable.Select(String filterExpression)
   at OSPSuite.Utility.Data.Pivoter.getData(DataView data, String filter, String dataField, Aggregate aggregate)
   at OSPSuite.Utility.Data.Pivoter.pivotDataFlat(DataView data, PivotInfo pivotInfo)
   at OSPSuite.Utility.Data.Pivoter.PivotData(DataView data, PivotInfo pivotInfo)
   at PKSim.Core.Services.PivotResultCreator.Create(PopulationPivotAnalysis pivotAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.ChartDataCreator`2.CreateResult[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.TimeProfileChartDataCreator.CreateResult[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.ChartDataCreator`2.CreateFor[TPopulationAnalysis](TPopulationAnalysis populationAnalysis, IPopulationDataCollector populationDataCollector, ObservedDataCollection observedDataCollection, Aggregate aggregate)
   at PKSim.Core.Services.ChartDataCreator`2.CreateFor[TPopulationAnalysis](PopulationAnalysisChart`1 populationAnalysisChart, Aggregate aggregate)
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.CreateChartData()
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.RefreshData()
   at PKSim.Presentation.Presenters.Charts.EditTimeProfileAnalysisChartPresenter.RefreshData()
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IPopulationDataCollector populationDataCollector)
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.UpdateAnalysisBasedOn(IAnalysable analysable)
   at PKSim.Presentation.Presenters.Charts.EditPopulationAnalysisChartPresenter`3.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject)
   at PKSim.Presentation.UICommands.CreateSimulationComparisonCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
Hey @marleysoueu 

This is a very unique bug that we have never seen thus far.
Would you be able ton zip the project file and attach it here?
If not (because of confidentiality reasons) can you sent it to me at michael@design2code.ca ? I'll check it out personally

Take care,
Michael

**Comment by msevestre** [comment]
@marleysoueu 
Ok this is because of the 's in the name of the simulation. I am not why this is creating a problem yet but at least, if you rename
`Simulating Koehm's Males` to `Simulating Koehm_s Males` or whatever that does not have an `'`, it will work

**Comment by marleysoueu** [comment]
Thank you, guys!!
