### ISSUE TITLE
PK-sim 12: Crash when loading from snapshot (Application parameters not found)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2831]
Loading from the attached snapshot worked fine up to PK-Sim **12.0.76**
Starting with PK-Sim **12.0.77** various errors occur. The primary error is that some application parameters cannot be found anymore; others are probably just follow-up errors.
[12.0.54_TC_4.77_03.json.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/13348977/12.0.54_TC_4.77_03.json.zip)

```
Information: Loading Project from snapshot file 'C:\Temp\12.0.54_TC_4.77_03.json'
Information: Loading simulation 'S1_Adult_4comp' (1/3)...
Warning: Snapshot parameter 'Applications|App1|Application_12|ProtocolSchemaItem|Infusion time' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Application_14|ProtocolSchemaItem|Infusion time' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Application_2|ProtocolSchemaItem|Infusion time' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Dissolved|Application_3|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Lint80|Application_10|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Lint80|Application_13|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Particles|Application_5|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Particles|Application_7|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Table|Application_11|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Table|Application_9|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Snapshot parameter 'Applications|App1|Weibull|Application_4|ProtocolSchemaItem|Volume of water/body weight' was not found in 'S1_Adult_4comp'.
Warning: Simulation run failed: some variables became negative when trying to reach t=674.9909313718235. There are different possible reasons for this:

  - Solver tolerances are too high. Please reduce the absolute and relative tolerances by one order of magnitude (e.g. from 1E-9 to 1E-10) and restart the simulation.
  - Some variables which are allowed to be negative were defined as non-negative.
  - Model is not properly established (e.g. the kinetic should be k*[A] but was defined as k*[B] etc.)

The following variables became negative :
S1_Adult_4comp|Events|App1|Lint80|Application_10|C1
Error: Cannot load Simulation 'S1_Adult_4comp'
Information: Loading simulation 'S2_Preterm_Protein' (1/3)...
Information: Loading simulation 'S3_Adults_4comp' (2/3)...
Warning: Cannot find simulation 'S1_Adult_4comp'
Warning: Cannot find simulation 'S1_Adult_4comp'
Warning: Cannot find simulation 'S1_Adult_4comp'
Error: Object reference not set to an instance of an object.

Stack trace:
at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.<>c.<CreateFor>b__5_1(ParameterSelection x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.CreateFor(IEnumerable`1 parameterSelections, ParameterIdentification parameterIdentification)
   at PKSim.Core.Snapshots.Mappers.IdentificationParameterMapper.<MapToModel>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__8`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ParameterIdentificationMapper.<MapToModel>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__8`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<MapToModel>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshotAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshotFileAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadProjectFromSnapshotPresenter.<LoadModelAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<performLoadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<StartAsync>d__16.MoveNext()
```

**Comment by Yuri05** [comment]
ok, that's probably because we removed the Applications node and the snapshot was already saved with the earlier version of PK-Sim 12 and thus no snapshot conversion occurs. 
So probably nothing to do here?

**Comment by Yuri05** [comment]
OK, I'm closing the issue.
There is still a problem with this particular project: one simulation, which was running before, does not run anymore (negative values) - but this has nothing to do with the snapshot.

another problem with the snapshot (will create a separate issue for that): if a PI cannot be loaded from snapshot - the whole snapshot loading process crashes and no simulations are restored

**Comment by msevestre** [comment]
Yes about the applications and the conversion/.
Why stuff becomes negative, I have no idea. @PavelBal Created one issue already about this. Someone with good eye needs to look at this =>>> YOU
