### ISSUE TITLE
Project file cannot be opened

### ISSUE THREAD

**Issue by CDarlow** [Open-Systems-Pharmacology/PK-Sim#2832]
Hi,

A project file I've been working on for several weeks with multiple simulations has seemingly corrupted with the below error message appearing upon opening. Can anyone advise if it is possible to recover the project file?

Thank you

Kind Regards

 Application:
PK-Sim® 11.2.142

Array cannot be null.
Parameter name: bytes

Stack trace:
```
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserialize(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<MapFrom>b__6_2(BuildingBlockMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass17_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>g__openProject|0()
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker)
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions)
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run()
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by rwmcintosh** [comment]
Possibly related https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2217

**Comment by rwmcintosh** [comment]
Closing as related issue is closed. If you need help recovering the project let us know.
