### ISSUE TITLE
PK-sim suddenly gives een error when opening the model, can I retrieve it?

### ISSUE THREAD

**Issue by KarenLeys** [Open-Systems-Pharmacology/PK-Sim#2875]
Hello,

I get the following error message when I try to open my PK-sim model for fentanyl that seemed to work perfectly last time I opened it and worked on it last week. After the error is closed, none of the inputs (individual, compounds, etc) I put into the software are there. 
I don't know what changed from all other times I saved, closed and then tried to open the model again.
Can my model be retrieved or do I have to start from scratch? (Last backup was several weeks ago.)

Application:
PK-Sim® 11.2.142

Value cannot be null.
Parameter name: key

Stack trace:
```
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.DataRepositoryXmlSerializer.TypedDeserialize(DataRepository dataRepository, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(ObservedDataMetaData observedDataMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<MapFrom>b__6_0(ObservedDataMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(ICoreWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.<>c__DisplayClass17_0.<OpenProject>b__0()
   at PKSim.Infrastructure.Workspace.LoadProject(Action projectLoadAction)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass32_0.<openProjectFromFile>g__openProject|0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

Thanks for taking a look!
Karen

**Comment by Yuri05** [comment]
3 observed data sets were corrupted. After removing them: it is possible to open the project (s. the attachment here). The removed observed data sets were not used in any simulation. If you need to use them later, you need to reimport the data.
* `Auspar 2014 200 µg IN. Auspar 2014 200 µg IV (adapt).{Molecule}.Human.Plasma`
* `Auspar 2014 400 µg IN.Auspar 2014 400 µg IN (adapt).Fentanyl (Kovar 2020) adult.Plasma.Human`
* `Auspar 2014 800 µg IN.Auspar 2014 800 µg IN (adapt).Fentanyl (Kovar 2020) adult.Plasma.Human`

[Fentanyl (2)_repaired.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/14432941/Fentanyl.2._repaired.zip)

Which version of PK-Sim did you use when you imported those observed data sets?

**Comment by Yuri05** [comment]
@msevestre Exactly the same problem as [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1589#issuecomment-726810544)
Again, extended property without a name 
<details><summary><b>Problematic data set<b></summary>
<p>

```
<?xml version="1.0" encoding="utf-8"?>
<McDataRepository id="a9d59b16-dcf4-43e6-905a-d57c0fc3c878" name="Auspar 2014 200 µg IN. Auspar 2014 200 µg IV (adapt).{Molecule}.Human.Plasma" icon="ObservedData" configurationId="24f57659-7290-411d-8fe9-15e9a2fab322" xmlVersion="79">
  <Columns>
    <McBaseGrid id="dbec9ac2-51d2-4c10-8394-ed838f9d0659" name="Time" dimension="Time" isInternal="0" baseGrid="dbec9ac2-51d2-4c10-8394-ed838f9d0659">
      <DataInfo origin="BaseGrid" auxiliaryType="Undefined" displayUnitName="h" />
      <QuantityInfo type="Time" orderIndex="0" Path="Auspar 2014 200 µg IN. Auspar 2014 200 µg IV (adapt).{Molecule}.Human.Plasma|Time" />
      <Values>AAEAAAD/////AQAAAAAAAAAPAQAAAAsAAAALnr2dQJ69HUFainFBlTSgQQAA8EEAADRCAABwQgAAtEIAAPBCAAA0QwAAcEML</Values>
      <RelatedColumnsCache />
    </McBaseGrid>
    <McDataColumn id="085e1e5f-c737-4e93-9311-5ba08db9081b" name="Measurement" dimension="Concentration (mass)" isInternal="0" baseGrid="dbec9ac2-51d2-4c10-8394-ed838f9d0659">
      <DataInfo origin="Observation" auxiliaryType="Undefined" displayUnitName="pg/ml" />
      <QuantityInfo type="Undefined" orderIndex="0" Path="Auspar 2014 200 µg IN. Auspar 2014 200 µg IV (adapt).{Molecule}.Human.Plasma|ObservedData||Plasma||Measurement" />
      <Values>AAEAAAD/////AQAAAAAAAAAPAQAAAAsAAAALK+ShL7xrJDDzPkAw3XopMMe2EjCaitkv0i+7LwrVnC9jiYMvu5leL7AgNi8L</Values>
      <RelatedColumnsCache />
    </McDataColumn>
  </Columns>
  <ExtendedProperties>
    <StringExtendedProperty name="Sheet" readOnly="0" />
    <StringExtendedProperty name="Species" readOnly="0" value="Human" />
    <StringExtendedProperty name="Compartment" readOnly="0" value="Plasma" />
    <StringExtendedProperty readOnly="0" />
  </ExtendedProperties>
</McDataRepository>

```
</p>
</details>

**Comment by KarenLeys** [comment]
Thank you so much! 

I used PK-Sim 11.2

Did I do something wrong to cause this corruption or is there any way for me to avoid getting in this situation again?

**Comment by Yuri05** [comment]
> Did I do something wrong to cause this corruption or is there any way for me to avoid getting in this situation again?

It's a glitch in the software, which is very rare and hard to reproduce.

**Comment by harishkaushikbugworks** [comment]
I have created this file in PK SIM 12.1 and recently upgared to 12.2 from then i cant open this file and it throws above erro shown above in this chat group , help me to open this file [Azacytidine (2).zip](https://github.com/user-attachments/files/28544725/Azacytidine.2.zip)

**Comment by Yuri05** [comment]
> I have created this file in PK SIM 12.1 and recently upgared to 12.2 from then i cant open this file and it throws above erro shown above in this chat group , help me to open this file [Azacytidine (2).zip](https://github.com/user-attachments/files/28544725/Azacytidine.2.zip)

The attached project is empty (0KB).
