### ISSUE TITLE
11.3 Crash in cloned PI after project save/load

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2882]
[03_Carbamazepine_11.3.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/14654013/03_Carbamazepine_11.3.pksim5.zip)
* Open the project attached
* Clone parameter identification **PI1** to **PI2**. Cloned PI looks good so far
<img width="350" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/368ddb1a-9bff-4f7a-b1f9-31082e0eeebe">

* Save the project and close it
* Reopen the project and open **PI2** - the error below comes
```
Application:
PK-Sim® 11.3.197

Array cannot be null.
Parameter name: bytes

Stack trace:
at System.Text.Encoding.GetString(Byte[] bytes)
   at OSPSuite.Serializer.Xml.XmlHelper.ElementFromBytes(Byte[] serializationByte)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.ElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.getConvertedElementFrom(Byte[] serializationBytes)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.ParameterIdentificationContentLoader.LoadContentFor(ParameterIdentification parameterIdentification)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
...
```
* After click on "Close": PI opens and is totally corrupted
<img width="400" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/efec4eb9-dd2f-40e6-bf87-b34094630c40">

**Comment by Yuri05** [comment]
11.2 has the same problem

**Comment by msevestre** [comment]
OH MY GOSH! Can you reproduce this consistently?
Finally an example

**Comment by rwmcintosh** [comment]
Content is NULL in the project database. Not surprising. So, why does it get stored like that? Investigating rn.

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/261477/10eb0ce2-0eaa-4d61-bd6a-c2504221dcba)

**Comment by rwmcintosh** [comment]
Could be added to this hotfix I think. I'll PR into 11.3 and we can see.
