### ISSUE TITLE
Adding Expression DB?

### ISSUE THREAD

**Issue by cbruno14** [Open-Systems-Pharmacology/PK-Sim#2899]
Hi I'm super new to PK-Sim (v 11.3) so I apologize if this is a really silly question, but I'm having a bad time trying to figure out how to upload a Human protein expression DB. I've downloaded the human gene expression file [here](https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v11.3), but when I go to Options --> Application and try to link the Human expression database I receive the following error:
`The requested operation cannot be performed on a file with a user-mapped section open.`

With the following Stack Trace:

```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Xml.XmlTextWriter..ctor(String filename, Encoding encoding)
   at OSPSuite.Serializer.Xml.XmlHelper.saveXmlObjectToFile(String fileName, Action`1 saveAction)
   at OSPSuite.Serializer.Xml.XmlHelper.saveXmlContentToFile(String xmlContent, String fileName)
   at PKSim.Infrastructure.Services.SettingsPersistor`1.Save(TSettings userSettings)
   at PKSim.Infrastructure.Services.UserSettingsPersistor.Save(IUserSettings userSettings)
   at PKSim.Presentation.Presenters.UserSettingsPresenter.SaveSettings()
   at PKSim.Presentation.Presenters.SettingsPresenter.saveSettings()
   at PKSim.Presentation.Presenters.SettingsPresenter.Initialize()
   at OSPSuite.Presentation.Core.ApplicationController.Start[TPresenter]()
   at OSPSuite.Presentation.UICommands.RunPresenterCommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

I was originally working within a project space, but I've tried restarting the application and repeating these steps in the absence of any building blocks to no avail. Can someone explain how to add the protein expression data for use in PBPK modeling?

**Comment by rwmcintosh** [comment]
The new database file path is being saved to user settings somewhere on the file system, but it appears that that location is not accessible to the program, or the file is open in another editor and cannot be updated.

The file is being updated is `C:\Users\<USERID>\AppData\Roaming\Open Systems Pharmacology\PK-Sim\11.3\UserSettings.xml` unless you chose another option during installation.
