### ISSUE TITLE
PK-Sim 12: `Could not load file or assembly 'Microsoft.Win32.Registry'`

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2924]
When trying to send simulation from PK-Sim to MoBi:
```
Application:
PK-Sim® 12.0.0

Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden.

Stack trace:

at PKSim.Infrastructure.PKSimConfiguration.get_MoBiPath()
   at PKSim.Infrastructure.Services.MoBiExportTask.retrieveMoBiExecutablePath() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\Services\MoBiExportTask.cs:line 95
   at PKSim.Infrastructure.Services.MoBiExportTask.startMoBiWithFile(Func`1 contentFileFullPathFunc, String option) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\Services\MoBiExportTask.cs:line 79
   at PKSim.Infrastructure.Services.MoBiExportTask.StartWith(Simulation simulation) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Infrastructure\Services\MoBiExportTask.cs:line 64
   at PKSim.Presentation.UICommands.ExportSimulationToMoBiCommand.PerformExecute() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\UICommands\ExportSimulationToMoBiCommand.cs:line 19
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute() in C:\SW-Dev\OSPSuite.Core\branches\11.1\src\OSPSuite.Presentation\UICommands\ObjectUICommands.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator) in C:\SW-Dev\OSPSuite.Core\branches\11.1\src\OSPSuite.Presentation\UICommands\UICommandExtensions.cs:line 26
```

**Comment by Yuri05** [comment]
Works after clean/rebuild Closing
