### ISSUE TITLE
Application: PK-Sim® 11.3.208

### ISSUE THREAD

**Issue by yanzh1222** [Open-Systems-Pharmacology/PK-Sim#2970]
Application:
PK-Sim® 11.3.208

Access to the path 'C:\ProgramData\Open Systems Pharmacology\PK-Sim\11.3\ApplicationSettings.xml' is denied.

Stack trace:
```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Xml.XmlTextWriter..ctor(String filename, Encoding encoding)
   at OSPSuite.Serializer.Xml.XmlHelper.saveXmlObjectToFile(String fileName, Action`1 saveAction)
   at OSPSuite.Serializer.Xml.XmlHelper.saveXmlContentToFile(String xmlContent, String fileName)
   at PKSim.Infrastructure.Services.SettingsPersistor`1.Save(TSettings userSettings)
   at PKSim.Infrastructure.Services.SettingsPersistor`1.SaveCurrent()
   at PKSim.UI.UICommands.ExitCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by rwmcintosh** [comment]
Does the folder exist there, if it does, do you have access to edit/add content?
