### ISSUE TITLE
Errors just when reopening a finished Parameter Identification

### ISSUE THREAD

**Issue by nguyen-tranbach** [Open-Systems-Pharmacology/PK-Sim#3002]
**Error 1:**
Application:
PK-Sim® 11.3.208

Id N6eTQp1Dm0urBzAPo66lAg-MF1408|Organism|PeripheralVenousBlood|DTG_F18|Fraction unchanged DTG-36001acd-229f-4dfd-b737-f2915346d6f6-1-Time not unique

Stack trace:
```
at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.Register(IWithId withId)
   at OSPSuite.Core.Serialization.Xml.DataColumnXmlSerializer`1.TypedDeserialize(T column, XElement element, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.DataRepositoryXmlSerializer.TypedDeserialize(DataRepository dataRepository, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Chart.CurveChartXmlSerializer`1.TypedDeserialize(TCurveChart curveChart, XElement outputToDeserialize, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.ParameterIdentificationXmlSerializer.TypedDeserialize(ParameterIdentification parameterIdentification, XElement parameterIdentificationElement, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(Object objectToDeserialize, XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(T objectToRead, XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.ParameterIdentificationContentLoader.LoadContentFor(ParameterIdentification parameterIdentification)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Error 2:**
Application:
PK-Sim® 11.3.208

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.MapFrom(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.MapDataTableFromColumns()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.Rebind()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.EditObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataPresenter.Edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationDataSelectionPresenter.observedDataSelected(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationDataSelectionPresenter.<.ctor>b__10_4(Object o, ObservedDataEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationOutputMappingPresenter.<>c__DisplayClass37_0.<Select>b__0()
   at OSPSuite.Utility.Extensions.LatchableExtensions.DoWithinLatch(ILatchable latchable, Action action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationOutputMappingPresenter.Select(OutputMappingDTO outputMappingDTO)
   at OSPSuite.UI.Views.ParameterIdentifications.ParameterIdentificationOutputMappingView.selectItem(OutputMappingDTO selectedItem)
   at OSPSuite.UI.Views.ParameterIdentifications.ParameterIdentificationOutputMappingView.selectFocusedElement()
   at OSPSuite.UI.Views.ParameterIdentifications.ParameterIdentificationOutputMappingView.gridViewRowChanged(FocusedRowChangedEventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by Yuri05** [comment]
Could you upload the project (zip it first)?

**Comment by nguyen-tranbach** [comment]
The file is so big that I cannot upload it. How should I send it to you?

**Comment by StephanSchaller** [comment]
@Yuri05 ?
