### ISSUE TITLE
Expression profile inheritance does not work

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#3015]
[39_Protein_Inheritance.zip](https://github.com/user-attachments/files/17621569/39_Protein_Inheritance.zip)
E.g. in the attached example, projects P1 and P2 both have the protein expression building block **"E1|Human|Healthy"**
```
{
  "Version": 79,
  "ExpressionProfiles": [
    {
      "Type": "Enzyme",
      "Species": "Human",
      "Molecule": "E1",
      "Category": "Healthy",
      "Parameters": [
...
```

In the qualification plan, P2 should inherit the protein expression **"E1|Human|Healthy"** from P1.

```
    "Projects": [
        {
            "Id": "P1",
            "Path": "./P1.json"
        },
        {
            "Id": "P2",
            "Path": "./P2.json",
            "BuildingBlocks": [
                {
                    "Type": "ExpressionProfile",
                    "Name": "E1|Human|Healthy",
                    "Project": "P2"
                }
            ]
        }
    ],

```

When trying to execute the qualification plan via the QualificationRunner: it crashes

**_QualificationRunner.exe -i QualiPlan.json -o output --norun_**
`[2024-11-04 18:12:21.902 PK-Sim ERROR] Could not find ExpressionProfile 'E1|Human|Healthy' in snapshot 'P2'. `

**Comment by msevestre** [comment]
Yeah. we have a failing test
![image](https://github.com/user-attachments/assets/2286037c-b522-49b3-8703-779a2d4bae66)

**Comment by Yuri05** [comment]
Still crashes, but with another error message.
QualiRunner **12.0.1**
PK-Sim **12.0.424**

<details><summary>Console Output</summary>

```
..\QualificationRunner_12.0.1\QualificationRunner.exe -i QualiPlan.json -o output --norun -p C:\Datenaustausch\00000_Verifications\PK-Sim_12.0.424 --logLevel Debug
info: QualificationRunner[0]
      Starting qualification workflow
dbug: QualificationRunner[0]
      Arguments:
Log file:
      Log level: Debug
      Configuration file: QualiPlan.json
      Output folder: output
      Run simulations: False
      Export project files: False

dbug: QualificationRunner[0]
      Copying static files
info: QualificationRunner[0]
      Starting validation runs...
dbug: QualificationRunner[0]
      Starting qualification run for project 'P1'
dbug: QualificationRunner[0]
      Qualification configuration for project 'P1' exported to 'output\temp\P1\config.json'
dbug: QualificationRunner[0]
      Starting qualification run for project 'P2'
dbug: QualificationRunner[0]
      Qualification configuration for project 'P2' exported to 'output\temp\P2\config.json'
fail: QualificationRunner[0]
      Project configuration for 'P2' is invalid. Please check the log file at 'output\temp\P2\log.txt' for details.
fail: QualificationRunner[0]
      Qualification Workflow failed
```
</details> 

[log.txt](https://github.com/user-attachments/files/18457650/log.txt)

Error message from the log file:

```
 [2025-01-17 17:52:18.966 PK-Sim ERROR] Object reference not set to an instance of an object.

Stack trace:
at OSPSuite.Core.Domain.Constants.NamesFromCompositeName(String compositeName, Char separator)
   at OSPSuite.Core.Domain.Constants.ContainerName.NamesFromExpressionProfileName(String expressionProfileName)
   at PKSim.Core.Snapshots.Project.BuildingBlockByTypeAndName(PKSimBuildingBlockType buildingBlockType, String name)
   at PKSim.Core.Snapshots.Project.Swap(IBuildingBlockSnapshot newBuildingBlock)
   at PKSim.CLI.Core.Services.QualificationRunner.<swapBuildingBlockIn>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.CLI.Core.Services.QualificationRunner.<RunBatchAsync>d__10.MoveNext()
 --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command) 
 
```

**Comment by msevestre** [comment]
ok I can reproduce. Fix coming soon
