### ISSUE TITLE
Error exporting plot to Excel

### ISSUE THREAD

**Issue by nguyen-tranbach** [Open-Systems-Pharmacology/PK-Sim#3017]
This happens when I tried to export a Residual vs. Time plot from a Parameter Identification to Excel

Application:
PK-Sim® 11.3.208

The workbook already contains a sheet named 'Simulation Results for Run 1_100'

Stack trace:
```
at NPOI.XSSF.UserModel.XSSFWorkbook.ValidateSheetName(String sheetName)
   at NPOI.XSSF.UserModel.XSSFWorkbook.CreateSheet(String sheetname)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.exportDataTableToWorkBook(IWorkbookConfiguration workBookConfiguration, DataTable dataTable)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, IWorkbookConfiguration workBookConfiguration)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataTables, String fileName, Boolean launchExcel)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataColumns, String fileName, Boolean launchExcel, DataColumnExportOptions exportOptions)
   at OSPSuite.Core.Services.CurveChartExportTask.ExportToExcel(CurveChart chart)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.ExportToExcel()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
Can you upload the project?

**Comment by nguyen-tranbach** [comment]
You can find the project in this [link](http://iame.catibiomed.fr/index.php/s/pXHFqFwPjYmvOgv)

I tried to export to Excel the forementionned plot from DTG_All_B_Sch_EHC in Parameter Identification
