### ISSUE TITLE
PK Analysis data copying issue

### ISSUE THREAD

**Issue by sarugesh** [Open-Systems-Pharmacology/PK-Sim#3026]
Hi 

Could not able to copy the PK analysis report, Kindly let me the solve the issue.

Best,
Murugesh

Application:
PK-Sim® 11.3.208

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.<>c__DisplayClass14_0.<getColumnName>b__0(PivotGridField field)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.getColumnName(PivotGridCells input, Int32 columnIndex)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.configureDataTable(PivotGridCells input, DataTable dt, Func`2 useColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.map(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter, Func`2 shouldUseRow, Func`2 shouldUseColumn)
   at OSPSuite.UI.Mappers.PivotGridCellsToDataTableMapper.MapFrom(PivotGridCells pivotGridCells, Func`2 displayNameRetreiver, Func`2 valueToDisplayConverter)
   at OSPSuite.UI.Controls.UxPivotGrid.copyAllCellsToClipboard()
   at OSPSuite.UI.Controls.UxPivotGrid.<>c__DisplayClass13_0.<OnKeyDown>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```
![Issue](https://github.com/user-attachments/assets/90dc426e-cb64-4914-b5b9-465adb18d432)

**Comment by Yuri05** [comment]
Is it possible to upload your project for investigation?
