### ISSUE TITLE
Old Procect do not open up in new Version 7.1

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#313]
Ok that's a tough experiance with the 7.1 Version. I tried to open up Projekts from 6.4 and earlier and that happens. B.t.w I haven't run the installation validation. Were was the tool and how to?

Application:
PK-Sim® 7.1.0 - Build 63

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
1 is not a supported code page.
Parameter name: codepage

Stack trace:
```
at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToString(Byte[] data, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToStringExt(Int32 flags, Byte[] data)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at OSPSuite.Infrastructure.Services.SharpLibCompression.Decompress(Byte[] byteArrayToDecompress)
   at PKSim.Core.Services.CompressedSerializationManager.decompressedByte(Byte[] serializationBytes)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserializeProperty[T](IMetaDataWithProperties metaData, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.Visit(IndividualMetaData individualMetaData)
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitMethod[T](IVisitor visitor, T objectToVisit, MethodInfo method)
   at OSPSuite.Utility.Visitor.VisitorInvoker.InvokeVisit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorExtensions.Visit[T](IVisitor visitor, T objectToVisit)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.mapFrom(BuildingBlockMetaData buildingBlockMetaData)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.<>c__DisplayClass5_0.<MapFrom>b__1(BuildingBlockMetaData x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Infrastructure.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at PKSim.Infrastructure.Serialization.ProjectPersistor.Load(ISession session)
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath)
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath)
   at PKSim.Presentation.Services.ProjectTask.<>c__DisplayClass26_0.<openProjectFromFile>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by msevestre** [comment]
This should work without any problem. As mentioned in the other issue, something is wrong with your installation

**Comment by msevestre** [comment]
A little bit of googling. This has something to do with your régional settings. 
What OS are you using?
What language/ region are you using?

**Comment by msevestre** [comment]
@tobiasK2001 
Can you start PowerShell on your machine and type the following command

```
[System.Threading.Thread]::CurrentThread.CurrentCulture.TextInfo
```

And send us back what is being outputted?
All thread I am looking at points to a corrupted Windows Install but I'd like to check what's the outcome there on your machine

**Comment by msevestre** [comment]
duplicates 
#314

**Comment by tobiasK2001** [comment]
Dear Micheal, can you please open this agaim? here are the results of Powershell:

ANSICodePage   : 1252
OEMCodePage    : 850
MacCodePage    : 10000
EBCDICCodePage : 20285
LCID           : 2057
CultureName    : en-GB
IsReadOnly     : False
ListSeparator  : ,
IsRightToLeft  : False

**Comment by tobiasK2001** [comment]
Oh no, I just opened PK-sim again... everything is going well. I can load template and old projects and everything. All is running smoothly. And the only major thing I changed is switching from McAfee to Nortn Antivirus....can that be? :-)
So I gess you can close it again, but keep in mind: never use McAfee with PK-sim

**Comment by msevestre** [comment]
@tobiasK2001 great to hear that this is fixed. This mostly has nothing to do with McAfee nor Norton nor PK-Sim. 
Your windows installation was for some reason corrupted (the OEMCodePage of 0 ist not a valid value!). Now it's returning the expected 850 which is the value that was expected with your installation. Probably a simple reboot might have fixed the issue (Wenn der Rechner nichts tut, reboot!)

Cheers,
Michael

**Comment by tobiasK2001** [comment]
yeah, reboot tut gut;-)
