### ISSUE TITLE
Loading of templates not possible in 7.1

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#314]
Tried to create a new project in PK-Sim with predefined templates and this is what happened...
Application:
PK-Sim® 7.1.0 - Build 63

1 is not a supported code page.
Parameter name: codepage

Stack trace:
```
at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToString(Byte[] data, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToStringExt(Int32 flags, Byte[] data)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at OSPSuite.Infrastructure.Services.SharpLibCompression.Decompress(Byte[] byteArrayToDecompress)
   at OSPSuite.Utility.Compression.StringCompression.Decompress(String stringToDecompress)
   at PKSim.Infrastructure.Serialization.CompressedStringSerializer.Deserialize[TObject](String serializationString)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.LoadTemplate[T](Template template)
   at PKSim.Presentation.Presenters.TemplatePresenter.loadTemplate[T](Template template)
   at PKSim.Presentation.Presenters.TemplatePresenter.loadSingleTemplate[T]()
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplate[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.LoadFromTemplate[TBuildingBlock](PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.CompoundTask.LoadFromTemplate(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate()
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadSingleFromTemplate()
   at PKSim.Presentation.UICommands.LoadBuildingBlockFromTemplateUICommand`2.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
Something is wrong with your installation. Were you ever able to load template?

**Comment by tobiasK2001** [comment]
no not with this Version/ Installation. What can I do?

**Comment by tobiasK2001** [comment]
This is the system Iam trying to run it: ![image](https://user-images.githubusercontent.com/25585248/30162997-739856da-93d7-11e7-9efc-7a7a0609524f.png)
Doing a simple simulation from the scratch worked so far

**Comment by msevestre** [comment]
What are you language settings? Regional settings or whatever they are called?

**Comment by msevestre** [comment]
You probably won't be able to load any of the example project either. Can you try just to confirm?

**Comment by msevestre** [comment]
@tobiasK2001 I guess this is not an issue anymore?

**Comment by tobiasK2001** [comment]
Hi Micheal, Sorry I am on a Business trip with no or low Internet. I try to check next week.
Best, Tobias

**Comment by Yuri05** [comment]
I guess this issue can be closed now due to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/313#issuecomment-331235079 ?

**Comment by tobiasK2001** [comment]
Yes, it is fine now:-)
