### ISSUE TITLE
Cannot reopen project with imported MoBi simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#462]
[Cefazolin.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1474430/Cefazolin.zip)

Steps2reproduce:
* open **Cefazolin_Test** project (created with 7.2) 
* go to Import/Export => Population simulation
* select **Cefazolin_pregnancy.pkml** (created with MoBi 6.3) and combine it with the POP population building block

Save the project, close and reopen it. Try to open the population simulation. The error below occurs
```Application:
PK-Sim® 7.2.0 - Build 0

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack trace:

at OSPSuite.Core.Domain.Services.ReferencesResolver.resolveReferences(IEnumerable`1 entityUsingFormulas) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ReferencesResolver.cs:line 28
   at OSPSuite.Core.Domain.Services.ReferencesResolver.ResolveReferencesIn(IContainer container) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ReferencesResolver.cs:line 21
   at OSPSuite.Core.Domain.Services.ReferencesResolver.ResolveReferencesIn(IModel model) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ReferencesResolver.cs:line 16
   at PKSim.Infrastructure.Serialization.SimulationUpdaterAfterDeserialization.UpdateSimulation(Simulation simulation) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Infrastructure\Serialization\SimulationUpdaterAfterDeserialization.cs:line 22
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.updatePropertiesFor[TObject](TObject deserializedObject, Int32 originalVersion, Boolean xmlConversionHappened) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Infrastructure\Serialization\Xml\XmlSerializationManager.cs:line 185
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Infrastructure\Serialization\Xml\XmlSerializationManager.cs:line 124
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Core\Services\CompressedSerializationManager.cs:line 47
   at PKSim.Infrastructure.Services.ContentLoader.LoadContentFor[T](T objectToLoad) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Infrastructure\Services\ContentLoader.cs:line 24
   at PKSim.Infrastructure.Services.LazyLoadTask.loadObjectBase[T](T objectToLoad) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Infrastructure\Services\LazyLoadTask.cs:line 88
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad) in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Infrastructure\Services\LazyLoadTask.cs:line 55
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0() in C:\VSS\PK-Sim\branches\7.2\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 31
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Services\HeavyWorkManager.cs:line 97
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Services\HeavyWorkManager.cs:line 62
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

P.S. Before reopening the project population simulation can be calculated and correct results are produced.

**Comment by msevestre** [comment]
Can a simple simulation pkml be saved and opened in PKSim?

What does that mean that it is a 6.3? Was the structure adjusted to the new pop parameters?

**Comment by msevestre** [comment]
Die Formula for PArameter volume in Myometrium is the problem. What's special about it?

**Comment by msevestre** [comment]
The problem is in Core. 
see https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/281
