### ISSUE TITLE
PK-Sim coverage stopped working

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#501]
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim-y8yi5

```
rake cover
 -register:user -target:nunit3-console.exe -targetargs:tests/PKSim.Tests/PKSim.Tests.csproj -output:OpenCover.xml -filter:+[PKSim.Core]* +[PKSim.Assets]* +[PKSim.Presentation]* +[PKSim.Infrastructure]* -excludebyfile:*.Designer.cs
rake aborted!
TypeError: no implicit conversion of nil into String
C:/projects/pk-sim-y8yi5/scripts/utils.rb:38:in `block in <top (required)>'
C:/projects/pk-sim-y8yi5/scripts/utils.rb:25:in `run_cmd'
C:/projects/pk-sim-y8yi5/scripts/coverage.rb:9:in `cover'
C:/projects/pk-sim-y8yi5/rakefile.rb:13:in `block in <top (required)>'
Tasks: TOP => cover
(See full trace by running task with --trace)
Command exited with code 1
```

**Comment by msevestre** [comment]
sorry wrong assignee
