### ISSUE TITLE
error message when transfering optimization results to simulation

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#603]
and subsequent re-running of simulation results.

---------------------------
Unhandled Exception
---------------------------
A generic error occurred in GDI+.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

Stack trace:

at System.Drawing.Image.FromHbitmap(IntPtr hbitmap, IntPtr hpalette)

   at System.Drawing.Image.FromHbitmap(IntPtr hbitmap)

   at System.Drawing.Icon.ToBitmap()

   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)

   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)

   at System.Windows.Forms.Control.WndProcException(Exception e)

   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)

   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.Run(ApplicationContext context)

   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()

   at PKSim.UI.BootStrapping.PKSimApplication.OnRun()

   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)

   at PKSim.Program.Main(String[] args)
---------------------------
OK   
---------------------------

**Comment by msevestre** [comment]
Not much we can do here. Your PC cannot handle more graphics being created at that stage. Probably been running for too long. Close everything, restart and you should be good to go
