### ISSUE TITLE
CLI Snapshot: Crash when input folder does not exist => Message should be clearer

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#686]
The attempt to create a CLI shapshot with the sorafenib test model (issue 648) results in an exception error. All of my other test project work fine.

```
C:\Program Files (x86)\Open Systems Pharmacology\PK-Sim 7.3>PKSim.CLI snap -o m:
\test -i m:\test\Sorrafenib -s
info: PK-Sim[0]
      Starting snapshot run with arguments:
Input Folder: m:\test\Sorrafenib
      Output Folder: m:\test
      Log file:
      Log level: Information
      Export mode: Snapshot

info: PK-Sim[0]
      Starting snapshot run: 2018-05-07 12:08

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'm:\te
st\Sorrafenib'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String origina
lUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`
1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOptio
n searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern)
   at PKSim.CLI.Core.Services.SnapshotRunner.allFilesFrom(String folder, String
filter)
   at PKSim.CLI.Core.Services.SnapshotRunner.<allFilesFrom>d__13.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PKSim.CLI.Core.Services.SnapshotRunner.<RunBatchAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PKSim.CLI.Program.startCommand[TRunOptions](CLICommand`1 command)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Ac
tion`1 action)
   at PKSim.CLI.Program.Main(String[] args)




Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	PKSim.CLI.exe
  Problemsignatur 02:	7.3.0.12
  Problemsignatur 03:	5aecca8d
  Problemsignatur 04:	mscorlib
  Problemsignatur 05:	4.7.2116.0
  Problemsignatur 06:	59c475d2
  Problemsignatur 07:	165d
  Problemsignatur 08:	fc
  Problemsignatur 09:	System.AggregateException
  Betriebsystemversion:	6.1.7601.2.1.0.272.7
  Gebietsschema-ID:	1033
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789

Lesen Sie unsere Datenschutzbestimmungen online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0407

Wenn die Onlinedatenschutzbestimmungen nicht verfügbar sind, lesen Sie unsere Datenschutzbestimmungen offline:
  C:\Windows\system32\de-DE\erofflps.txt
```

**Comment by Yuri05** [comment]
@UlrichSi Can you reproduce the issue with the same project if it's copied to a local drive (e.g. C:\temp)?

**Comment by UlrichSi** [comment]
@Yuri05 You're right, it works if the project file is stored locally. The network path will crash PKsim.CLI.

**Comment by msevestre** [comment]
This is weird:
`Could not find a part of the path 'm:\test\Sorrafenib' `

Did you loose connectivity on your M drive? Does it ALWAYS crash with this project located on the M drive when started from CLI?

**Comment by msevestre** [comment]
Sorry: Does folder `m:\test\Sorrafenib` exists??

**Comment by msevestre** [comment]
Agreed.

**Comment by msevestre** [comment]
This is the new output

```
info: PK-Sim[0]
      Starting snapshot run with arguments:
Input Folder: m:\test\Sorrafenib
      Output Folder: m:
      Log file:
      Log level: Information
      Export mode: Snapshot

info: PK-Sim[0]
      Starting snapshot run: 2018-05-07 10:54
fail: PK-Sim[0]
      'm:\test\Sorrafenib' does not exist!
info: PK-Sim[0]
      0 project loaded and exported in '00m:00s:00ms'
info: PK-Sim[0]
      Snapshot run finished: 2018-05-07 10:54
info: PK-Sim[0]
      Snapshot run finished

```

**Comment by UlrichSi** [comment]
looks fine to me - will such an error message also occur if an invalid input directory is used with the "run" or "export" commands?

**Comment by msevestre** [comment]
no idea:)
