### ISSUE TITLE
Errors importing from Snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#753]
7.3.0.20 
Open example project https://github.com/Open-Systems-Pharmacology/Example_Aciclovir/blob/master/Aciclovir.pksim5 and export to snapshot.
Then try to load a project from exported snapshot: it fails with some warnings and errors

<details><summary>Import Errors</summary>

```
Information: Loading Project from snapshot file 'C:\temp\Aciclovir.json'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Laskin_1982_GroupA'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Laskin_1982_GroupB'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Laskin_1982_GroupC'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Laskin_1982_GroupD'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Vergin 1995 IV'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Vergin 1995 200mg tablet'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Vergin 1995 400mg tablet'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Palma 2007'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Palma 2007 Zovirax Table'
Warning: Parameter 'Fraction unbound (plasma, reference value)' defined in molecule 'Aciclovir' has an invalid value: NaN

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
Error: Cannot load Simulation 'Palma 2007 Zovirax weibull'
Error: Object reference not set to an instance of an object.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

Stack trace:
at OSPSuite.Core.Domain.Project.GetOrCreateClassifiableFor[TClassifiable,TSubject](TSubject subject)
   at PKSim.Core.Snapshots.Mappers.ClassificationSnapshotTask.<>c__DisplayClass3_0`2.<updateProjectFor>b__0(String snapshotClassifiable)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at PKSim.Core.Snapshots.Mappers.ClassificationSnapshotTask.<updateProjectFor>d__3`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<MapToModel>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBase`2.<MapToModel>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadModelFromSnapshot>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshot>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadProjectFromSnapshotPresenter.<LoadModelAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<PerformLoad>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<Start>d__14.MoveNext()

```
</details>

**Comment by msevestre** [comment]
Can you attach the snapshot file? that way I don't have to create it myself

**Comment by Yuri05** [comment]
[Aciclovir.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2013220/Aciclovir.zip)
PK-Sim project created before 7.3
All simulations are in "green" state.

**Comment by msevestre** [comment]
Is there a reason why those simulations cannot be loaded? Many are throwing an error

**Comment by msevestre** [comment]
```
  "FractionUnbound": [
        {
          "Name": "Human",
          "Species": "Human"
        },
        {
          "Name": "Rat",
          "IsDefault": false,
          "Species": "Rat"
        },
        {
          "Name": "Dog",
          "IsDefault": false,
          "Species": "Dog"
        }
      ],
```
fraction unbound is not defined?!?

**Comment by msevestre** [comment]
no value there

**Comment by msevestre** [comment]
The exception is due to the fact that some simulations were not created properly and then we try to classify them (e.g. put them in folder). That can be fixed easily. Does not explain why fu values are not exported tho

**Comment by msevestre** [comment]
ok this is because the fu IsDefault is true after conversion and the parameter is not exported... double weird

**Comment by Yuri05** [comment]
>ok this is because the fu IsDefault is true after conversion and the parameter is not exported... double weird

Can be a problem with NaN-comparison?

```
      public static bool ValueDiffersFromDefault(this IParameter parameter)
      {
         if (!parameter.Editable)
            return false;

         if (parameter.Formula.IsExplicit() || parameter.Formula.IsDistributed())
            return parameter.IsFixedValue;

         if (parameter.DefaultValue == null)
            return false;

         return !ValueComparer.AreValuesEqual(parameter.Value, parameter.DefaultValue.Value, CoreConstants.DOUBLE_RELATIVE_EPSILON);
      }
```

**Comment by msevestre** [comment]
That's an error during project conversion.

**Comment by Yuri05** [comment]
```
    public static bool AreValuesEqual(double value1, double value2, double relTol)
    {
      if (double.IsNaN(value1))
        return double.IsNaN(value2);
      if (value1 == 0.0)
        return value2 == 0.0;
      return Math.Abs((value1 - value2) / value1) <= relTol;
    }
```

Yep, I think what is missing here is:

```
      if (double.IsNaN(value2))
        return double.IsNaN(value1);
```

**Comment by msevestre** [comment]
ok fix is coming

**Comment by msevestre** [comment]
This is fixed. However there is sill one simulation that reports solver error when being ran. If you find out why, create another issue :)
