### ISSUE TITLE
Snapshort import problem

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#788]
7.0.3.27 
Wenn importing project from snapshot (attached) multiple errors and warnings appear.
Project used for export created with 7.3 (started with 7.0.3.22 or 7.3.0.23, finished with 7.3.0.27)

[SnapshotImportProblem_01.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2027419/SnapshotImportProblem_01.zip)

<details><summary>Import errors</summary>

```
Information: Loading Project from snapshot file 'C:\TC_4.77_Snapshots_09.json'
Error: Object reference not set to an instance of an object.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

Stack trace:
at OSPSuite.Core.Domain.Descriptors.MatchTagCondition.Equals(Object otherObject) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Descriptors\MatchTagCondition.cs:line 44
   at OSPSuite.Core.Domain.Descriptors.DescriptorCriteria.Equals(DescriptorCriteria other) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Descriptors\DescriptorCriteria.cs:line 32
   at OSPSuite.Core.Domain.Descriptors.DescriptorCriteria.Equals(Object obj) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Descriptors\DescriptorCriteria.cs:line 42
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.Contains(TKey key) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Collections\Cache.cs:line 189
   at OSPSuite.Core.Domain.Services.EventBuilderTask.addApplicationTransports(IApplicationBuilder applicationBuilder, IEventGroup eventGroup) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 141
   at OSPSuite.Core.Domain.Services.EventBuilderTask.createEventGroupInContainer(IEventGroupBuilder eventGroupBuilder, IContainer sourceContainer) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 124
   at OSPSuite.Core.Domain.Services.EventBuilderTask.createEventGroupFrom(IEventGroupBuilder eventGroupBuilder, IMoleculeBuildingBlock molecules) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 105
   at OSPSuite.Core.Domain.Services.EventBuilderTask.CreateEvents(IBuildConfiguration buildConfiguration, IModel model) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 69
   at OSPSuite.Core.Domain.Services.ModelConstructor.createObserversAndEvents(IModel model, IBuildConfiguration buildConfiguration) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ModelConstructor.cs:line 211
   at OSPSuite.Core.Domain.Services.ModelConstructor.buildProcess(IModel model, IBuildConfiguration buildConfiguration, Func`3[] steps) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ModelConstructor.cs:line 145
   at OSPSuite.Core.Domain.Services.ModelConstructor.CreateModelFrom(IBuildConfiguration buildConfiguration, String modelName) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ModelConstructor.cs:line 77
   at PKSim.Core.Services.SimulationModelCreator.CreateModelFor(Simulation simulation, Boolean shouldValidate, Boolean shouldShowProgress) in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Services\SimulationModelCreator.cs:line 58
   at PKSim.Core.Snapshots.Mappers.SimulationMapper.<createSimulationFrom>d__41.MoveNext() in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Snapshots\Mappers\SimulationMapper.cs:line 319
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SimulationMapper.<MapToModel>d__33.MoveNext() in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Snapshots\Mappers\SimulationMapper.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<allSmulationsFrom>d__34.MoveNext() in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Snapshots\Mappers\ProjectMapper.cs:line 247
Error: Cannot load Simulation 'S2_Preterm_Protein'
Error: Object reference not set to an instance of an object.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

Stack trace:
at OSPSuite.Core.Domain.Descriptors.MatchTagCondition.Equals(Object otherObject) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Descriptors\MatchTagCondition.cs:line 44
   at OSPSuite.Core.Domain.Descriptors.DescriptorCriteria.Equals(DescriptorCriteria other) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Descriptors\DescriptorCriteria.cs:line 32
   at OSPSuite.Core.Domain.Descriptors.DescriptorCriteria.Equals(Object obj) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Descriptors\DescriptorCriteria.cs:line 42
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.Contains(TKey key) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Collections\Cache.cs:line 189
   at OSPSuite.Core.Domain.Services.EventBuilderTask.addApplicationTransports(IApplicationBuilder applicationBuilder, IEventGroup eventGroup) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 141
   at OSPSuite.Core.Domain.Services.EventBuilderTask.createEventGroupInContainer(IEventGroupBuilder eventGroupBuilder, IContainer sourceContainer) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 124
   at OSPSuite.Core.Domain.Services.EventBuilderTask.createEventGroupFrom(IEventGroupBuilder eventGroupBuilder, IMoleculeBuildingBlock molecules) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 105
   at OSPSuite.Core.Domain.Services.EventBuilderTask.CreateEvents(IBuildConfiguration buildConfiguration, IModel model) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\EventBuilderTask.cs:line 69
   at OSPSuite.Core.Domain.Services.ModelConstructor.createObserversAndEvents(IModel model, IBuildConfiguration buildConfiguration) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ModelConstructor.cs:line 211
   at OSPSuite.Core.Domain.Services.ModelConstructor.buildProcess(IModel model, IBuildConfiguration buildConfiguration, Func`3[] steps) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ModelConstructor.cs:line 145
   at OSPSuite.Core.Domain.Services.ModelConstructor.CreateModelFrom(IBuildConfiguration buildConfiguration, String modelName) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ModelConstructor.cs:line 77
   at PKSim.Core.Services.SimulationModelCreator.CreateModelFor(Simulation simulation, Boolean shouldValidate, Boolean shouldShowProgress) in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Services\SimulationModelCreator.cs:line 58
   at PKSim.Core.Snapshots.Mappers.SimulationMapper.<createSimulationFrom>d__41.MoveNext() in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Snapshots\Mappers\SimulationMapper.cs:line 319
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SimulationMapper.<MapToModel>d__33.MoveNext() in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Snapshots\Mappers\SimulationMapper.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<allSmulationsFrom>d__34.MoveNext() in C:\VSS\PK-Sim\branches\7.3\src\PKSim.Core\Snapshots\Mappers\ProjectMapper.cs:line 247
Error: Cannot load Simulation 'S3_Adults_4comp'
Warning: Could not find quantity with path 'S2_Preterm_Protein|Organism|PeripheralVenousBlood|C2|Plasma (Peripheral Venous Blood)'.
Information: Project loaded from snapshot
```
</details>

**Comment by msevestre** [comment]
yeah this is probably due to the TargetCompartment not being exported?!?

**Comment by Yuri05** [comment]
Import works now. Great!
