### ISSUE TITLE
Error when trying to "Load from template"

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#852]
When using "Load from template" or "Save as Template" from the context menus of the BB explorer, the error message below pops up. This happens with all BB types. 

Application:
PK-Sim® 7.3.0.42

Das Microsoft Jet-Datenbankmodul findet die Eingangstabelle oder Abfrage 'TAB_TEMPLATES' nicht. Stellen Sie sicher, dass sie existiert und der Name richtig eingegeben wurde.

Stack trace:
```
at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at PKSim.Infrastructure.ORM.DAS.DAS.ExecuteSQL(String sql)
   at PKSim.Infrastructure.Services.TemplateDatabaseConverter.convertDataBaseSchemaTo53(DAS database)
   at PKSim.Infrastructure.Services.TemplateDatabaseConverter.Convert(ITemplateDatabase templateDatabase)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.establishConnection(TemplateDatabaseType templateDatabaseType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateDatabaseType templateDatabaseType, TemplateType templateType)
   at PKSim.Infrastructure.Services.TemplateTaskQuery.AllTemplatesFor(TemplateType templateType)
   at PKSim.Presentation.Presenters.TemplatePresenter.LoadFromTemplate[T](TemplateType templateType)
   at PKSim.Presentation.Services.BuildingBlockTask.LoadFromTemplate[TBuildingBlock](PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate(PKSimBuildingBlockType buildingBlockType)
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadFromTemplate()
   at PKSim.Presentation.Services.BuildingBlockTask`1.LoadSingleFromTemplate()
   at PKSim.Presentation.UICommands.LoadBuildingBlockFromTemplateUICommand`2.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
Seems you are using a wrong template Db?
Please check under options (create new if needed)

**Comment by UlrichSi** [comment]
Thanks so much, Yuri05 - that seemed to have been wrongly set by something, since I didn't touch it after installation. It was put on "C:\ProgramData\Open Systems Pharmacology" instead of pointing to the version's subdirectory.
