### ISSUE TITLE
Exception error in Parameter Identification when adding a new simulation

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#884]
If an invalid line is present in the Data tab, the exception error below is thrown.

To reproduce:
1. Load the project "Theophylline" from the examples folder.
2. Create a PI task
3. Click on "Add Output". An empty line with error symbols is displayed.
4. Click on "Add Simulation". Check any of the suggested simulations. Then click "Ok".

A more informative error message or no error message at all (since the output table already contains the symbols) is recommendable here, even though it is pretty obvious what went wrong. 

 
Application:
PK-Sim® 7.3.0.42

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.ParameterIdentifications.ParameterIdentification.<>c.<get_AllObservedData>b__74_0(OutputMapping x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at OSPSuite.Core.Domain.ParameterIdentifications.ParameterIdentification.UsesObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Services.ParameterIdentificationTask.addOutputMapping(IQuantity output, String outputPath, DataRepository observedData, ISimulation simulation, ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Services.ParameterIdentificationTask.<>c__DisplayClass30_1.<addOutputMappingsFor>b__0(DataRepository obs)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Services.ParameterIdentificationTask.addOutputMappingsFor(ISimulation simulation, ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Services.ParameterIdentificationTask.AddSimulationTo(ParameterIdentification parameterIdentification, ISimulation simulation)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationSimulationSelectionPresenter.AddSimulation(ISimulation simulation)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationSimulationSelectionPresenter.AddSimulations(IEnumerable`1 simulations)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationSimulationSelectionPresenter.doWithSimulationSelectionPresenter(Action`1 action, Boolean allowMultipleSelections)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationSimulationSelectionPresenter.SelectSimulationsToAdd()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
Cannot reproduce.
