### ISSUE TITLE
Examples installed with 7.1 are all corrupted

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#89]
Only happens with installed examples; all other projects can be opened without problem

Error message:
Application:
PK-Sim® 7.1.0 - Build 22

database disk image is malformed
database disk image is malformed

Stack trace:
```
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at OSPSuite.Core.Extensions.DbConnectionExtensions.ExecuteNonQuery(IDbConnection sqlLite, String query) in C:\projects\ospsuite-core\src\OSPSuite.Core\Extensions\DbConnectionExtensions.cs:line 34
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.migrateTo5_3(SQLiteConnection sqlite) in C:\projects\pk-sim\src\PKSim.Infrastructure\Serialization\DatabaseSchemaMigrator.cs:line 36
   at PKSim.Infrastructure.Serialization.DatabaseSchemaMigrator.MigrateSchema(String fileFullPath) in C:\projects\pk-sim\src\PKSim.Infrastructure\Serialization\DatabaseSchemaMigrator.cs:line 25
   at PKSim.Infrastructure.Serialization.WorkspacePersistor.LoadSession(IWorkspace workspace, String fileFullPath) in C:\projects\pk-sim\src\PKSim.Infrastructure\Serialization\WorkspacePersistor.cs:line 87
   at PKSim.Infrastructure.Workspace.OpenProject(String fileFullPath) in C:\projects\pk-sim\src\PKSim.Infrastructure\Workspace.cs:line 101
   at PKSim.Presentation.Services.ProjectTask.openProjectFromFile(String projectFile, Boolean shouldStartWorker) in C:\projects\pk-sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 282
   at PKSim.Presentation.Services.ProjectTask.Run(StartOptions startOptions) in C:\projects\pk-sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 196
   at PKSim.Presentation.Presenters.Main.PKSimMainViewPresenter.Run() in C:\projects\pk-sim\src\PKSim.Presentation\Presenters\Main\PKSimMainViewPresenter.cs:line 73
   at PKSim.UI.Views.Shell.<OnLoad>b__4_0() in C:\projects\pk-sim\src\PKSim.UI\Views\Shell.cs:line 69
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Extensions\ExceptionExtensions.cs:line 16
```

**Comment by Yuri05** [comment]
MoBi example projects are OK

**Comment by rwmcintosh** [comment]
@Yuri05 Is that new for Build 22? Or not sure?

**Comment by Yuri05** [comment]
Didn't try for previous builds
