### ISSUE TITLE
Zooming in/out on Time Profile Analysis throws error message

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#909]
In the attached file, zooming in and out on the Time Profile Analysis with the mouse wheel generates the _oops... something went terribly wrong_ error message shown below.
The error seems to pop up only if simulated curves are included with a low relative/absolute tolerance in solver settings (i.e. with "bumpy" curves in lower concentration range), such as the lumen concentrations in the attached simulation file.

[Caffeine_Test.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2257094/Caffeine_Test.zip)

Application:
PK-Sim® 7.3.0.42

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.UI.Views.Charts.ChartDisplayView.GetPointsForSecondaryAxis(Single x, Single y, AxisTypes yAxisType)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.setSecondaryAxisRange(Single xMin, Single xMax, Single yMin, Single yMax, AxisTypes axisType)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.<>c__DisplayClass36_0.<SetVisibleRange>b__0(AxisTypes axisType)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.SetVisibleRange(Nullable`1 xMin, Nullable`1 xMax, Nullable`1 yMin, Nullable`1 yMax)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.postZoom(RangeInfo xRange, RangeInfo yRange)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.onZoom(ChartZoomEventArgs e)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.<>c__DisplayClass22_2.<InitializeResources>b__13()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
And finally fixed.
