### ISSUE TITLE
Could not connect the human db database to PK-sim 7.3 portable

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#914]
I try to connect the human db from varios locations. When it tried to add Enzyme via expression database this Error occurs.

Application:
PK-Sim® 7.3.0.42

The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.

Stack trace:
```
at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dataProvider, String connectionString)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String workgroupDb, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.Core.Database.Connect(String databasePath)
   at PKSim.Infrastructure.ORM.Core.DatabaseDisposer..ctor(IDatabase database, String databasePath)
   at PKSim.Infrastructure.Services.ProteinExpressionsDatabasePathManager.ConnectToDatabaseFor(Species species)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.proteinFromQuery(TSimulationSubject simulationSubject, IndividualMolecule newMolecule)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.AddMoleculeTo[TMolecule](TSimulationSubject simulationSubject)
   at PKSim.Presentation.Presenters.Individuals.MoleculesPresenter`1.AddMolcule[TMolecule]()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by StephanSchaller** [comment]
I have run in the same issue.

The OSPS Setup may be missing the Access Database Engine?
When looking for the issue on the net, I found this [thread ](https://stackoverflow.com/questions/6649363/microsoft-ace-oledb-12-0-provider-is-not-registered-on-the-local-machine).

Installing the [2007 Office System Driver: Data Connectivity Components](https://www.microsoft.com/en-us/download/details.aspx?id=23734) solved it for me (but make sure the Expression Database you are using is the most recent one as otherwise it may be password protected).

**Comment by tobiasK2001** [comment]
Dear Stephan,

indeed downloading the lates Version of the Expression database helped here ;-) Thanks for the tip!

Best, Tobias

**Comment by tobiasK2001** [comment]
no I didn't change that. Actually I use Windows 10 pro amd Office 365.

**Comment by Yuri05** [comment]
OK, closing. @tobiasK2001 Let us know if you face any further problems
