### ISSUE TITLE
Can not run old PI

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#94]
Open any PI in the project attached (created with PK-sim 6.3.2) and run it. Different errors are shown:

* PI1

```
Application:
PK-Sim® 7.1.0 - Build 23

Specified argument was out of the range of valid values.
Parameter name: StandardParameterIdentificationRunMode

Stack trace:

at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunFactory.CreateFor(ParameterIdentification parameterIdentification, CancellationToken cancellationToken) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunFactory.cs:line 37
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<>c__DisplayClass12_0.<createParameterIdentificationRuns>b__0() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<createParameterIdentificationRuns>d__12.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<StartAsync>d__6.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunner.<Run>d__8.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunner.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Extensions\TaskExtensions.cs:line 26
```
* PI2:
```
Application:
PK-Sim® 7.1.0 - Build 23

Specified argument was out of the range of valid values.
Parameter name: MultipleParameterIdentificationRunMode

Stack trace:
at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunFactory.CreateFor(ParameterIdentification parameterIdentification, CancellationToken cancellationToken) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunFactory.cs:line 37
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<>c__DisplayClass12_0.<createParameterIdentificationRuns>b__0() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<createParameterIdentificationRuns>d__12.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<StartAsync>d__6.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunner.<Run>d__8.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunner.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Extensions\TaskExtensions.cs:line 26
```

* PI3
Cannot even be opened. Error message:
PK-Sim®
```
No license found for calculation method 'IntestinalPermeability_CACO_MPTC'.
```

[6.3.2_OptimizationTest.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/907704/6.3.2_OptimizationTest.zip)

**Comment by msevestre** [comment]
Where is this license message coming from?

**Comment by msevestre** [comment]
@Yuri05 I have created #100 for license issue: Message should be different

**Comment by msevestre** [comment]
Fixed with Open-Systems-Pharmacology/OSPSuite.Core#40
