### ISSUE TITLE
Manual editing of observed data: error after deleting value

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#942]
When manually editing observed data and (mistakenly by pressing Del or Backspace) deleting a value and hitting enter, the error message below is thrown. For some reason, the empty cell is kept afterwards and not flagged red, as done for invalid entries.

![grafik](https://user-images.githubusercontent.com/27352743/45489030-7527fb80-b763-11e8-8490-84861c3c0b2f.png)

![grafik](https://user-images.githubusercontent.com/27352743/45488981-5b86b400-b763-11e8-8a8b-e8231bac1ce7.png)

**Comment by UlrichSi** [comment]
Still not working in v. 7.4.95 EAP. Pressing backspace, then moving down with the cursor or pressing Enter results in an exception error. This time it is:
Application:
PK-Sim® 7.4.0.95

Input string was not in a correct format.

Stack trace:
```
at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at OSPSuite.Utility.Extensions.ConversionExtensions.ConvertedTo[T](Object itemToConvert)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryDataPresenter.GetCellValidationErrorMessages(Int32 rowIndex, Int32 columnIndex, String newValue)
   at OSPSuite.UI.Views.ObservedData.DataRepositoryDataView.gridEditorValidating(BaseContainerValidateEditorEventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass24_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by msevestre** [comment]
Can confirm it's still there. Let me check if the fix actually landed in the code :)

**Comment by msevestre** [comment]
all right should be fixed now. Please try..again
