### ISSUE TITLE
Cannot run a Parameter Identification

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#96]
Any parameter identification fails with 

Application:
PK-Sim® 7.1.0 - Build 23

Specified argument was out of the range of valid values.
Parameter name: StandardParameterIdentificationRunMode

Stack trace:
```
at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunFactory.CreateFor(ParameterIdentification parameterIdentification, CancellationToken cancellationToken) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunFactory.cs:line 37
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<>c__DisplayClass12_0.<createParameterIdentificationRuns>b__0() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<createParameterIdentificationRuns>d__12.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationEngine.<StartAsync>d__6.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationEngine.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.ParameterIdentificationRunner.<Run>d__8.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\ParameterIdentificationRunner.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Core.Extensions.TaskExtensions.<SecureAwait>d__2`1.MoveNext() in C:\projects\ospsuite-core\src\OSPSuite.Core\Extensions\TaskExtensions.cs:line 26
```

**Comment by rwmcintosh** [comment]
@PavelBal is that a new PI or a PI from an existing project?
Does this issue repeat #96

**Comment by PavelBal** [comment]
This happens with the new PI.

Open empty project, create an individual, compound, and administration, load dummy data and create a new PI. Assign data to anything and select some parameter to optimize (does not matter, which one). Select "run", and the exception is thrown.

I cannot see how I can attach a PK-Sim project to the issue?

**Comment by rwmcintosh** [comment]
I think we can close this one and just mention the steps to repeat in #94

**Comment by msevestre** [comment]
This is a registration issue. Let's have the fix close both issues once this is implemented. Issues are clearly duplicated
